//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AdjudicationStatusCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AdjudicationStatusCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="2"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="NA"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "AdjudicationStatusCodeType")
@XmlEnum
public enum AdjudicationStatusCodeType {


    /**
     * 
     * 						Pending/Waiting Further Action - Indicates that the SAC or BI 
     * 						has not yet been adjudicated
     * 					
     * 
     */
    P,

    /**
     * 
     * 						Required - Indicates that the SAC or BI 
     * 						has not yet been submitted to OPM
     * 					
     * 
     */
    R,

    /**
     * 
     * 						Complete - Indicates that the SAC or BI has been 
     * 						successfully adjudicated
     * 					
     * 
     */
    C,

    /**
     * 
     * 						N/A - Indicates that an enrollment is for non-PIV use, 
     * 						where a particular investigation is not required.
     * 					
     * 
     */
    NA;

    public String value() {
        return name();
    }

    public static AdjudicationStatusCodeType fromValue(String v) {
        return valueOf(v);
    }

}
