//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardPersonalizationLocationTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardPersonalizationLocationTypeCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Local"/&gt;
 *     &lt;enumeration value="Remote"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CardPersonalizationLocationTypeCodeType")
@XmlEnum
public enum CardPersonalizationLocationTypeCodeType {

    @XmlEnumValue("Local")
    LOCAL("Local"),
    @XmlEnumValue("Remote")
    REMOTE("Remote");
    private final String value;

    CardPersonalizationLocationTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CardPersonalizationLocationTypeCodeType fromValue(String v) {
        for (CardPersonalizationLocationTypeCodeType c: CardPersonalizationLocationTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
