//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CardIssuanceStateCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CardIssuanceStateCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="40"/&gt;
 *     &lt;enumeration value="CARD_NOT_REQUESTED"/&gt;
 *     &lt;enumeration value="CARD_REQUESTED"/&gt;
 *     &lt;enumeration value="CARD_ISSUED"/&gt;
 *     &lt;enumeration value="CARD_SUSPENDED"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CardIssuanceStateCodeType")
@XmlEnum
public enum CardIssuanceStateCodeType {


    /**
     * 
     * 						PIV card not requested 
     * 					
     * 
     */
    CARD_NOT_REQUESTED,

    /**
     * PIV card requested but not yet issued
     * 
     */
    CARD_REQUESTED,

    /**
     * PIV card issued
     * 
     */
    CARD_ISSUED,

    /**
     * PIV card issued but currently suspended
     * 
     */
    CARD_SUSPENDED;

    public String value() {
        return name();
    }

    public static CardIssuanceStateCodeType fromValue(String v) {
        return valueOf(v);
    }

}
