//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountryCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CountryCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="AA"/&gt;
 *     &lt;enumeration value="AB"/&gt;
 *     &lt;enumeration value="AD"/&gt;
 *     &lt;enumeration value="AE"/&gt;
 *     &lt;enumeration value="AF"/&gt;
 *     &lt;enumeration value="AG"/&gt;
 *     &lt;enumeration value="AH"/&gt;
 *     &lt;enumeration value="AI"/&gt;
 *     &lt;enumeration value="AJ"/&gt;
 *     &lt;enumeration value="AK"/&gt;
 *     &lt;enumeration value="AL"/&gt;
 *     &lt;enumeration value="AM"/&gt;
 *     &lt;enumeration value="AN"/&gt;
 *     &lt;enumeration value="AO"/&gt;
 *     &lt;enumeration value="AP"/&gt;
 *     &lt;enumeration value="AQ"/&gt;
 *     &lt;enumeration value="AR"/&gt;
 *     &lt;enumeration value="AS"/&gt;
 *     &lt;enumeration value="AT"/&gt;
 *     &lt;enumeration value="AU"/&gt;
 *     &lt;enumeration value="AV"/&gt;
 *     &lt;enumeration value="AX"/&gt;
 *     &lt;enumeration value="AZ"/&gt;
 *     &lt;enumeration value="BA"/&gt;
 *     &lt;enumeration value="BB"/&gt;
 *     &lt;enumeration value="BC"/&gt;
 *     &lt;enumeration value="BD"/&gt;
 *     &lt;enumeration value="BE"/&gt;
 *     &lt;enumeration value="BF"/&gt;
 *     &lt;enumeration value="BG"/&gt;
 *     &lt;enumeration value="BH"/&gt;
 *     &lt;enumeration value="BI"/&gt;
 *     &lt;enumeration value="BJ"/&gt;
 *     &lt;enumeration value="BK"/&gt;
 *     &lt;enumeration value="BL"/&gt;
 *     &lt;enumeration value="BM"/&gt;
 *     &lt;enumeration value="BN"/&gt;
 *     &lt;enumeration value="BO"/&gt;
 *     &lt;enumeration value="BP"/&gt;
 *     &lt;enumeration value="BQ"/&gt;
 *     &lt;enumeration value="BR"/&gt;
 *     &lt;enumeration value="BS"/&gt;
 *     &lt;enumeration value="BT"/&gt;
 *     &lt;enumeration value="BU"/&gt;
 *     &lt;enumeration value="BV"/&gt;
 *     &lt;enumeration value="BW"/&gt;
 *     &lt;enumeration value="BX"/&gt;
 *     &lt;enumeration value="BY"/&gt;
 *     &lt;enumeration value="BZ"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="CB"/&gt;
 *     &lt;enumeration value="CC"/&gt;
 *     &lt;enumeration value="CD"/&gt;
 *     &lt;enumeration value="CE"/&gt;
 *     &lt;enumeration value="CF"/&gt;
 *     &lt;enumeration value="CG"/&gt;
 *     &lt;enumeration value="CH"/&gt;
 *     &lt;enumeration value="CI"/&gt;
 *     &lt;enumeration value="CJ"/&gt;
 *     &lt;enumeration value="CL"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="CO"/&gt;
 *     &lt;enumeration value="CP"/&gt;
 *     &lt;enumeration value="CQ"/&gt;
 *     &lt;enumeration value="CR"/&gt;
 *     &lt;enumeration value="CS"/&gt;
 *     &lt;enumeration value="CT"/&gt;
 *     &lt;enumeration value="CU"/&gt;
 *     &lt;enumeration value="CV"/&gt;
 *     &lt;enumeration value="CW"/&gt;
 *     &lt;enumeration value="CY"/&gt;
 *     &lt;enumeration value="CZ"/&gt;
 *     &lt;enumeration value="DA"/&gt;
 *     &lt;enumeration value="DB"/&gt;
 *     &lt;enumeration value="DC"/&gt;
 *     &lt;enumeration value="DD"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="DF"/&gt;
 *     &lt;enumeration value="DG"/&gt;
 *     &lt;enumeration value="DH"/&gt;
 *     &lt;enumeration value="DI"/&gt;
 *     &lt;enumeration value="DJ"/&gt;
 *     &lt;enumeration value="DK"/&gt;
 *     &lt;enumeration value="DL"/&gt;
 *     &lt;enumeration value="DM"/&gt;
 *     &lt;enumeration value="DN"/&gt;
 *     &lt;enumeration value="DO"/&gt;
 *     &lt;enumeration value="DP"/&gt;
 *     &lt;enumeration value="DR"/&gt;
 *     &lt;enumeration value="DS"/&gt;
 *     &lt;enumeration value="DT"/&gt;
 *     &lt;enumeration value="DV"/&gt;
 *     &lt;enumeration value="DW"/&gt;
 *     &lt;enumeration value="EE"/&gt;
 *     &lt;enumeration value="EK"/&gt;
 *     &lt;enumeration value="EL"/&gt;
 *     &lt;enumeration value="EN"/&gt;
 *     &lt;enumeration value="EO"/&gt;
 *     &lt;enumeration value="ER"/&gt;
 *     &lt;enumeration value="ES"/&gt;
 *     &lt;enumeration value="ET"/&gt;
 *     &lt;enumeration value="EU"/&gt;
 *     &lt;enumeration value="EY"/&gt;
 *     &lt;enumeration value="EZ"/&gt;
 *     &lt;enumeration value="FA"/&gt;
 *     &lt;enumeration value="FC"/&gt;
 *     &lt;enumeration value="FD"/&gt;
 *     &lt;enumeration value="FG"/&gt;
 *     &lt;enumeration value="FJ"/&gt;
 *     &lt;enumeration value="FL"/&gt;
 *     &lt;enumeration value="FN"/&gt;
 *     &lt;enumeration value="FO"/&gt;
 *     &lt;enumeration value="FP"/&gt;
 *     &lt;enumeration value="FR"/&gt;
 *     &lt;enumeration value="FS"/&gt;
 *     &lt;enumeration value="FX"/&gt;
 *     &lt;enumeration value="GA"/&gt;
 *     &lt;enumeration value="GB"/&gt;
 *     &lt;enumeration value="GC"/&gt;
 *     &lt;enumeration value="GD"/&gt;
 *     &lt;enumeration value="GE"/&gt;
 *     &lt;enumeration value="GF"/&gt;
 *     &lt;enumeration value="GG"/&gt;
 *     &lt;enumeration value="GI"/&gt;
 *     &lt;enumeration value="GJ"/&gt;
 *     &lt;enumeration value="GK"/&gt;
 *     &lt;enumeration value="GM"/&gt;
 *     &lt;enumeration value="GN"/&gt;
 *     &lt;enumeration value="GO"/&gt;
 *     &lt;enumeration value="GP"/&gt;
 *     &lt;enumeration value="GR"/&gt;
 *     &lt;enumeration value="GS"/&gt;
 *     &lt;enumeration value="GT"/&gt;
 *     &lt;enumeration value="GU"/&gt;
 *     &lt;enumeration value="GY"/&gt;
 *     &lt;enumeration value="GZ"/&gt;
 *     &lt;enumeration value="HD"/&gt;
 *     &lt;enumeration value="HE"/&gt;
 *     &lt;enumeration value="HI"/&gt;
 *     &lt;enumeration value="HK"/&gt;
 *     &lt;enumeration value="HL"/&gt;
 *     &lt;enumeration value="HN"/&gt;
 *     &lt;enumeration value="HO"/&gt;
 *     &lt;enumeration value="HR"/&gt;
 *     &lt;enumeration value="HS"/&gt;
 *     &lt;enumeration value="HT"/&gt;
 *     &lt;enumeration value="HU"/&gt;
 *     &lt;enumeration value="IA"/&gt;
 *     &lt;enumeration value="IB"/&gt;
 *     &lt;enumeration value="IC"/&gt;
 *     &lt;enumeration value="ID"/&gt;
 *     &lt;enumeration value="IE"/&gt;
 *     &lt;enumeration value="II"/&gt;
 *     &lt;enumeration value="IL"/&gt;
 *     &lt;enumeration value="IM"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="IO"/&gt;
 *     &lt;enumeration value="IQ"/&gt;
 *     &lt;enumeration value="IR"/&gt;
 *     &lt;enumeration value="IS"/&gt;
 *     &lt;enumeration value="IT"/&gt;
 *     &lt;enumeration value="IU"/&gt;
 *     &lt;enumeration value="IW"/&gt;
 *     &lt;enumeration value="IX"/&gt;
 *     &lt;enumeration value="IY"/&gt;
 *     &lt;enumeration value="JA"/&gt;
 *     &lt;enumeration value="JE"/&gt;
 *     &lt;enumeration value="JI"/&gt;
 *     &lt;enumeration value="JL"/&gt;
 *     &lt;enumeration value="JM"/&gt;
 *     &lt;enumeration value="JN"/&gt;
 *     &lt;enumeration value="JO"/&gt;
 *     &lt;enumeration value="JR"/&gt;
 *     &lt;enumeration value="JU"/&gt;
 *     &lt;enumeration value="KB"/&gt;
 *     &lt;enumeration value="KC"/&gt;
 *     &lt;enumeration value="KE"/&gt;
 *     &lt;enumeration value="KH"/&gt;
 *     &lt;enumeration value="KI"/&gt;
 *     &lt;enumeration value="KK"/&gt;
 *     &lt;enumeration value="KN"/&gt;
 *     &lt;enumeration value="KO"/&gt;
 *     &lt;enumeration value="KP"/&gt;
 *     &lt;enumeration value="KS"/&gt;
 *     &lt;enumeration value="KT"/&gt;
 *     &lt;enumeration value="KU"/&gt;
 *     &lt;enumeration value="KW"/&gt;
 *     &lt;enumeration value="KY"/&gt;
 *     &lt;enumeration value="KZ"/&gt;
 *     &lt;enumeration value="LA"/&gt;
 *     &lt;enumeration value="LB"/&gt;
 *     &lt;enumeration value="LC"/&gt;
 *     &lt;enumeration value="LD"/&gt;
 *     &lt;enumeration value="LE"/&gt;
 *     &lt;enumeration value="LF"/&gt;
 *     &lt;enumeration value="LH"/&gt;
 *     &lt;enumeration value="LI"/&gt;
 *     &lt;enumeration value="LL"/&gt;
 *     &lt;enumeration value="LN"/&gt;
 *     &lt;enumeration value="LO"/&gt;
 *     &lt;enumeration value="LP"/&gt;
 *     &lt;enumeration value="LS"/&gt;
 *     &lt;enumeration value="LT"/&gt;
 *     &lt;enumeration value="LU"/&gt;
 *     &lt;enumeration value="LX"/&gt;
 *     &lt;enumeration value="LY"/&gt;
 *     &lt;enumeration value="MA"/&gt;
 *     &lt;enumeration value="MB"/&gt;
 *     &lt;enumeration value="MC"/&gt;
 *     &lt;enumeration value="MD"/&gt;
 *     &lt;enumeration value="ME"/&gt;
 *     &lt;enumeration value="MF"/&gt;
 *     &lt;enumeration value="MG"/&gt;
 *     &lt;enumeration value="MH"/&gt;
 *     &lt;enumeration value="MI"/&gt;
 *     &lt;enumeration value="MJ"/&gt;
 *     &lt;enumeration value="MK"/&gt;
 *     &lt;enumeration value="ML"/&gt;
 *     &lt;enumeration value="MM"/&gt;
 *     &lt;enumeration value="MN"/&gt;
 *     &lt;enumeration value="MO"/&gt;
 *     &lt;enumeration value="MP"/&gt;
 *     &lt;enumeration value="MQ"/&gt;
 *     &lt;enumeration value="MR"/&gt;
 *     &lt;enumeration value="MS"/&gt;
 *     &lt;enumeration value="MT"/&gt;
 *     &lt;enumeration value="MU"/&gt;
 *     &lt;enumeration value="MV"/&gt;
 *     &lt;enumeration value="MW"/&gt;
 *     &lt;enumeration value="MX"/&gt;
 *     &lt;enumeration value="MY"/&gt;
 *     &lt;enumeration value="MZ"/&gt;
 *     &lt;enumeration value="NA"/&gt;
 *     &lt;enumeration value="NB"/&gt;
 *     &lt;enumeration value="NC"/&gt;
 *     &lt;enumeration value="ND"/&gt;
 *     &lt;enumeration value="NE"/&gt;
 *     &lt;enumeration value="NF"/&gt;
 *     &lt;enumeration value="NG"/&gt;
 *     &lt;enumeration value="NH"/&gt;
 *     &lt;enumeration value="NI"/&gt;
 *     &lt;enumeration value="NJ"/&gt;
 *     &lt;enumeration value="NK"/&gt;
 *     &lt;enumeration value="NL"/&gt;
 *     &lt;enumeration value="NM"/&gt;
 *     &lt;enumeration value="NN"/&gt;
 *     &lt;enumeration value="NO"/&gt;
 *     &lt;enumeration value="NP"/&gt;
 *     &lt;enumeration value="NQ"/&gt;
 *     &lt;enumeration value="NR"/&gt;
 *     &lt;enumeration value="NS"/&gt;
 *     &lt;enumeration value="NT"/&gt;
 *     &lt;enumeration value="NU"/&gt;
 *     &lt;enumeration value="NV"/&gt;
 *     &lt;enumeration value="NW"/&gt;
 *     &lt;enumeration value="NX"/&gt;
 *     &lt;enumeration value="NY"/&gt;
 *     &lt;enumeration value="NZ"/&gt;
 *     &lt;enumeration value="OA"/&gt;
 *     &lt;enumeration value="OC"/&gt;
 *     &lt;enumeration value="OF"/&gt;
 *     &lt;enumeration value="OG"/&gt;
 *     &lt;enumeration value="OH"/&gt;
 *     &lt;enumeration value="OI"/&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="OM"/&gt;
 *     &lt;enumeration value="ON"/&gt;
 *     &lt;enumeration value="OO"/&gt;
 *     &lt;enumeration value="OR"/&gt;
 *     &lt;enumeration value="OS"/&gt;
 *     &lt;enumeration value="OT"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="PB"/&gt;
 *     &lt;enumeration value="PC"/&gt;
 *     &lt;enumeration value="PD"/&gt;
 *     &lt;enumeration value="PE"/&gt;
 *     &lt;enumeration value="PF"/&gt;
 *     &lt;enumeration value="PG"/&gt;
 *     &lt;enumeration value="PI"/&gt;
 *     &lt;enumeration value="PK"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="PM"/&gt;
 *     &lt;enumeration value="PN"/&gt;
 *     &lt;enumeration value="PO"/&gt;
 *     &lt;enumeration value="PQ"/&gt;
 *     &lt;enumeration value="PR"/&gt;
 *     &lt;enumeration value="PS"/&gt;
 *     &lt;enumeration value="PT"/&gt;
 *     &lt;enumeration value="PU"/&gt;
 *     &lt;enumeration value="PV"/&gt;
 *     &lt;enumeration value="PW"/&gt;
 *     &lt;enumeration value="QA"/&gt;
 *     &lt;enumeration value="QR"/&gt;
 *     &lt;enumeration value="QU"/&gt;
 *     &lt;enumeration value="RA"/&gt;
 *     &lt;enumeration value="RB"/&gt;
 *     &lt;enumeration value="RC"/&gt;
 *     &lt;enumeration value="RE"/&gt;
 *     &lt;enumeration value="RF"/&gt;
 *     &lt;enumeration value="RG"/&gt;
 *     &lt;enumeration value="RH"/&gt;
 *     &lt;enumeration value="RI"/&gt;
 *     &lt;enumeration value="RL"/&gt;
 *     &lt;enumeration value="RR"/&gt;
 *     &lt;enumeration value="RS"/&gt;
 *     &lt;enumeration value="RU"/&gt;
 *     &lt;enumeration value="RV"/&gt;
 *     &lt;enumeration value="RW"/&gt;
 *     &lt;enumeration value="RY"/&gt;
 *     &lt;enumeration value="SA"/&gt;
 *     &lt;enumeration value="SB"/&gt;
 *     &lt;enumeration value="SC"/&gt;
 *     &lt;enumeration value="SD"/&gt;
 *     &lt;enumeration value="SE"/&gt;
 *     &lt;enumeration value="SF"/&gt;
 *     &lt;enumeration value="SG"/&gt;
 *     &lt;enumeration value="SH"/&gt;
 *     &lt;enumeration value="SI"/&gt;
 *     &lt;enumeration value="SJ"/&gt;
 *     &lt;enumeration value="SK"/&gt;
 *     &lt;enumeration value="SL"/&gt;
 *     &lt;enumeration value="SM"/&gt;
 *     &lt;enumeration value="SN"/&gt;
 *     &lt;enumeration value="SO"/&gt;
 *     &lt;enumeration value="SP"/&gt;
 *     &lt;enumeration value="SQ"/&gt;
 *     &lt;enumeration value="SR"/&gt;
 *     &lt;enumeration value="SS"/&gt;
 *     &lt;enumeration value="SU"/&gt;
 *     &lt;enumeration value="SV"/&gt;
 *     &lt;enumeration value="SW"/&gt;
 *     &lt;enumeration value="SY"/&gt;
 *     &lt;enumeration value="SZ"/&gt;
 *     &lt;enumeration value="TA"/&gt;
 *     &lt;enumeration value="TB"/&gt;
 *     &lt;enumeration value="TC"/&gt;
 *     &lt;enumeration value="TD"/&gt;
 *     &lt;enumeration value="TE"/&gt;
 *     &lt;enumeration value="TF"/&gt;
 *     &lt;enumeration value="TG"/&gt;
 *     &lt;enumeration value="TH"/&gt;
 *     &lt;enumeration value="TJ"/&gt;
 *     &lt;enumeration value="TK"/&gt;
 *     &lt;enumeration value="TL"/&gt;
 *     &lt;enumeration value="TM"/&gt;
 *     &lt;enumeration value="TN"/&gt;
 *     &lt;enumeration value="TO"/&gt;
 *     &lt;enumeration value="TP"/&gt;
 *     &lt;enumeration value="TR"/&gt;
 *     &lt;enumeration value="TS"/&gt;
 *     &lt;enumeration value="TT"/&gt;
 *     &lt;enumeration value="TU"/&gt;
 *     &lt;enumeration value="TV"/&gt;
 *     &lt;enumeration value="TW"/&gt;
 *     &lt;enumeration value="TX"/&gt;
 *     &lt;enumeration value="TY"/&gt;
 *     &lt;enumeration value="TZ"/&gt;
 *     &lt;enumeration value="UC"/&gt;
 *     &lt;enumeration value="UG"/&gt;
 *     &lt;enumeration value="UK"/&gt;
 *     &lt;enumeration value="UM"/&gt;
 *     &lt;enumeration value="UR"/&gt;
 *     &lt;enumeration value="US"/&gt;
 *     &lt;enumeration value="UT"/&gt;
 *     &lt;enumeration value="UV"/&gt;
 *     &lt;enumeration value="UY"/&gt;
 *     &lt;enumeration value="UZ"/&gt;
 *     &lt;enumeration value="VA"/&gt;
 *     &lt;enumeration value="VB"/&gt;
 *     &lt;enumeration value="VC"/&gt;
 *     &lt;enumeration value="VI"/&gt;
 *     &lt;enumeration value="VL"/&gt;
 *     &lt;enumeration value="VT"/&gt;
 *     &lt;enumeration value="VV"/&gt;
 *     &lt;enumeration value="VY"/&gt;
 *     &lt;enumeration value="VZ"/&gt;
 *     &lt;enumeration value="WA"/&gt;
 *     &lt;enumeration value="WB"/&gt;
 *     &lt;enumeration value="WD"/&gt;
 *     &lt;enumeration value="WE"/&gt;
 *     &lt;enumeration value="WF"/&gt;
 *     &lt;enumeration value="WI"/&gt;
 *     &lt;enumeration value="WK"/&gt;
 *     &lt;enumeration value="WL"/&gt;
 *     &lt;enumeration value="WN"/&gt;
 *     &lt;enumeration value="WS"/&gt;
 *     &lt;enumeration value="WT"/&gt;
 *     &lt;enumeration value="WV"/&gt;
 *     &lt;enumeration value="WY"/&gt;
 *     &lt;enumeration value="XX"/&gt;
 *     &lt;enumeration value="YG"/&gt;
 *     &lt;enumeration value="YO"/&gt;
 *     &lt;enumeration value="YT"/&gt;
 *     &lt;enumeration value="YU"/&gt;
 *     &lt;enumeration value="YY"/&gt;
 *     &lt;enumeration value="ZA"/&gt;
 *     &lt;enumeration value="ZB"/&gt;
 *     &lt;enumeration value="ZC"/&gt;
 *     &lt;enumeration value="ZD"/&gt;
 *     &lt;enumeration value="ZI"/&gt;
 *     &lt;enumeration value="ZM"/&gt;
 *     &lt;enumeration value="ZO"/&gt;
 *     &lt;enumeration value="ZR"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CountryCodeType")
@XmlEnum
public enum CountryCodeType {


    /**
     * Albania
     * 
     */
    AA,

    /**
     * Alberta
     * 
     */
    AB,

    /**
     * Andorra
     * 
     */
    AD,

    /**
     * Anguilla
     * 
     */
    AE,

    /**
     * Afghanista
     * 
     */
    AF,

    /**
     * Aguascalientes
     * 
     */
    AG,

    /**
     * Ashmore and Cartier Islands
     * 
     */
    AH,

    /**
     * Antigua and Barbuda (formerly Antigua)
     * 
     */
    AI,

    /**
     * Aruba (now independent of Netherlands Antilles)
     * 
     */
    AJ,

    /**
     * Alaska
     * 
     */
    AK,

    /**
     * Alabama
     * 
     */
    AL,

    /**
     * American Samoa (Islands)
     * 
     */
    AM,

    /**
     * Algeria
     * 
     */
    AN,

    /**
     * Angola
     * 
     */
    AO,

    /**
     * Armenia
     * 
     */
    AP,

    /**
     * Azores Islands
     * 
     */
    AQ,

    /**
     * Arkansas
     * 
     */
    AR,

    /**
     * Australia
     * 
     */
    AS,

    /**
     * Argentina
     * 
     */
    AT,

    /**
     * Austria
     * 
     */
    AU,

    /**
     * Azerbaijan
     * 
     */
    AV,

    /**
     * APACHE TRIBE
     * 
     */
    AX,

    /**
     * Arizona
     * 
     */
    AZ,

    /**
     * Baja California (Northern Section)
     * 
     */
    BA,

    /**
     * Barbados
     * 
     */
    BB,

    /**
     * British Columbia
     * 
     */
    BC,

    /**
     * Bahamas, The
     * 
     */
    BD,

    /**
     * Bahrain/Bahrein
     * 
     */
    BE,

    /**
     * Bassas Da India (French possession)
     * 
     */
    BF,

    /**
     * Belgium
     * 
     */
    BG,

    /**
     * Belize (formerly British Honduras)
     * 
     */
    BH,

    /**
     * Burundi
     * 
     */
    BI,

    /**
     * Baja California (Southern Section)
     * 
     */
    BJ,

    /**
     * Baker Island
     * 
     */
    BK,

    /**
     * Bangladesh
     * 
     */
    BL,

    /**
     * Bermuda
     * 
     */
    BM,

    /**
     * Bhutan
     * 
     */
    BN,

    /**
     * British Indian Ocean Territory
     * 
     */
    BO,

    /**
     * Bosnia and Hercegovenia
     * 
     */
    BP,

    /**
     * Bouvet Island (Norwegian territory)
     * 
     */
    BQ,

    /**
     * Burma
     * 
     */
    BR,

    /**
     * British Solomon Islands (now Solomon Islands)
     * 
     */
    BS,

    /**
     * Botswana
     * 
     */
    BT,

    /**
     * Bulgaria
     * 
     */
    BU,

    /**
     * Bolivia
     * 
     */
    BV,

    /**
     * Balearic Islands
     * 
     */
    BW,

    /**
     * Brunei
     * 
     */
    BX,

    /**
     * Byelarus
     * 
     */
    BY,

    /**
     * Brazil
     * 
     */
    BZ,

    /**
     * California
     * 
     */
    CA,

    /**
     * Colombia
     * 
     */
    CB,

    /**
     * Cuba
     * 
     */
    CC,

    /**
     * Canada(See separate list of Canadian Provinces; use code CD only when province is unknown.)
     * 
     */
    CD,

    /**
     * Campeche
     * 
     */
    CE,

    /**
     * Chad
     * 
     */
    CF,

    /**
     * Caroline Islands
     * 
     */
    CG,

    /**
     * Chihuahua
     * 
     */
    CH,

    /**
     * Chiapas
     * 
     */
    CI,

    /**
     * Cambodia (formerly Khmer Republic and Kampuchea)
     * 
     */
    CJ,

    /**
     * Colima
     * 
     */
    CL,

    /**
     * Cameroon
     * 
     */
    CM,

    /**
     * Colorado
     * 
     */
    CO,

    /**
     * Cayman Islands
     * 
     */
    CP,

    /**
     * Chile
     * 
     */
    CQ,

    /**
     * Costa Rica
     * 
     */
    CR,

    /**
     * Cyprus
     * 
     */
    CS,

    /**
     * Connecticut
     * 
     */
    CT,

    /**
     * Coahuila
     * 
     */
    CU,

    /**
     * Cape Verde Islands
     * 
     */
    CV,

    /**
     * Central African Republic
     * 
     */
    CW,

    /**
     * Ceylon (Now Sri Lanka)
     * 
     */
    CY,

    /**
     * Canal Zone
     * 
     */
    CZ,

    /**
     * CHEYENNE and ARAPAHO TRIBES
     * 
     */
    DA,

    /**
     * Clipperton Island (French possession)
     * 
     */
    DB,

    /**
     * District of Columbia
     * 
     */
    DC,

    /**
     * Cocos (Keeling) Islands (Australian dependency)
     * 
     */
    DD,

    /**
     * Delaware
     * 
     */
    DE,

    /**
     * Distrito Federal (Mexico, D. F.)
     * 
     */
    DF,

    /**
     * Comoros (or Comoros Islands)
     * 
     */
    DG,

    /**
     * Benin (formerly Dahomey)
     * 
     */
    DH,

    /**
     * Cook Islands
     * 
     */
    DI,

    /**
     * Coral Sea Islands (Australian territory)
     * 
     */
    DJ,

    /**
     * Denmark
     * 
     */
    DK,

    /**
     * Devil's Lake Sioux Tribe
     * 
     */
    DL,

    /**
     * Dominica
     * 
     */
    DM,

    /**
     * Djibouti
     * 
     */
    DN,

    /**
     * Durango
     * 
     */
    DO,

    /**
     * COMANCHE NATION
     * 
     */
    DP,

    /**
     * Dominican Republic
     * 
     */
    DR,

    /**
     * MIAMI TRIBE
     * 
     */
    DS,

    /**
     * MUSCOGEE (CREEK) TRIBE
     * 
     */
    DT,

    /**
     * SENECA-CAYUGA TRIBES
     * 
     */
    DV,

    /**
     * CITIZEN BAND POTTAWATOMIE TRIBE
     * 
     */
    DW,

    /**
     * Absentee Shawnee
     * 
     */
    EE,

    /**
     * Equatorial Guinea
     * 
     */
    EK,

    /**
     * El Salvador
     * 
     */
    EL,

    /**
     * England
     * 
     */
    EN,

    /**
     * Ethiopia
     * 
     */
    EO,

    /**
     * Europa Island (French possession)
     * 
     */
    ER,

    /**
     * Estonia
     * 
     */
    ES,

    /**
     * Eritrea
     * 
     */
    ET,

    /**
     * Ecuador
     * 
     */
    EU,

    /**
     * Egypt (formerly United Arab Republic)
     * 
     */
    EY,

    /**
     * Czech Republic
     * 
     */
    EZ,

    /**
     * Falkland Islands
     * 
     */
    FA,

    /**
     * Fond du Lac
     * 
     */
    FC,

    /**
     * Finland
     * 
     */
    FD,

    /**
     * French Guiana
     * 
     */
    FG,

    /**
     * Fiji
     * 
     */
    FJ,

    /**
     * Florida
     * 
     */
    FL,

    /**
     * France
     * 
     */
    FN,

    /**
     * Faroe Islands
     * 
     */
    FO,

    /**
     * French Polynesia
     * 
     */
    FP,

    /**
     * French Southern and Antartic Lands
     * 
     */
    FR,

    /**
     * Federated States of Micronesia
     * 
     */
    FS,

    /**
     * Sac and Fox
     * 
     */
    FX,

    /**
     * Georgia
     * 
     */
    GA,

    /**
     * Gabon
     * 
     */
    GB,

    /**
     * Greece
     * 
     */
    GC,

    /**
     * Georgia
     * 
     */
    GD,

    /**
     * Germany (East Germany: 1945-1989, for reference only)(West Germany: 1945-1989, for reference only)
     * 
     */
    GE,

    /**
     * Guernsey
     * 
     */
    GF,

    /**
     * Ghana
     * 
     */
    GG,

    /**
     * Guinea
     * 
     */
    GI,

    /**
     * Grenada
     * 
     */
    GJ,

    /**
     * Gambia, The
     * 
     */
    GK,

    /**
     * Guam
     * 
     */
    GM,

    /**
     * Greenland
     * 
     */
    GN,

    /**
     * Glorioso Islands (French possession)
     * 
     */
    GO,

    /**
     * Guadeloupe
     * 
     */
    GP,

    /**
     * Guerrero
     * 
     */
    GR,

    /**
     * South Georgia and the South Sandwich Islands
     * 
     */
    GS,

    /**
     * Guatemala
     * 
     */
    GT,

    /**
     * Guanajuato
     * 
     */
    GU,

    /**
     * Guyana
     * 
     */
    GY,

    /**
     * Gaza
     * 
     */
    GZ,

    /**
     * Honduras
     * 
     */
    HD,

    /**
     * Heard Island and McDonald Island
     * 
     */
    HE,

    /**
     * Hawaii
     * 
     */
    HI,

    /**
     * Hong Kong
     * 
     */
    HK,

    /**
     * Hidalgo
     * 
     */
    HL,

    /**
     * New Hebrides (now Vanuatu)
     * 
     */
    HN,

    /**
     * Howland Island
     * 
     */
    HO,

    /**
     * Christmas Island
     * 
     */
    HR,

    /**
     * Saint Helena
     * 
     */
    HS,

    /**
     * Haiti
     * 
     */
    HT,

    /**
     * Hungary
     * 
     */
    HU,

    /**
     * Iowa
     * 
     */
    IA,

    /**
     * Isle of Man
     * 
     */
    IB,

    /**
     * Iceland
     * 
     */
    IC,

    /**
     * Idaho
     * 
     */
    ID,

    /**
     * Ireland (does not include Northern Ireland, see Northern Ireland)
     * 
     */
    IE,

    /**
     * India
     * 
     */
    II,

    /**
     * Illinois
     * 
     */
    IL,

    /**
     * Madeira Islands
     * 
     */
    IM,

    /**
     * Indiana
     * 
     */
    IN,

    /**
     * Indonesia (now includes Portuguese Timor)
     * 
     */
    IO,

    /**
     * Iraq
     * 
     */
    IQ,

    /**
     * Iran
     * 
     */
    IR,

    /**
     * Israel
     * 
     */
    IS,

    /**
     * Italy (includes Sicily and Sardinia)
     * 
     */
    IT,

    /**
     * Niue
     * 
     */
    IU,

    /**
     * IOWA TRIBE
     * 
     */
    IW,

    /**
     * Menominee
     * 
     */
    IX,

    /**
     * Cote d'Ivoire (Ivory Coast)
     * 
     */
    IY,

    /**
     * Japan
     * 
     */
    JA,

    /**
     * Jersey
     * 
     */
    JE,

    /**
     * Johnston Island
     * 
     */
    JI,

    /**
     * Jalisco
     * 
     */
    JL,

    /**
     * Jamaica
     * 
     */
    JM,

    /**
     * Jan Mayen
     * 
     */
    JN,

    /**
     * Jordan
     * 
     */
    JO,

    /**
     * Jarvis Island
     * 
     */
    JR,

    /**
     * Juan de Nova Island
     * 
     */
    JU,

    /**
     * Gilbert Islands (now Kiribati)
     * 
     */
    KB,

    /**
     * Croatia
     * 
     */
    KC,

    /**
     * Kenya
     * 
     */
    KE,

    /**
     * Manahiki Island
     * 
     */
    KH,

    /**
     * Kingman Reef
     * 
     */
    KI,

    /**
     * KICKAPOO TRIBE
     * 
     */
    KK,

    /**
     * North Korea
     * 
     */
    KN,

    /**
     * South Korea
     * 
     */
    KO,

    /**
     * Shakopee
     * 
     */
    KP,

    /**
     * Kansas
     * 
     */
    KS,

    /**
     * Kazakhstan
     * 
     */
    KT,

    /**
     * Kuwait
     * 
     */
    KU,

    /**
     * Kiowa
     * 
     */
    KW,

    /**
     * Kentucky
     * 
     */
    KY,

    /**
     * Kyrgyzstan
     * 
     */
    KZ,

    /**
     * Louisiana
     * 
     */
    LA,

    /**
     * Liberia
     * 
     */
    LB,

    /**
     * Mille Lacs
     * 
     */
    LC,

    /**
     * Moldova
     * 
     */
    LD,

    /**
     * Lesotho
     * 
     */
    LE,

    /**
     * Slovakia
     * 
     */
    LF,

    /**
     * Lithuania
     * 
     */
    LH,

    /**
     * Liechtenstein
     * 
     */
    LI,

    /**
     * Leech Lake Band of Chippewa
     * 
     */
    LL,

    /**
     * Lebanon
     * 
     */
    LN,

    /**
     * Slovenia
     * 
     */
    LO,

    /**
     * Lac du Flambeau Band of Lake Superior Chippewa
     * 
     */
    LP,

    /**
     * Laos
     * 
     */
    LS,

    /**
     * LATVIA
     * 
     */
    LT,

    /**
     * Saint Lucia
     * 
     */
    LU,

    /**
     * Luxembourg
     * 
     */
    LX,

    /**
     * Libya
     * 
     */
    LY,

    /**
     * Massachusetts
     * 
     */
    MA,

    /**
     * Manitoba
     * 
     */
    MB,

    /**
     * Michoacan
     * 
     */
    MC,

    /**
     * Maryland
     * 
     */
    MD,

    /**
     * Maine
     * 
     */
    ME,

    /**
     * Malawi
     * 
     */
    MF,

    /**
     * Mongolia
     * 
     */
    MG,

    /**
     * Marshall Islands
     * 
     */
    MH,

    /**
     * Michigan
     * 
     */
    MI,

    /**
     * Monaco
     * 
     */
    MJ,

    /**
     * Mariana Islands
     * 
     */
    MK,

    /**
     * Mali
     * 
     */
    ML,

    /**
     * Mexico (See separate list of Mexican States; use code MM only when state is unknown)
     * 
     */
    MM,

    /**
     * Minnesota
     * 
     */
    MN,

    /**
     * Missouri
     * 
     */
    MO,

    /**
     * Madagascar (included in Malagasy Republic)
     * 
     */
    MP,

    /**
     * Morocco
     * 
     */
    MQ,

    /**
     * Morelos
     * 
     */
    MR,

    /**
     * Mississippi
     * 
     */
    MS,

    /**
     * Montana
     * 
     */
    MT,

    /**
     * Mauritania
     * 
     */
    MU,

    /**
     * Maldives
     * 
     */
    MV,

    /**
     * Midway Islands
     * 
     */
    MW,

    /**
     * Mexico (State)
     * 
     */
    MX,

    /**
     * Malta
     * 
     */
    MY,

    /**
     * Malaysia
     * 
     */
    MZ,

    /**
     * Nayarit
     * 
     */
    NA,

    /**
     * Nebraska
     * 
     */
    NB,

    /**
     * North Carolina
     * 
     */
    NC,

    /**
     * North Dakota
     * 
     */
    ND,

    /**
     * Holland (Netherlands)
     * 
     */
    NE,

    /**
     * Newfoundland (includes Labrador)
     * 
     */
    NF,

    /**
     * Nigeria
     * 
     */
    NG,

    /**
     * New Hampshire
     * 
     */
    NH,

    /**
     * Northern Ireland
     * 
     */
    NI,

    /**
     * New Jersey
     * 
     */
    NJ,

    /**
     * New Brunswick
     * 
     */
    NK,

    /**
     * Nuevo Leon
     * 
     */
    NL,

    /**
     * New Mexico
     * 
     */
    NM,

    /**
     * Niger
     * 
     */
    NN,

    /**
     * New Guinea (now Papua New Guinea)
     * 
     */
    NO,

    /**
     * Nepal
     * 
     */
    NP,

    /**
     * New Caledonia
     * 
     */
    NQ,

    /**
     * Nauru
     * 
     */
    NR,

    /**
     * Nova Scotia
     * 
     */
    NS,

    /**
     * Northwest Territories
     * 
     */
    NT,

    /**
     * Nicaragua
     * 
     */
    NU,

    /**
     * Nevada
     * 
     */
    NV,

    /**
     * Norway
     * 
     */
    NW,

    /**
     * Bonaire (Netherlands Antilles)
     * 
     */
    NX,

    /**
     * New York
     * 
     */
    NY,

    /**
     * New Zealand
     * 
     */
    NZ,

    /**
     * Oaxaca
     * 
     */
    OA,

    /**
     * Macao (now spelled Macau)
     * 
     */
    OC,

    /**
     * Norfolk Island
     * 
     */
    OF,

    /**
     * OSAGE NATION
     * 
     */
    OG,

    /**
     * Ohio
     * 
     */
    OH,

    /**
     * Okinawa
     * 
     */
    OI,

    /**
     * Oklahoma
     * 
     */
    OK,

    /**
     * Oman
     * 
     */
    OM,

    /**
     * Ontario
     * 
     */
    ON,

    /**
     * OTOE-MISSOURIA TRIBE
     * 
     */
    OO,

    /**
     * Oregon
     * 
     */
    OR,

    /**
     * Oglala Sioux
     * 
     */
    OS,

    /**
     * Oneida Tribe of Indians of Wisconsin
     * 
     */
    OT,

    /**
     * Pennsylvania
     * 
     */
    PA,

    /**
     * Puebla
     * 
     */
    PB,

    /**
     * Pitcairn,Henderson, Ducie, and OenoIslands
     * 
     */
    PC,

    /**
     * Palau, Republic of
     * 
     */
    PD,

    /**
     * Prince Edward Island
     * 
     */
    PE,

    /**
     * Parcel Islands
     * 
     */
    PF,

    /**
     * Guinea-Bissau (formerly Portuguese Guinea)
     * 
     */
    PG,

    /**
     * Philippines
     * 
     */
    PI,

    /**
     * Pakistan
     * 
     */
    PK,

    /**
     * Palmyra Atoll
     * 
     */
    PL,

    /**
     * Panama
     * 
     */
    PM,

    /**
     * PONCA TRIBE
     * 
     */
    PN,

    /**
     * Poland
     * 
     */
    PO,

    /**
     * Quebec
     * 
     */
    PQ,

    /**
     * Puerto Rico
     * 
     */
    PR,

    /**
     * Saint Pierre and Miquelon
     * 
     */
    PS,

    /**
     * Portugal
     * 
     */
    PT,

    /**
     * Peru
     * 
     */
    PU,

    /**
     * Paraquay
     * 
     */
    PV,

    /**
     * PAWNEE TRIBE
     * 
     */
    PW,

    /**
     * Qatar
     * 
     */
    QA,

    /**
     * Quintana Roo
     * 
     */
    QR,

    /**
     * Queretaro
     * 
     */
    QU,

    /**
     * Russia
     * 
     */
    RA,

    /**
     * Republic of Congo, Brazzaville
     * 
     */
    RB,

    /**
     * People's Republic of China
     * 
     */
    RC,

    /**
     * Reunion
     * 
     */
    RE,

    /**
     * Russian Federation
     * 
     */
    RF,

    /**
     * Gibraltar
     * 
     */
    RG,

    /**
     * Rhodesia (now Zimbabwe)
     * 
     */
    RH,

    /**
     * Rhode Island
     * 
     */
    RI,

    /**
     * Red Lake
     * 
     */
    RL,

    /**
     * Montserrat
     * 
     */
    RR,

    /**
     * Spanish Sahara (now Western Sahara)
     * 
     */
    RS,

    /**
     * Romania/Rumania
     * 
     */
    RU,

    /**
     * Socialist Republic of Vietnam
     * 
     */
    RV,

    /**
     * Rwanda
     * 
     */
    RW,

    /**
     * Republic of Yemen
     * 
     */
    RY,

    /**
     * Sierre Leone (Sierra Leone)
     * 
     */
    SA,

    /**
     * Saudi Arabia
     * 
     */
    SB,

    /**
     * South Carolina
     * 
     */
    SC,

    /**
     * South Dakota
     * 
     */
    SD,

    /**
     * Seychelles
     * 
     */
    SE,

    /**
     * South Africa
     * 
     */
    SF,

    /**
     * Senegal
     * 
     */
    SG,

    /**
     * San Marino
     * 
     */
    SH,

    /**
     * Sinaloa
     * 
     */
    SI,

    /**
     * Namibia (South-West Africa)
     * 
     */
    SJ,

    /**
     * SEMINOLE NATION
     * 
     */
    SK,

    /**
     * San Luis Potosi
     * 
     */
    SL,

    /**
     * Somalia
     * 
     */
    SM,

    /**
     * Saskatchewan
     * 
     */
    SN,

    /**
     * Sonora
     * 
     */
    SO,

    /**
     * Spain
     * 
     */
    SP,

    /**
     * Sweden
     * 
     */
    SQ,

    /**
     * Singapore
     * 
     */
    SR,

    /**
     * Scotland
     * 
     */
    SS,

    /**
     * Sudan
     * 
     */
    SU,

    /**
     * Svalbard
     * 
     */
    SV,

    /**
     * Swaziland
     * 
     */
    SW,

    /**
     * Syria
     * 
     */
    SY,

    /**
     * Switzerland
     * 
     */
    SZ,

    /**
     * Tamaulipas
     * 
     */
    TA,

    /**
     * Tabasco
     * 
     */
    TB,

    /**
     * Trucial States (now United Arab Emirates)
     * 
     */
    TC,

    /**
     * Trust Territory of the Pacific Islands
     * 
     */
    TD,

    /**
     * Spratly Islands
     * 
     */
    TE,

    /**
     * Tuamotu Archipelago
     * 
     */
    TF,

    /**
     * Tonga
     * 
     */
    TG,

    /**
     * Thailand
     * 
     */
    TH,

    /**
     * Tajikistan
     * 
     */
    TJ,

    /**
     * Tokelau
     * 
     */
    TK,

    /**
     * Tlaxcala
     * 
     */
    TL,

    /**
     * Tromelin Island (French possession)
     * 
     */
    TM,

    /**
     * Tennessee
     * 
     */
    TN,

    /**
     * Togo
     * 
     */
    TO,

    /**
     * Sao Tome and Principe
     * 
     */
    TP,

    /**
     * Turks and Calcos Islands
     * 
     */
    TR,

    /**
     * Nevis and Saint Christopher "Kitts"
     * 
     */
    TS,

    /**
     * Trinidad and Tobago
     * 
     */
    TT,

    /**
     * Tunisia
     * 
     */
    TU,

    /**
     * Ellice Islands (now Tuvalu)
     * 
     */
    TV,

    /**
     * Taiwan, Republic of China
     * 
     */
    TW,

    /**
     * Texas
     * 
     */
    TX,

    /**
     * Turkey
     * 
     */
    TY,

    /**
     * Tanzania, United Republic of
     * 
     */
    TZ,

    /**
     * Turtle Mtn. Band of Chipewa
     * 
     */
    UC,

    /**
     * Uganda
     * 
     */
    UG,

    /**
     * Ukraine
     * 
     */
    UK,

    /**
     * Mauritius
     * 
     */
    UM,

    /**
     * Turkmenistan
     * 
     */
    UR,

    /**
     * United States of America (USA) (Should be used in the following circumstances: 1. To indicate the LIS
     * 
     */
    US,

    /**
     * Utah
     * 
     */
    UT,

    /**
     * Burkina Faso (known as Burkina, formerly Upper Volta)
     * 
     */
    UV,

    /**
     * Uruguay
     * 
     */
    UY,

    /**
     * Uzbekistan
     * 
     */
    UZ,

    /**
     * Virginia
     * 
     */
    VA,

    /**
     * British Virgin Islands
     * 
     */
    VB,

    /**
     * Veracruz
     * 
     */
    VC,

    /**
     * U.S. Virgin Islands
     * 
     */
    VI,

    /**
     * Navassa Island
     * 
     */
    VL,

    /**
     * Vermont
     * 
     */
    VT,

    /**
     * Saint Vincent and the Grenadines
     * 
     */
    VV,

    /**
     * Vatican City
     * 
     */
    VY,

    /**
     * Venezuela
     * 
     */
    VZ,

    /**
     * Washington
     * 
     */
    WA,

    /**
     * West Bank
     * 
     */
    WB,

    /**
     * WYANDOTTE TRIBE
     * 
     */
    WD,

    /**
     * White Earth
     * 
     */
    WE,

    /**
     * Wallis and Futuna (French territory)
     * 
     */
    WF,

    /**
     * Wisconsin
     * 
     */
    WI,

    /**
     * Wake Island
     * 
     */
    WK,

    /**
     * Wales
     * 
     */
    WL,

    /**
     * West Indies (for West Indies Islands not found separately listed)
     * 
     */
    WN,

    /**
     * Western Samoa
     * 
     */
    WS,

    /**
     * WICHITA TRIBE
     * 
     */
    WT,

    /**
     * West Virginia
     * 
     */
    WV,

    /**
     * Wyoming
     * 
     */
    WY,

    /**
     * Unknown Place of Birth (for use in IIIrecords only)
     * 
     */
    XX,

    /**
     * Yugoslavia
     * 
     */
    YG,

    /**
     * Mayotte
     * 
     */
    YO,

    /**
     * Yukon (Territory)
     * 
     */
    YT,

    /**
     * Yucatan
     * 
     */
    YU,

    /**
     * All others (Any foreign country/dependency/territory not included in the above abbreviation lists
     * 
     */
    YY,

    /**
     * Zacatecas
     * 
     */
    ZA,

    /**
     * Martinique
     * 
     */
    ZB,

    /**
     * Surinam
     * 
     */
    ZC,

    /**
     * Macedonia
     * 
     */
    ZD,

    /**
     * Canary Islands
     * 
     */
    ZI,

    /**
     * Zambia
     * 
     */
    ZM,

    /**
     * Mozambique
     * 
     */
    ZO,

    /**
     * Congo Kinshasa, now Zaire
     * 
     */
    ZR;

    public String value() {
        return name();
    }

    public static CountryCodeType fromValue(String v) {
        return valueOf(v);
    }

}
