//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CredentialCategoryType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CredentialCategoryType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="30"/&gt;
 *     &lt;enumeration value="Federal Employee"/&gt;
 *     &lt;enumeration value="Federal Contractor"/&gt;
 *     &lt;enumeration value="Organizational Affiliate"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CredentialCategoryType")
@XmlEnum
public enum CredentialCategoryType {

    @XmlEnumValue("Federal Employee")
    FEDERAL_EMPLOYEE("Federal Employee"),
    @XmlEnumValue("Federal Contractor")
    FEDERAL_CONTRACTOR("Federal Contractor"),
    @XmlEnumValue("Organizational Affiliate")
    ORGANIZATIONAL_AFFILIATE("Organizational Affiliate");
    private final String value;

    CredentialCategoryType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CredentialCategoryType fromValue(String v) {
        for (CredentialCategoryType c: CredentialCategoryType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
