//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EnrollmentTypeCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EnrollmentTypeCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="PIV-AutoProduceCard"/&gt;
 *     &lt;enumeration value="PIV"/&gt;
 *     &lt;enumeration value="BkinvestigateOnly"/&gt;
 *     &lt;enumeration value="NonPIV-AutoProduceCard"/&gt;
 *     &lt;enumeration value="NonPIV"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EnrollmentTypeCodeType")
@XmlEnum
public enum EnrollmentTypeCodeType {


    /**
     * 
     * 						PIV enrollment with automatic card production
     * 		        	
     * 
     */
    @XmlEnumValue("PIV-AutoProduceCard")
    PIV_AUTO_PRODUCE_CARD("PIV-AutoProduceCard"),

    /**
     * 
     * 						PIV enrollment with no automatic card production.  The
     * 						PIV card will be produced only when requested.
     * 		        	
     * 
     */
    PIV("PIV"),

    /**
     * 
     * 						Non PIV enrollment, Background investigation only.
     * 						No card can be produced with this type of enrollment.
     * 		        	
     * 
     */
    @XmlEnumValue("BkinvestigateOnly")
    BKINVESTIGATE_ONLY("BkinvestigateOnly"),

    /**
     * 
     * 						Non PIV enrollment with automatic card production
     * 		        	
     * 
     */
    @XmlEnumValue("NonPIV-AutoProduceCard")
    NON_PIV_AUTO_PRODUCE_CARD("NonPIV-AutoProduceCard"),

    /**
     * 
     * 						Non PIV enrollment with no automatic card production.  The
     * 						card will be produced only when requested.
     * 		        	
     * 
     */
    @XmlEnumValue("NonPIV")
    NON_PIV("NonPIV");
    private final String value;

    EnrollmentTypeCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EnrollmentTypeCodeType fromValue(String v) {
        for (EnrollmentTypeCodeType c: EnrollmentTypeCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
