//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionHeader" type="{http://hspd12.hhs.gov/scms/idProofing/v1}TransactionHeaderType"/&gt;
 *         &lt;element name="SearchPersonId" type="{http://hspd12.hhs.gov/scms/idProofing/v1}HHSIdType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionHeader",
    "searchPersonId"
})
@XmlRootElement(name = "GetPersonDataRequest", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1")
public class GetPersonDataRequest {

    @XmlElement(name = "TransactionHeader", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", required = true)
    protected TransactionHeaderType2 transactionHeader;
    @XmlElement(name = "SearchPersonId", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", required = true)
    protected String searchPersonId;

    /**
     * Gets the value of the transactionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHeaderType2 }
     *     
     */
    public TransactionHeaderType2 getTransactionHeader() {
        return transactionHeader;
    }

    /**
     * Sets the value of the transactionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHeaderType2 }
     *     
     */
    public void setTransactionHeader(TransactionHeaderType2 value) {
        this.transactionHeader = value;
    }

    /**
     * Gets the value of the searchPersonId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSearchPersonId() {
        return searchPersonId;
    }

    /**
     * Sets the value of the searchPersonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSearchPersonId(String value) {
        this.searchPersonId = value;
    }

}
