//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         		This Type defines the required data items which may be 
 *         		included in a Induct Person request.
 *         	
 * 
 * <p>Java class for HHSInductPersonRequiredDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="HHSInductPersonRequiredDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonSponsored" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EmployeeID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivEmployeeIDType" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}FirstNameType"/&gt;
 *         &lt;element name="LastName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}LastNameType"/&gt;
 *         &lt;element name="PersonID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdType" minOccurs="0"/&gt;
 *         &lt;element name="IdentificationInfo" type="{http://hspd12.hhs.gov/federated/enrollment/v1}IdentificationInformationType"/&gt;
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}date"/&gt;
 *         &lt;element name="CountryOfCitizenship" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="PositionSensitivity" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PositionSensitivityType" minOccurs="0"/&gt;
 *         &lt;element name="EmergencyResponder" type="{http://hspd12.hhs.gov/federated/enrollment/v1}YesNoCodeType"/&gt;
 *         &lt;element name="Organization" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OrganizationCodeType"/&gt;
 *         &lt;element name="OPDIV" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType"/&gt;
 *         &lt;element name="AffiliationCode" type="{http://hspd12.hhs.gov/federated/enrollment/v1}AffiliationCodeType"/&gt;
 *         &lt;element name="CAN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CANType" minOccurs="0"/&gt;
 *         &lt;element name="PrimarySmtpEmailAddress" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EmailAddressType" minOccurs="0"/&gt;
 *         &lt;element name="UPN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}UPNType" minOccurs="0"/&gt;
 *         &lt;element name="IssuingAuthority" type="{http://hspd12.hhs.gov/federated/enrollment/v1}IssuingAuthorityCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CredentialCategory" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CredentialCategoryType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HHSInductPersonRequiredDataType", propOrder = {
    "personSponsored",
    "employeeID",
    "firstName",
    "lastName",
    "personID",
    "identificationInfo",
    "dob",
    "countryOfCitizenship",
    "positionSensitivity",
    "emergencyResponder",
    "organization",
    "opdiv",
    "affiliationCode",
    "can",
    "primarySmtpEmailAddress",
    "upn",
    "issuingAuthority",
    "credentialCategory"
})
public class HHSInductPersonRequiredDataType {

    @XmlElement(name = "PersonSponsored")
    protected boolean personSponsored;
    @XmlElement(name = "EmployeeID")
    protected String employeeID;
    @XmlElement(name = "FirstName", required = true)
    protected String firstName;
    @XmlElement(name = "LastName", required = true)
    protected String lastName;
    @XmlElement(name = "PersonID")
    protected String personID;
    @XmlElement(name = "IdentificationInfo", required = true)
    protected IdentificationInformationType identificationInfo;
    @XmlElement(name = "DOB", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dob;
    @XmlElement(name = "CountryOfCitizenship")
    @XmlSchemaType(name = "string")
    protected CountryCodeType countryOfCitizenship;
    @XmlElement(name = "PositionSensitivity", defaultValue = "1")
    protected Integer positionSensitivity;
    @XmlElement(name = "EmergencyResponder", required = true)
    @XmlSchemaType(name = "string")
    protected YesNoCodeType emergencyResponder;
    @XmlElement(name = "Organization", required = true)
    @XmlSchemaType(name = "string")
    protected OrganizationCodeType organization;
    @XmlElement(name = "OPDIV", required = true)
    @XmlSchemaType(name = "string")
    protected OpdivCodeType opdiv;
    @XmlElement(name = "AffiliationCode", required = true)
    @XmlSchemaType(name = "string")
    protected AffiliationCodeType affiliationCode;
    @XmlElement(name = "CAN")
    protected String can;
    @XmlElement(name = "PrimarySmtpEmailAddress")
    protected String primarySmtpEmailAddress;
    @XmlElement(name = "UPN")
    protected String upn;
    @XmlElement(name = "IssuingAuthority")
    @XmlSchemaType(name = "string")
    protected IssuingAuthorityCodeType issuingAuthority;
    @XmlElement(name = "CredentialCategory", required = true)
    @XmlSchemaType(name = "string")
    protected CredentialCategoryType credentialCategory;

    /**
     * Gets the value of the personSponsored property.
     * 
     */
    public boolean isPersonSponsored() {
        return personSponsored;
    }

    /**
     * Sets the value of the personSponsored property.
     * 
     */
    public void setPersonSponsored(boolean value) {
        this.personSponsored = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the personID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonID() {
        return personID;
    }

    /**
     * Sets the value of the personID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonID(String value) {
        this.personID = value;
    }

    /**
     * Gets the value of the identificationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link IdentificationInformationType }
     *     
     */
    public IdentificationInformationType getIdentificationInfo() {
        return identificationInfo;
    }

    /**
     * Sets the value of the identificationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdentificationInformationType }
     *     
     */
    public void setIdentificationInfo(IdentificationInformationType value) {
        this.identificationInfo = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDOB(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the countryOfCitizenship property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getCountryOfCitizenship() {
        return countryOfCitizenship;
    }

    /**
     * Sets the value of the countryOfCitizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setCountryOfCitizenship(CountryCodeType value) {
        this.countryOfCitizenship = value;
    }

    /**
     * Gets the value of the positionSensitivity property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getPositionSensitivity() {
        return positionSensitivity;
    }

    /**
     * Sets the value of the positionSensitivity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setPositionSensitivity(Integer value) {
        this.positionSensitivity = value;
    }

    /**
     * Gets the value of the emergencyResponder property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoCodeType }
     *     
     */
    public YesNoCodeType getEmergencyResponder() {
        return emergencyResponder;
    }

    /**
     * Sets the value of the emergencyResponder property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoCodeType }
     *     
     */
    public void setEmergencyResponder(YesNoCodeType value) {
        this.emergencyResponder = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationCodeType }
     *     
     */
    public OrganizationCodeType getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationCodeType }
     *     
     */
    public void setOrganization(OrganizationCodeType value) {
        this.organization = value;
    }

    /**
     * Gets the value of the opdiv property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivCodeType }
     *     
     */
    public OpdivCodeType getOPDIV() {
        return opdiv;
    }

    /**
     * Sets the value of the opdiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivCodeType }
     *     
     */
    public void setOPDIV(OpdivCodeType value) {
        this.opdiv = value;
    }

    /**
     * Gets the value of the affiliationCode property.
     * 
     * @return
     *     possible object is
     *     {@link AffiliationCodeType }
     *     
     */
    public AffiliationCodeType getAffiliationCode() {
        return affiliationCode;
    }

    /**
     * Sets the value of the affiliationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AffiliationCodeType }
     *     
     */
    public void setAffiliationCode(AffiliationCodeType value) {
        this.affiliationCode = value;
    }

    /**
     * Gets the value of the can property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCAN() {
        return can;
    }

    /**
     * Sets the value of the can property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCAN(String value) {
        this.can = value;
    }

    /**
     * Gets the value of the primarySmtpEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimarySmtpEmailAddress() {
        return primarySmtpEmailAddress;
    }

    /**
     * Sets the value of the primarySmtpEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarySmtpEmailAddress(String value) {
        this.primarySmtpEmailAddress = value;
    }

    /**
     * Gets the value of the upn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUPN() {
        return upn;
    }

    /**
     * Sets the value of the upn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUPN(String value) {
        this.upn = value;
    }

    /**
     * Gets the value of the issuingAuthority property.
     * 
     * @return
     *     possible object is
     *     {@link IssuingAuthorityCodeType }
     *     
     */
    public IssuingAuthorityCodeType getIssuingAuthority() {
        return issuingAuthority;
    }

    /**
     * Sets the value of the issuingAuthority property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssuingAuthorityCodeType }
     *     
     */
    public void setIssuingAuthority(IssuingAuthorityCodeType value) {
        this.issuingAuthority = value;
    }

    /**
     * Gets the value of the credentialCategory property.
     * 
     * @return
     *     possible object is
     *     {@link CredentialCategoryType }
     *     
     */
    public CredentialCategoryType getCredentialCategory() {
        return credentialCategory;
    }

    /**
     * Sets the value of the credentialCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link CredentialCategoryType }
     *     
     */
    public void setCredentialCategory(CredentialCategoryType value) {
        this.credentialCategory = value;
    }

}
