//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type defines the data maintained about the owner of an 
 *                 identity in the IDM.
 *             
 * 
 * <p>Java class for IdentityOwnerType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentityOwnerType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OwningOrganization" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OrganizationCodeType"/&gt;
 *         &lt;element name="OwningAgency" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType"/&gt;
 *         &lt;element name="OwningSubGroup" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivSubgroupCodeType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentityOwnerType", namespace = "http://hspd12.hhs.gov/federated/idm/idmsInterface/v1", propOrder = {
    "owningOrganization",
    "owningAgency",
    "owningSubGroup"
})
public class IdentityOwnerType {

    @XmlElement(name = "OwningOrganization", required = true)
    @XmlSchemaType(name = "string")
    protected OrganizationCodeType owningOrganization;
    @XmlElement(name = "OwningAgency", required = true)
    @XmlSchemaType(name = "string")
    protected OpdivCodeType owningAgency;
    @XmlElement(name = "OwningSubGroup", required = true)
    @XmlSchemaType(name = "string")
    protected OpdivSubgroupCodeType owningSubGroup;

    /**
     * Gets the value of the owningOrganization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationCodeType }
     *     
     */
    public OrganizationCodeType getOwningOrganization() {
        return owningOrganization;
    }

    /**
     * Sets the value of the owningOrganization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationCodeType }
     *     
     */
    public void setOwningOrganization(OrganizationCodeType value) {
        this.owningOrganization = value;
    }

    /**
     * Gets the value of the owningAgency property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivCodeType }
     *     
     */
    public OpdivCodeType getOwningAgency() {
        return owningAgency;
    }

    /**
     * Sets the value of the owningAgency property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivCodeType }
     *     
     */
    public void setOwningAgency(OpdivCodeType value) {
        this.owningAgency = value;
    }

    /**
     * Gets the value of the owningSubGroup property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivSubgroupCodeType }
     *     
     */
    public OpdivSubgroupCodeType getOwningSubGroup() {
        return owningSubGroup;
    }

    /**
     * Sets the value of the owningSubGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivSubgroupCodeType }
     *     
     */
    public void setOwningSubGroup(OpdivSubgroupCodeType value) {
        this.owningSubGroup = value;
    }

}
