//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This element contains information needed to identify the
 *         		person being sponsored. At least one of the sub elements 
 *         		must be specified or the induction request will be rejected.
 *         	
 * 
 * <p>Java class for IdentificationInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IdentificationInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SSN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}SocialSecurityNumberType" minOccurs="0"/&gt;
 *         &lt;element name="ARN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}AlienRegistrationNumberType" minOccurs="0"/&gt;
 *         &lt;element name="VisaNumber" type="{http://hspd12.hhs.gov/federated/enrollment/v1}VisaNumberType" minOccurs="0"/&gt;
 *         &lt;element name="ForeignPOB" type="{http://hspd12.hhs.gov/federated/enrollment/v1}ForeignPlaceOfBirthInfoType" minOccurs="0"/&gt;
 *         &lt;element name="ForeignId" type="{http://hspd12.hhs.gov/federated/enrollment/v1}ForeignNationalIdInfoType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IdentificationInformationType", propOrder = {
    "ssn",
    "arn",
    "visaNumber",
    "foreignPOB",
    "foreignId"
})
public class IdentificationInformationType {

    @XmlElement(name = "SSN")
    protected String ssn;
    @XmlElement(name = "ARN")
    protected String arn;
    @XmlElement(name = "VisaNumber")
    protected String visaNumber;
    @XmlElement(name = "ForeignPOB")
    protected ForeignPlaceOfBirthInfoType foreignPOB;
    @XmlElement(name = "ForeignId")
    protected ForeignNationalIdInfoType foreignId;

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the arn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getARN() {
        return arn;
    }

    /**
     * Sets the value of the arn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setARN(String value) {
        this.arn = value;
    }

    /**
     * Gets the value of the visaNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisaNumber() {
        return visaNumber;
    }

    /**
     * Sets the value of the visaNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisaNumber(String value) {
        this.visaNumber = value;
    }

    /**
     * Gets the value of the foreignPOB property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignPlaceOfBirthInfoType }
     *     
     */
    public ForeignPlaceOfBirthInfoType getForeignPOB() {
        return foreignPOB;
    }

    /**
     * Sets the value of the foreignPOB property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignPlaceOfBirthInfoType }
     *     
     */
    public void setForeignPOB(ForeignPlaceOfBirthInfoType value) {
        this.foreignPOB = value;
    }

    /**
     * Gets the value of the foreignId property.
     * 
     * @return
     *     possible object is
     *     {@link ForeignNationalIdInfoType }
     *     
     */
    public ForeignNationalIdInfoType getForeignId() {
        return foreignId;
    }

    /**
     * Sets the value of the foreignId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ForeignNationalIdInfoType }
     *     
     */
    public void setForeignId(ForeignNationalIdInfoType value) {
        this.foreignId = value;
    }

}
