//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This Type defines the data items for a single Applicant 
 *         		in an InductPersonRequest call.
 *         	
 * 
 * <p>Java class for InductPersonApplicantDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="InductPersonApplicantDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="BaseInductPersonData" type="{http://hspd12.hhs.gov/federated/enrollment/v1}HHSInductPersonRequiredDataType"/&gt;
 *         &lt;element name="ExtraInductPersonData" type="{http://hspd12.hhs.gov/federated/enrollment/v1}HHSInductPersonOptionalDataType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "InductPersonApplicantDataType", propOrder = {
    "baseInductPersonData",
    "extraInductPersonData"
})
public class InductPersonApplicantDataType {

    @XmlElement(name = "BaseInductPersonData", required = true)
    protected HHSInductPersonRequiredDataType baseInductPersonData;
    @XmlElement(name = "ExtraInductPersonData")
    protected HHSInductPersonOptionalDataType extraInductPersonData;

    /**
     * Gets the value of the baseInductPersonData property.
     * 
     * @return
     *     possible object is
     *     {@link HHSInductPersonRequiredDataType }
     *     
     */
    public HHSInductPersonRequiredDataType getBaseInductPersonData() {
        return baseInductPersonData;
    }

    /**
     * Sets the value of the baseInductPersonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HHSInductPersonRequiredDataType }
     *     
     */
    public void setBaseInductPersonData(HHSInductPersonRequiredDataType value) {
        this.baseInductPersonData = value;
    }

    /**
     * Gets the value of the extraInductPersonData property.
     * 
     * @return
     *     possible object is
     *     {@link HHSInductPersonOptionalDataType }
     *     
     */
    public HHSInductPersonOptionalDataType getExtraInductPersonData() {
        return extraInductPersonData;
    }

    /**
     * Sets the value of the extraInductPersonData property.
     * 
     * @param value
     *     allowed object is
     *     {@link HHSInductPersonOptionalDataType }
     *     
     */
    public void setExtraInductPersonData(HHSInductPersonOptionalDataType value) {
        this.extraInductPersonData = value;
    }

}
