//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * 
 *         		This Type defines the data items which can be used to match
 *         		a set of personal demographic information to a person or group 
 *         		of people in the IDMS.
 *         	
 * 
 * <p>Java class for MatchPersonSearchData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchPersonSearchData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Prefix" type="{http://hspd12.hhs.gov/federated/enrollment/v1}NamePrefixType" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}FirstNameType" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}MiddleNameType" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://hspd12.hhs.gov/federated/enrollment/v1}LastNameType" minOccurs="0"/&gt;
 *         &lt;element name="GenerationQualifier" type="{http://hspd12.hhs.gov/federated/enrollment/v1}NameGenerationQualifierType" minOccurs="0"/&gt;
 *         &lt;element name="NameSuffix" type="{http://hspd12.hhs.gov/federated/enrollment/v1}NameSuffixType" minOccurs="0"/&gt;
 *         &lt;element name="EmployeeID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivEmployeeIDType" minOccurs="0"/&gt;
 *         &lt;element name="SSN" type="{http://hspd12.hhs.gov/federated/enrollment/v1}SocialSecurityNumberType" minOccurs="0"/&gt;
 *         &lt;element name="DOB" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="CityOfBirth" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CityOfBirthType" minOccurs="0"/&gt;
 *         &lt;element name="StateOfBirth" type="{http://hspd12.hhs.gov/federated/enrollment/v1}StateCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CountryOfBirth" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="CountryOfCitizenship" type="{http://hspd12.hhs.gov/federated/enrollment/v1}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="PrimarySmtpEmailAddress" type="{http://hspd12.hhs.gov/federated/enrollment/v1}EmailAddressType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchPersonSearchData", propOrder = {
    "prefix",
    "firstName",
    "middleName",
    "lastName",
    "generationQualifier",
    "nameSuffix",
    "employeeID",
    "ssn",
    "dob",
    "cityOfBirth",
    "stateOfBirth",
    "countryOfBirth",
    "countryOfCitizenship",
    "primarySmtpEmailAddress"
})
public class MatchPersonSearchData {

    @XmlElement(name = "Prefix")
    @XmlSchemaType(name = "string")
    protected NamePrefixType prefix;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElement(name = "GenerationQualifier")
    @XmlSchemaType(name = "string")
    protected NameGenerationQualifierType generationQualifier;
    @XmlElement(name = "NameSuffix")
    protected String nameSuffix;
    @XmlElement(name = "EmployeeID")
    protected String employeeID;
    @XmlElement(name = "SSN")
    protected String ssn;
    @XmlElement(name = "DOB")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar dob;
    @XmlElement(name = "CityOfBirth")
    protected String cityOfBirth;
    @XmlElement(name = "StateOfBirth")
    @XmlSchemaType(name = "string")
    protected StateCodeType stateOfBirth;
    @XmlElement(name = "CountryOfBirth")
    @XmlSchemaType(name = "string")
    protected CountryCodeType countryOfBirth;
    @XmlElement(name = "CountryOfCitizenship")
    @XmlSchemaType(name = "string")
    protected CountryCodeType countryOfCitizenship;
    @XmlElement(name = "PrimarySmtpEmailAddress")
    protected String primarySmtpEmailAddress;

    /**
     * Gets the value of the prefix property.
     * 
     * @return
     *     possible object is
     *     {@link NamePrefixType }
     *     
     */
    public NamePrefixType getPrefix() {
        return prefix;
    }

    /**
     * Sets the value of the prefix property.
     * 
     * @param value
     *     allowed object is
     *     {@link NamePrefixType }
     *     
     */
    public void setPrefix(NamePrefixType value) {
        this.prefix = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the generationQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link NameGenerationQualifierType }
     *     
     */
    public NameGenerationQualifierType getGenerationQualifier() {
        return generationQualifier;
    }

    /**
     * Sets the value of the generationQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameGenerationQualifierType }
     *     
     */
    public void setGenerationQualifier(NameGenerationQualifierType value) {
        this.generationQualifier = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameSuffix(String value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the employeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmployeeID() {
        return employeeID;
    }

    /**
     * Sets the value of the employeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmployeeID(String value) {
        this.employeeID = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSSN() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSSN(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the dob property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDOB() {
        return dob;
    }

    /**
     * Sets the value of the dob property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDOB(XMLGregorianCalendar value) {
        this.dob = value;
    }

    /**
     * Gets the value of the cityOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityOfBirth() {
        return cityOfBirth;
    }

    /**
     * Sets the value of the cityOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityOfBirth(String value) {
        this.cityOfBirth = value;
    }

    /**
     * Gets the value of the stateOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link StateCodeType }
     *     
     */
    public StateCodeType getStateOfBirth() {
        return stateOfBirth;
    }

    /**
     * Sets the value of the stateOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link StateCodeType }
     *     
     */
    public void setStateOfBirth(StateCodeType value) {
        this.stateOfBirth = value;
    }

    /**
     * Gets the value of the countryOfBirth property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getCountryOfBirth() {
        return countryOfBirth;
    }

    /**
     * Sets the value of the countryOfBirth property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setCountryOfBirth(CountryCodeType value) {
        this.countryOfBirth = value;
    }

    /**
     * Gets the value of the countryOfCitizenship property.
     * 
     * @return
     *     possible object is
     *     {@link CountryCodeType }
     *     
     */
    public CountryCodeType getCountryOfCitizenship() {
        return countryOfCitizenship;
    }

    /**
     * Sets the value of the countryOfCitizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountryCodeType }
     *     
     */
    public void setCountryOfCitizenship(CountryCodeType value) {
        this.countryOfCitizenship = value;
    }

    /**
     * Gets the value of the primarySmtpEmailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimarySmtpEmailAddress() {
        return primarySmtpEmailAddress;
    }

    /**
     * Sets the value of the primarySmtpEmailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimarySmtpEmailAddress(String value) {
        this.primarySmtpEmailAddress = value;
    }

}
