//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.hhs.induction.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _PersonInformationTypeSalutation_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "Salutation");
    private final static QName _PersonInformationTypeMiddleName_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "MiddleName");
    private final static QName _PersonInformationTypeNameSuffix_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "NameSuffix");
    private final static QName _PersonInformationTypeWorkAddress1_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkAddress1");
    private final static QName _PersonInformationTypeWorkAddress2_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkAddress2");
    private final static QName _PersonInformationTypeWorkAddress3_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkAddress3");
    private final static QName _PersonInformationTypeWorkCity_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkCity");
    private final static QName _PersonInformationTypeWorkState_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkState");
    private final static QName _PersonInformationTypeWorkPostalCode_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkPostalCode");
    private final static QName _PersonInformationTypeWorkCountry_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkCountry");
    private final static QName _PersonInformationTypeWorkPhone_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "WorkPhone");
    private final static QName _PersonInformationTypeAlternatePhone_QNAME = new QName("http://hspd12.hhs.gov/scms/idProofing/v1", "AlternatePhone");
    private final static QName _InductionDataTypeMiddleName_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "MiddleName");
    private final static QName _InductionDataTypeEmployeeID_QNAME = new QName("http://hspd12.hhs.gov/federated/enrollment/v1", "EmployeeID");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.hhs.induction.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IdmPersonInfoType }
     * 
     */
    public IdmPersonInfoType createIdmPersonInfoType() {
        return new IdmPersonInfoType();
    }

    /**
     * Create an instance of {@link IdmPersonInfoType.IdentityInfo }
     * 
     */
    public IdmPersonInfoType.IdentityInfo createIdmPersonInfoTypeIdentityInfo() {
        return new IdmPersonInfoType.IdentityInfo();
    }

    /**
     * Create an instance of {@link InductPersonRequest }
     * 
     */
    public InductPersonRequest createInductPersonRequest() {
        return new InductPersonRequest();
    }

    /**
     * Create an instance of {@link TransactionHeaderType }
     * 
     */
    public TransactionHeaderType createTransactionHeaderType() {
        return new TransactionHeaderType();
    }

    /**
     * Create an instance of {@link InductPersonApplicantDataType }
     * 
     */
    public InductPersonApplicantDataType createInductPersonApplicantDataType() {
        return new InductPersonApplicantDataType();
    }

    /**
     * Create an instance of {@link InductPersonIncRequest }
     * 
     */
    public InductPersonIncRequest createInductPersonIncRequest() {
        return new InductPersonIncRequest();
    }

    /**
     * Create an instance of {@link InductionDataType }
     * 
     */
    public InductionDataType createInductionDataType() {
        return new InductionDataType();
    }

    /**
     * Create an instance of {@link InductPersonResponse }
     * 
     */
    public InductPersonResponse createInductPersonResponse() {
        return new InductPersonResponse();
    }

    /**
     * Create an instance of {@link InductPersonResultType }
     * 
     */
    public InductPersonResultType createInductPersonResultType() {
        return new InductPersonResultType();
    }

    /**
     * Create an instance of {@link ReadInductionDataRequest }
     * 
     */
    public ReadInductionDataRequest createReadInductionDataRequest() {
        return new ReadInductionDataRequest();
    }

    /**
     * Create an instance of {@link ReadInductionDataResponse }
     * 
     */
    public ReadInductionDataResponse createReadInductionDataResponse() {
        return new ReadInductionDataResponse();
    }

    /**
     * Create an instance of {@link UpdateInductionDataRequest }
     * 
     */
    public UpdateInductionDataRequest createUpdateInductionDataRequest() {
        return new UpdateInductionDataRequest();
    }

    /**
     * Create an instance of {@link UpdateInductionDataResponse }
     * 
     */
    public UpdateInductionDataResponse createUpdateInductionDataResponse() {
        return new UpdateInductionDataResponse();
    }

    /**
     * Create an instance of {@link ReadFacialImageRequest }
     * 
     */
    public ReadFacialImageRequest createReadFacialImageRequest() {
        return new ReadFacialImageRequest();
    }

    /**
     * Create an instance of {@link ReadFacialImageResponse }
     * 
     */
    public ReadFacialImageResponse createReadFacialImageResponse() {
        return new ReadFacialImageResponse();
    }

    /**
     * Create an instance of {@link FacialImageDataType }
     * 
     */
    public FacialImageDataType createFacialImageDataType() {
        return new FacialImageDataType();
    }

    /**
     * Create an instance of {@link ReservePersonIdentifierRequest }
     * 
     */
    public ReservePersonIdentifierRequest createReservePersonIdentifierRequest() {
        return new ReservePersonIdentifierRequest();
    }

    /**
     * Create an instance of {@link ReservePersonIdentifierResponse }
     * 
     */
    public ReservePersonIdentifierResponse createReservePersonIdentifierResponse() {
        return new ReservePersonIdentifierResponse();
    }

    /**
     * Create an instance of {@link MatchPersonRequest }
     * 
     */
    public MatchPersonRequest createMatchPersonRequest() {
        return new MatchPersonRequest();
    }

    /**
     * Create an instance of {@link MatchPersonSearchData }
     * 
     */
    public MatchPersonSearchData createMatchPersonSearchData() {
        return new MatchPersonSearchData();
    }

    /**
     * Create an instance of {@link MatchPersonResponse }
     * 
     */
    public MatchPersonResponse createMatchPersonResponse() {
        return new MatchPersonResponse();
    }

    /**
     * Create an instance of {@link MatchPersonResultsData }
     * 
     */
    public MatchPersonResultsData createMatchPersonResultsData() {
        return new MatchPersonResultsData();
    }

    /**
     * Create an instance of {@link GetApplicantProcessingStateRequest }
     * 
     */
    public GetApplicantProcessingStateRequest createGetApplicantProcessingStateRequest() {
        return new GetApplicantProcessingStateRequest();
    }

    /**
     * Create an instance of {@link GetApplicantProcessingStateResponse }
     * 
     */
    public GetApplicantProcessingStateResponse createGetApplicantProcessingStateResponse() {
        return new GetApplicantProcessingStateResponse();
    }

    /**
     * Create an instance of {@link MissingInductionDataInfoType }
     * 
     */
    public MissingInductionDataInfoType createMissingInductionDataInfoType() {
        return new MissingInductionDataInfoType();
    }

    /**
     * Create an instance of {@link DeactivateApplicantRequest }
     * 
     */
    public DeactivateApplicantRequest createDeactivateApplicantRequest() {
        return new DeactivateApplicantRequest();
    }

    /**
     * Create an instance of {@link DeactivateApplicantResponse }
     * 
     */
    public DeactivateApplicantResponse createDeactivateApplicantResponse() {
        return new DeactivateApplicantResponse();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataHashRequest }
     * 
     */
    public SyncGetApplicantDataHashRequest createSyncGetApplicantDataHashRequest() {
        return new SyncGetApplicantDataHashRequest();
    }

    /**
     * Create an instance of {@link PersonIdRangeType }
     * 
     */
    public PersonIdRangeType createPersonIdRangeType() {
        return new PersonIdRangeType();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataHashResponse }
     * 
     */
    public SyncGetApplicantDataHashResponse createSyncGetApplicantDataHashResponse() {
        return new SyncGetApplicantDataHashResponse();
    }

    /**
     * Create an instance of {@link SyncApplicantDataHashType }
     * 
     */
    public SyncApplicantDataHashType createSyncApplicantDataHashType() {
        return new SyncApplicantDataHashType();
    }

    /**
     * Create an instance of {@link SyncGetApplicantInfoHashRequest }
     * 
     */
    public SyncGetApplicantInfoHashRequest createSyncGetApplicantInfoHashRequest() {
        return new SyncGetApplicantInfoHashRequest();
    }

    /**
     * Create an instance of {@link SyncGetApplicantInfoHashResponse }
     * 
     */
    public SyncGetApplicantInfoHashResponse createSyncGetApplicantInfoHashResponse() {
        return new SyncGetApplicantInfoHashResponse();
    }

    /**
     * Create an instance of {@link SyncApplicantInfoHashType }
     * 
     */
    public SyncApplicantInfoHashType createSyncApplicantInfoHashType() {
        return new SyncApplicantInfoHashType();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataDiffRequest }
     * 
     */
    public SyncGetApplicantDataDiffRequest createSyncGetApplicantDataDiffRequest() {
        return new SyncGetApplicantDataDiffRequest();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataDiffResponse }
     * 
     */
    public SyncGetApplicantDataDiffResponse createSyncGetApplicantDataDiffResponse() {
        return new SyncGetApplicantDataDiffResponse();
    }

    /**
     * Create an instance of {@link SyncGetApplicantDataDiffResultType }
     * 
     */
    public SyncGetApplicantDataDiffResultType createSyncGetApplicantDataDiffResultType() {
        return new SyncGetApplicantDataDiffResultType();
    }

    /**
     * Create an instance of {@link SyncSetOpdivHashedFieldsRequest }
     * 
     */
    public SyncSetOpdivHashedFieldsRequest createSyncSetOpdivHashedFieldsRequest() {
        return new SyncSetOpdivHashedFieldsRequest();
    }

    /**
     * Create an instance of {@link SyncSetOpdivHashedFieldsResponse }
     * 
     */
    public SyncSetOpdivHashedFieldsResponse createSyncSetOpdivHashedFieldsResponse() {
        return new SyncSetOpdivHashedFieldsResponse();
    }

    /**
     * Create an instance of {@link CardTrackingUpdateRequest }
     * 
     */
    public CardTrackingUpdateRequest createCardTrackingUpdateRequest() {
        return new CardTrackingUpdateRequest();
    }

    /**
     * Create an instance of {@link CardTrackingUpdateResponse }
     * 
     */
    public CardTrackingUpdateResponse createCardTrackingUpdateResponse() {
        return new CardTrackingUpdateResponse();
    }

    /**
     * Create an instance of {@link GetCardTrackingHistoryRequest }
     * 
     */
    public GetCardTrackingHistoryRequest createGetCardTrackingHistoryRequest() {
        return new GetCardTrackingHistoryRequest();
    }

    /**
     * Create an instance of {@link GetCardTrackingHistoryResponse }
     * 
     */
    public GetCardTrackingHistoryResponse createGetCardTrackingHistoryResponse() {
        return new GetCardTrackingHistoryResponse();
    }

    /**
     * Create an instance of {@link CardTrackingHistoryEventType }
     * 
     */
    public CardTrackingHistoryEventType createCardTrackingHistoryEventType() {
        return new CardTrackingHistoryEventType();
    }

    /**
     * Create an instance of {@link CardRenewalRequiredRequest }
     * 
     */
    public CardRenewalRequiredRequest createCardRenewalRequiredRequest() {
        return new CardRenewalRequiredRequest();
    }

    /**
     * Create an instance of {@link CardRenewalRequiredResponse }
     * 
     */
    public CardRenewalRequiredResponse createCardRenewalRequiredResponse() {
        return new CardRenewalRequiredResponse();
    }

    /**
     * Create an instance of {@link CardReissueRequiredRequest }
     * 
     */
    public CardReissueRequiredRequest createCardReissueRequiredRequest() {
        return new CardReissueRequiredRequest();
    }

    /**
     * Create an instance of {@link CardReissueRequiredResponse }
     * 
     */
    public CardReissueRequiredResponse createCardReissueRequiredResponse() {
        return new CardReissueRequiredResponse();
    }

    /**
     * Create an instance of {@link PIVTerminationRequest }
     * 
     */
    public PIVTerminationRequest createPIVTerminationRequest() {
        return new PIVTerminationRequest();
    }

    /**
     * Create an instance of {@link PIVTerminationResponse }
     * 
     */
    public PIVTerminationResponse createPIVTerminationResponse() {
        return new PIVTerminationResponse();
    }

    /**
     * Create an instance of {@link PIVReactivationRequest }
     * 
     */
    public PIVReactivationRequest createPIVReactivationRequest() {
        return new PIVReactivationRequest();
    }

    /**
     * Create an instance of {@link PIVReactivationResponse }
     * 
     */
    public PIVReactivationResponse createPIVReactivationResponse() {
        return new PIVReactivationResponse();
    }

    /**
     * Create an instance of {@link CreateBadgeRequest }
     * 
     */
    public CreateBadgeRequest createCreateBadgeRequest() {
        return new CreateBadgeRequest();
    }

    /**
     * Create an instance of {@link CreateBadgeResponse }
     * 
     */
    public CreateBadgeResponse createCreateBadgeResponse() {
        return new CreateBadgeResponse();
    }

    /**
     * Create an instance of {@link GetIssuedCardInfoRequest }
     * 
     */
    public GetIssuedCardInfoRequest createGetIssuedCardInfoRequest() {
        return new GetIssuedCardInfoRequest();
    }

    /**
     * Create an instance of {@link GetIssuedCardInfoResponse }
     * 
     */
    public GetIssuedCardInfoResponse createGetIssuedCardInfoResponse() {
        return new GetIssuedCardInfoResponse();
    }

    /**
     * Create an instance of {@link CHUIDDataFieldsType }
     * 
     */
    public CHUIDDataFieldsType createCHUIDDataFieldsType() {
        return new CHUIDDataFieldsType();
    }

    /**
     * Create an instance of {@link ReissueExistentCardRequest }
     * 
     */
    public ReissueExistentCardRequest createReissueExistentCardRequest() {
        return new ReissueExistentCardRequest();
    }

    /**
     * Create an instance of {@link ReissueExistentCardResponse }
     * 
     */
    public ReissueExistentCardResponse createReissueExistentCardResponse() {
        return new ReissueExistentCardResponse();
    }

    /**
     * Create an instance of {@link CheckCardRequest }
     * 
     */
    public CheckCardRequest createCheckCardRequest() {
        return new CheckCardRequest();
    }

    /**
     * Create an instance of {@link CheckCardResponse }
     * 
     */
    public CheckCardResponse createCheckCardResponse() {
        return new CheckCardResponse();
    }

    /**
     * Create an instance of {@link SubscribeCardEventsRequest }
     * 
     */
    public SubscribeCardEventsRequest createSubscribeCardEventsRequest() {
        return new SubscribeCardEventsRequest();
    }

    /**
     * Create an instance of {@link SubscribeCardEventsResponse }
     * 
     */
    public SubscribeCardEventsResponse createSubscribeCardEventsResponse() {
        return new SubscribeCardEventsResponse();
    }

    /**
     * Create an instance of {@link UnSubscribeCardEventsRequest }
     * 
     */
    public UnSubscribeCardEventsRequest createUnSubscribeCardEventsRequest() {
        return new UnSubscribeCardEventsRequest();
    }

    /**
     * Create an instance of {@link UnSubscribeCardEventsResponse }
     * 
     */
    public UnSubscribeCardEventsResponse createUnSubscribeCardEventsResponse() {
        return new UnSubscribeCardEventsResponse();
    }

    /**
     * Create an instance of {@link ForeignNationalIdInfoType }
     * 
     */
    public ForeignNationalIdInfoType createForeignNationalIdInfoType() {
        return new ForeignNationalIdInfoType();
    }

    /**
     * Create an instance of {@link ForeignPlaceOfBirthInfoType }
     * 
     */
    public ForeignPlaceOfBirthInfoType createForeignPlaceOfBirthInfoType() {
        return new ForeignPlaceOfBirthInfoType();
    }

    /**
     * Create an instance of {@link ApplicantAlternateUIDType }
     * 
     */
    public ApplicantAlternateUIDType createApplicantAlternateUIDType() {
        return new ApplicantAlternateUIDType();
    }

    /**
     * Create an instance of {@link FASCNDataFieldsType }
     * 
     */
    public FASCNDataFieldsType createFASCNDataFieldsType() {
        return new FASCNDataFieldsType();
    }

    /**
     * Create an instance of {@link HHSInductPersonRequiredDataType }
     * 
     */
    public HHSInductPersonRequiredDataType createHHSInductPersonRequiredDataType() {
        return new HHSInductPersonRequiredDataType();
    }

    /**
     * Create an instance of {@link HHSInductPersonOptionalDataType }
     * 
     */
    public HHSInductPersonOptionalDataType createHHSInductPersonOptionalDataType() {
        return new HHSInductPersonOptionalDataType();
    }

    /**
     * Create an instance of {@link IdentificationInformationType }
     * 
     */
    public IdentificationInformationType createIdentificationInformationType() {
        return new IdentificationInformationType();
    }

    /**
     * Create an instance of {@link ApplicantFieldDifferenceType }
     * 
     */
    public ApplicantFieldDifferenceType createApplicantFieldDifferenceType() {
        return new ApplicantFieldDifferenceType();
    }

    /**
     * Create an instance of {@link GetPersonDataRequest }
     * 
     */
    public GetPersonDataRequest createGetPersonDataRequest() {
        return new GetPersonDataRequest();
    }

    /**
     * Create an instance of {@link TransactionHeaderType2 }
     * 
     */
    public TransactionHeaderType2 createTransactionHeaderType2() {
        return new TransactionHeaderType2();
    }

    /**
     * Create an instance of {@link GetPersonDataResponse }
     * 
     */
    public GetPersonDataResponse createGetPersonDataResponse() {
        return new GetPersonDataResponse();
    }

    /**
     * Create an instance of {@link PersonInformationType }
     * 
     */
    public PersonInformationType createPersonInformationType() {
        return new PersonInformationType();
    }

    /**
     * Create an instance of {@link SetPersonDataRequest }
     * 
     */
    public SetPersonDataRequest createSetPersonDataRequest() {
        return new SetPersonDataRequest();
    }

    /**
     * Create an instance of {@link SetPersonDataResponse }
     * 
     */
    public SetPersonDataResponse createSetPersonDataResponse() {
        return new SetPersonDataResponse();
    }

    /**
     * Create an instance of {@link CreateIdmIdentityRequest }
     * 
     */
    public CreateIdmIdentityRequest createCreateIdmIdentityRequest() {
        return new CreateIdmIdentityRequest();
    }

    /**
     * Create an instance of {@link IdentityOwnerType }
     * 
     */
    public IdentityOwnerType createIdentityOwnerType() {
        return new IdentityOwnerType();
    }

    /**
     * Create an instance of {@link CreateIdmIdentityResponse }
     * 
     */
    public CreateIdmIdentityResponse createCreateIdmIdentityResponse() {
        return new CreateIdmIdentityResponse();
    }

    /**
     * Create an instance of {@link SearchIdmIdentityRequest }
     * 
     */
    public SearchIdmIdentityRequest createSearchIdmIdentityRequest() {
        return new SearchIdmIdentityRequest();
    }

    /**
     * Create an instance of {@link SearchIdmIdentityResponse }
     * 
     */
    public SearchIdmIdentityResponse createSearchIdmIdentityResponse() {
        return new SearchIdmIdentityResponse();
    }

    /**
     * Create an instance of {@link SearchIdmIdentityResponseFieldsType }
     * 
     */
    public SearchIdmIdentityResponseFieldsType createSearchIdmIdentityResponseFieldsType() {
        return new SearchIdmIdentityResponseFieldsType();
    }

    /**
     * Create an instance of {@link IdmPersonInfoType.IdentityInfo.PlaceOfBirthType }
     * 
     */
    public IdmPersonInfoType.IdentityInfo.PlaceOfBirthType createIdmPersonInfoTypeIdentityInfoPlaceOfBirthType() {
        return new IdmPersonInfoType.IdentityInfo.PlaceOfBirthType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameSalutationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "Salutation", scope = PersonInformationType.class)
    public JAXBElement<NameSalutationType> createPersonInformationTypeSalutation(NameSalutationType value) {
        return new JAXBElement<NameSalutationType>(_PersonInformationTypeSalutation_QNAME, NameSalutationType.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "MiddleName", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeMiddleName(String value) {
        return new JAXBElement<String>(_PersonInformationTypeMiddleName_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "NameSuffix", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeNameSuffix(String value) {
        return new JAXBElement<String>(_PersonInformationTypeNameSuffix_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkAddress1", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkAddress1(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkAddress1_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkAddress2", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkAddress2(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkAddress2_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkAddress3", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkAddress3(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkAddress3_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkCity", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkCity(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkCity_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkState", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkState(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkState_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkPostalCode", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkPostalCode(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkPostalCode_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkCountry", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkCountry(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkCountry_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "WorkPhone", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeWorkPhone(String value) {
        return new JAXBElement<String>(_PersonInformationTypeWorkPhone_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", name = "AlternatePhone", scope = PersonInformationType.class)
    public JAXBElement<String> createPersonInformationTypeAlternatePhone(String value) {
        return new JAXBElement<String>(_PersonInformationTypeAlternatePhone_QNAME, String.class, PersonInformationType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "MiddleName", scope = InductionDataType.class)
    public JAXBElement<String> createInductionDataTypeMiddleName(String value) {
        return new JAXBElement<String>(_InductionDataTypeMiddleName_QNAME, String.class, InductionDataType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", name = "EmployeeID", scope = InductionDataType.class)
    public JAXBElement<String> createInductionDataTypeEmployeeID(String value) {
        return new JAXBElement<String>(_InductionDataTypeEmployeeID_QNAME, String.class, InductionDataType.class, value);
    }

}
