//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OpdivSubgroupCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OpdivSubgroupCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="50"/&gt;
 *     &lt;enumeration value="NONE"/&gt;
 *     &lt;enumeration value="FDA-SPECIAL"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OpdivSubgroupCodeType")
@XmlEnum
public enum OpdivSubgroupCodeType {


    /**
     * Not a member of a special agency subgroup
     * 
     */
    NONE("NONE"),

    /**
     * FDA Special subgroup
     * 
     */
    @XmlEnumValue("FDA-SPECIAL")
    FDA_SPECIAL("FDA-SPECIAL");
    private final String value;

    OpdivSubgroupCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static OpdivSubgroupCodeType fromValue(String v) {
        for (OpdivSubgroupCodeType c: OpdivSubgroupCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
