//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hspd12.hhs.gov/federated/enrollment/v1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.hhs.induction.schemas;
