//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This type defines the data fields for information about a person.
 *             
 * 
 * <p>Java class for PersonInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonInformationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Salutation" type="{http://hspd12.hhs.gov/scms/idProofing/v1}NameSalutationType" minOccurs="0"/&gt;
 *         &lt;element name="FirstName" type="{http://hspd12.hhs.gov/scms/idProofing/v1}NameFirstType" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://hspd12.hhs.gov/scms/idProofing/v1}NameMiddleType" minOccurs="0"/&gt;
 *         &lt;element name="LastName" type="{http://hspd12.hhs.gov/scms/idProofing/v1}NameLastType" minOccurs="0"/&gt;
 *         &lt;element name="NameSuffix" type="{http://hspd12.hhs.gov/scms/idProofing/v1}NameSuffixType" minOccurs="0"/&gt;
 *         &lt;element name="EmailAddress" type="{http://hspd12.hhs.gov/scms/idProofing/v1}EmailAddressType" minOccurs="0"/&gt;
 *         &lt;element name="OrgName" type="{http://hspd12.hhs.gov/scms/idProofing/v1}OrgNameType" minOccurs="0"/&gt;
 *         &lt;element name="OrgRole" type="{http://hspd12.hhs.gov/scms/idProofing/v1}OrgPersonRoleType" minOccurs="0"/&gt;
 *         &lt;element name="WorkAddress1" type="{http://hspd12.hhs.gov/scms/idProofing/v1}PostalAddrStreetAddrType" minOccurs="0"/&gt;
 *         &lt;element name="WorkAddress2" type="{http://hspd12.hhs.gov/scms/idProofing/v1}PostalAddrStreetAddrType" minOccurs="0"/&gt;
 *         &lt;element name="WorkAddress3" type="{http://hspd12.hhs.gov/scms/idProofing/v1}PostalAddrStreetAddrType" minOccurs="0"/&gt;
 *         &lt;element name="WorkCity" type="{http://hspd12.hhs.gov/scms/idProofing/v1}CityNameType" minOccurs="0"/&gt;
 *         &lt;element name="WorkState" type="{http://hspd12.hhs.gov/scms/idProofing/v1}StateCodeType" minOccurs="0"/&gt;
 *         &lt;element name="WorkPostalCode" type="{http://hspd12.hhs.gov/scms/idProofing/v1}PostalCodeType" minOccurs="0"/&gt;
 *         &lt;element name="WorkCountry" type="{http://hspd12.hhs.gov/scms/idProofing/v1}CountryCodeType" minOccurs="0"/&gt;
 *         &lt;element name="WorkPhone" type="{http://hspd12.hhs.gov/scms/idProofing/v1}PhoneNumberType" minOccurs="0"/&gt;
 *         &lt;element name="AlternatePhone" type="{http://hspd12.hhs.gov/scms/idProofing/v1}PhoneNumberType" minOccurs="0"/&gt;
 *         &lt;element name="PrimaryPhoneField" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;enumeration value="WorkPhone"/&gt;
 *               &lt;enumeration value="AlternatePhone"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonInformationType", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", propOrder = {
    "salutation",
    "firstName",
    "middleName",
    "lastName",
    "nameSuffix",
    "emailAddress",
    "orgName",
    "orgRole",
    "workAddress1",
    "workAddress2",
    "workAddress3",
    "workCity",
    "workState",
    "workPostalCode",
    "workCountry",
    "workPhone",
    "alternatePhone",
    "primaryPhoneField"
})
public class PersonInformationType {

    @XmlElementRef(name = "Salutation", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<NameSalutationType> salutation;
    @XmlElement(name = "FirstName")
    protected String firstName;
    @XmlElementRef(name = "MiddleName", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> middleName;
    @XmlElement(name = "LastName")
    protected String lastName;
    @XmlElementRef(name = "NameSuffix", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> nameSuffix;
    @XmlElement(name = "EmailAddress")
    protected String emailAddress;
    @XmlElement(name = "OrgName")
    protected String orgName;
    @XmlElement(name = "OrgRole")
    protected String orgRole;
    @XmlElementRef(name = "WorkAddress1", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workAddress1;
    @XmlElementRef(name = "WorkAddress2", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workAddress2;
    @XmlElementRef(name = "WorkAddress3", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workAddress3;
    @XmlElementRef(name = "WorkCity", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workCity;
    @XmlElementRef(name = "WorkState", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workState;
    @XmlElementRef(name = "WorkPostalCode", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPostalCode;
    @XmlElementRef(name = "WorkCountry", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workCountry;
    @XmlElementRef(name = "WorkPhone", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> workPhone;
    @XmlElementRef(name = "AlternatePhone", namespace = "http://hspd12.hhs.gov/scms/idProofing/v1", type = JAXBElement.class, required = false)
    protected JAXBElement<String> alternatePhone;
    @XmlElement(name = "PrimaryPhoneField")
    protected String primaryPhoneField;

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link NameSalutationType }{@code >}
     *     
     */
    public JAXBElement<NameSalutationType> getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link NameSalutationType }{@code >}
     *     
     */
    public void setSalutation(JAXBElement<NameSalutationType> value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setMiddleName(JAXBElement<String> value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setNameSuffix(JAXBElement<String> value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the emailAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * Sets the value of the emailAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmailAddress(String value) {
        this.emailAddress = value;
    }

    /**
     * Gets the value of the orgName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * Sets the value of the orgName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgName(String value) {
        this.orgName = value;
    }

    /**
     * Gets the value of the orgRole property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrgRole() {
        return orgRole;
    }

    /**
     * Sets the value of the orgRole property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrgRole(String value) {
        this.orgRole = value;
    }

    /**
     * Gets the value of the workAddress1 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkAddress1() {
        return workAddress1;
    }

    /**
     * Sets the value of the workAddress1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkAddress1(JAXBElement<String> value) {
        this.workAddress1 = value;
    }

    /**
     * Gets the value of the workAddress2 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkAddress2() {
        return workAddress2;
    }

    /**
     * Sets the value of the workAddress2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkAddress2(JAXBElement<String> value) {
        this.workAddress2 = value;
    }

    /**
     * Gets the value of the workAddress3 property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkAddress3() {
        return workAddress3;
    }

    /**
     * Sets the value of the workAddress3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkAddress3(JAXBElement<String> value) {
        this.workAddress3 = value;
    }

    /**
     * Gets the value of the workCity property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkCity() {
        return workCity;
    }

    /**
     * Sets the value of the workCity property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkCity(JAXBElement<String> value) {
        this.workCity = value;
    }

    /**
     * Gets the value of the workState property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkState() {
        return workState;
    }

    /**
     * Sets the value of the workState property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkState(JAXBElement<String> value) {
        this.workState = value;
    }

    /**
     * Gets the value of the workPostalCode property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPostalCode() {
        return workPostalCode;
    }

    /**
     * Sets the value of the workPostalCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPostalCode(JAXBElement<String> value) {
        this.workPostalCode = value;
    }

    /**
     * Gets the value of the workCountry property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkCountry() {
        return workCountry;
    }

    /**
     * Sets the value of the workCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkCountry(JAXBElement<String> value) {
        this.workCountry = value;
    }

    /**
     * Gets the value of the workPhone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getWorkPhone() {
        return workPhone;
    }

    /**
     * Sets the value of the workPhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setWorkPhone(JAXBElement<String> value) {
        this.workPhone = value;
    }

    /**
     * Gets the value of the alternatePhone property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getAlternatePhone() {
        return alternatePhone;
    }

    /**
     * Sets the value of the alternatePhone property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setAlternatePhone(JAXBElement<String> value) {
        this.alternatePhone = value;
    }

    /**
     * Gets the value of the primaryPhoneField property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryPhoneField() {
        return primaryPhoneField;
    }

    /**
     * Sets the value of the primaryPhoneField property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryPhoneField(String value) {
        this.primaryPhoneField = value;
    }

}
