//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PIVReactivationReasonCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PIVReactivationReasonCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="EmploymentReinstated"/&gt;
 *     &lt;enumeration value="LostCardFound"/&gt;
 *     &lt;enumeration value="StolenCardRetrieved"/&gt;
 *     &lt;enumeration value="Other"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PIVReactivationReasonCodeType")
@XmlEnum
public enum PIVReactivationReasonCodeType {

    @XmlEnumValue("EmploymentReinstated")
    EMPLOYMENT_REINSTATED("EmploymentReinstated"),
    @XmlEnumValue("LostCardFound")
    LOST_CARD_FOUND("LostCardFound"),
    @XmlEnumValue("StolenCardRetrieved")
    STOLEN_CARD_RETRIEVED("StolenCardRetrieved"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    PIVReactivationReasonCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PIVReactivationReasonCodeType fromValue(String v) {
        for (PIVReactivationReasonCodeType c: PIVReactivationReasonCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
