//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ProcessingStateCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ProcessingStateCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="40"/&gt;
 *     &lt;enumeration value="InductionDataWait"/&gt;
 *     &lt;enumeration value="InductionComplete"/&gt;
 *     &lt;enumeration value="SponsorWait"/&gt;
 *     &lt;enumeration value="Sponsored"/&gt;
 *     &lt;enumeration value="EnrollWait"/&gt;
 *     &lt;enumeration value="Enrolled"/&gt;
 *     &lt;enumeration value="AdjudicationWait"/&gt;
 *     &lt;enumeration value="AdjudicateApprove"/&gt;
 *     &lt;enumeration value="AdjudicateReject"/&gt;
 *     &lt;enumeration value="CardProductionRequested"/&gt;
 *     &lt;enumeration value="CardProductionWait"/&gt;
 *     &lt;enumeration value="CardProduced"/&gt;
 *     &lt;enumeration value="CardIssueWait"/&gt;
 *     &lt;enumeration value="CardIssueComplete"/&gt;
 *     &lt;enumeration value="CardIssueFail"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ProcessingStateCodeType")
@XmlEnum
public enum ProcessingStateCodeType {


    /**
     * 
     * 						Waiting on induction data 
     * 					
     * 
     */
    @XmlEnumValue("InductionDataWait")
    INDUCTION_DATA_WAIT("InductionDataWait"),

    /**
     * All required induction data has been provided
     * 
     */
    @XmlEnumValue("InductionComplete")
    INDUCTION_COMPLETE("InductionComplete"),

    /**
     * An Applicant with all required induction data is awaiting sponsorship
     * 
     */
    @XmlEnumValue("SponsorWait")
    SPONSOR_WAIT("SponsorWait"),

    /**
     * 
     * 						The applicant has been inducted and sponsored
     * 					
     * 
     */
    @XmlEnumValue("Sponsored")
    SPONSORED("Sponsored"),

    /**
     * Waiting on applicant to enroll
     * 
     */
    @XmlEnumValue("EnrollWait")
    ENROLL_WAIT("EnrollWait"),

    /**
     * Applicant successfully inducted and enrolled
     * 
     */
    @XmlEnumValue("Enrolled")
    ENROLLED("Enrolled"),

    /**
     * Applicant awaiting adjudication
     * 
     */
    @XmlEnumValue("AdjudicationWait")
    ADJUDICATION_WAIT("AdjudicationWait"),

    /**
     * Applicant was approved by adjudicator
     * 
     */
    @XmlEnumValue("AdjudicateApprove")
    ADJUDICATE_APPROVE("AdjudicateApprove"),

    /**
     * Applicant was rejected by adjudicator
     * 
     */
    @XmlEnumValue("AdjudicateReject")
    ADJUDICATE_REJECT("AdjudicateReject"),

    /**
     * A card production request has been sent
     * 
     */
    @XmlEnumValue("CardProductionRequested")
    CARD_PRODUCTION_REQUESTED("CardProductionRequested"),

    /**
     * Waiting for the Applicant's card to be printed and delivered
     * 
     */
    @XmlEnumValue("CardProductionWait")
    CARD_PRODUCTION_WAIT("CardProductionWait"),

    /**
     * The Applicant's card has been printed and delivered
     * 
     */
    @XmlEnumValue("CardProduced")
    CARD_PRODUCED("CardProduced"),

    /**
     * Waiting for applicant to show up at CIS to pick up and activate card
     * 
     */
    @XmlEnumValue("CardIssueWait")
    CARD_ISSUE_WAIT("CardIssueWait"),

    /**
     * Applicant has arrived at CIS and card has been personalized and activated
     * 
     */
    @XmlEnumValue("CardIssueComplete")
    CARD_ISSUE_COMPLETE("CardIssueComplete"),

    /**
     * Card issuance failed
     * 
     */
    @XmlEnumValue("CardIssueFail")
    CARD_ISSUE_FAIL("CardIssueFail");
    private final String value;

    ProcessingStateCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ProcessingStateCodeType fromValue(String v) {
        for (ProcessingStateCodeType c: ProcessingStateCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
