//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PropertyPassCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PropertyPassCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="3"/&gt;
 *     &lt;enumeration value="Any"/&gt;
 *     &lt;enumeration value="AV"/&gt;
 *     &lt;enumeration value="CC"/&gt;
 *     &lt;enumeration value="CE"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="CY"/&gt;
 *     &lt;enumeration value="D"/&gt;
 *     &lt;enumeration value="F"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="P"/&gt;
 *     &lt;enumeration value="T"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "PropertyPassCodeType")
@XmlEnum
public enum PropertyPassCodeType {


    /**
     * 
     * 						Any Property Type
     * 					
     * 
     */
    @XmlEnumValue("Any")
    ANY("Any"),

    /**
     * 
     * 						Audio Visual Equipment
     * 					
     * 
     */
    AV("AV"),

    /**
     * 
     * 						Computer Camera Equipment
     * 					
     * 
     */
    CC("CC"),

    /**
     * 
     * 						Computer Equipment
     * 					
     * 
     */
    CE("CE"),

    /**
     * 
     * 						Camera Equipment
     * 					
     * 
     */
    CM("CM"),

    /**
     * 
     * 						Copier Equipment
     * 					
     * 
     */
    CY("CY"),

    /**
     * 
     * 						Disk/Tape/Listings
     * 					
     * 
     */
    D("D"),

    /**
     * Furniture
     * 
     */
    F("F"),

    /**
     * Laptops
     * 
     */
    L("L"),

    /**
     * Packages
     * 
     */
    P("P"),

    /**
     * 
     * 						Telephone Equipment
     * 					
     * 
     */
    T("T");
    private final String value;

    PropertyPassCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PropertyPassCodeType fromValue(String v) {
        for (PropertyPassCodeType c: PropertyPassCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
