//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionHeader" type="{http://hspd12.hhs.gov/federated/enrollment/v1}TransactionHeaderType"/&gt;
 *         &lt;element name="Organization" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OrganizationCodeType" minOccurs="0"/&gt;
 *         &lt;element name="OPDIV" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType" minOccurs="0"/&gt;
 *         &lt;element name="OpdivEmployeeID" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivEmployeeIDType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionHeader",
    "organization",
    "opdiv",
    "opdivEmployeeID"
})
@XmlRootElement(name = "ReservePersonIdentifierRequest")
public class ReservePersonIdentifierRequest {

    @XmlElement(name = "TransactionHeader", required = true)
    protected TransactionHeaderType transactionHeader;
    @XmlElement(name = "Organization")
    @XmlSchemaType(name = "string")
    protected OrganizationCodeType organization;
    @XmlElement(name = "OPDIV")
    @XmlSchemaType(name = "string")
    protected OpdivCodeType opdiv;
    @XmlElement(name = "OpdivEmployeeID", required = true)
    protected String opdivEmployeeID;

    /**
     * Gets the value of the transactionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHeaderType }
     *     
     */
    public TransactionHeaderType getTransactionHeader() {
        return transactionHeader;
    }

    /**
     * Sets the value of the transactionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHeaderType }
     *     
     */
    public void setTransactionHeader(TransactionHeaderType value) {
        this.transactionHeader = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationCodeType }
     *     
     */
    public OrganizationCodeType getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationCodeType }
     *     
     */
    public void setOrganization(OrganizationCodeType value) {
        this.organization = value;
    }

    /**
     * Gets the value of the opdiv property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivCodeType }
     *     
     */
    public OpdivCodeType getOPDIV() {
        return opdiv;
    }

    /**
     * Sets the value of the opdiv property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivCodeType }
     *     
     */
    public void setOPDIV(OpdivCodeType value) {
        this.opdiv = value;
    }

    /**
     * Gets the value of the opdivEmployeeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpdivEmployeeID() {
        return opdivEmployeeID;
    }

    /**
     * Sets the value of the opdivEmployeeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpdivEmployeeID(String value) {
        this.opdivEmployeeID = value;
    }

}
