//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 This Type defines the result type used in the 
 *                 SearchVimIdentityResponse element to return
 *                 One of these items will be returned for each
 *                 IDM identity field values requested. 
 *             
 * 
 * <p>Java class for SearchIdmIdentityResponseFieldsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchIdmIdentityResponseFieldsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FieldType" type="{http://hspd12.hhs.gov/federated/idm/idmsInterface/v1}IdmDataFieldsEnumType"/&gt;
 *         &lt;element name="FieldStringValue" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchIdmIdentityResponseFieldsType", namespace = "http://hspd12.hhs.gov/federated/idm/idmsInterface/v1", propOrder = {
    "fieldType",
    "fieldStringValue"
})
public class SearchIdmIdentityResponseFieldsType {

    @XmlElement(name = "FieldType", required = true)
    @XmlSchemaType(name = "string")
    protected IdmDataFieldsEnumType fieldType;
    @XmlElement(name = "FieldStringValue")
    protected String fieldStringValue;

    /**
     * Gets the value of the fieldType property.
     * 
     * @return
     *     possible object is
     *     {@link IdmDataFieldsEnumType }
     *     
     */
    public IdmDataFieldsEnumType getFieldType() {
        return fieldType;
    }

    /**
     * Sets the value of the fieldType property.
     * 
     * @param value
     *     allowed object is
     *     {@link IdmDataFieldsEnumType }
     *     
     */
    public void setFieldType(IdmDataFieldsEnumType value) {
        this.fieldType = value;
    }

    /**
     * Gets the value of the fieldStringValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldStringValue() {
        return fieldStringValue;
    }

    /**
     * Sets the value of the fieldStringValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldStringValue(String value) {
        this.fieldStringValue = value;
    }

}
