//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SecurityAccessCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SecurityAccessCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;maxLength value="2"/&gt;
 *     &lt;enumeration value="R"/&gt;
 *     &lt;enumeration value="A"/&gt;
 *     &lt;enumeration value="AE"/&gt;
 *     &lt;enumeration value="E"/&gt;
 *     &lt;enumeration value="L"/&gt;
 *     &lt;enumeration value="C"/&gt;
 *     &lt;enumeration value="NM"/&gt;
 *     &lt;enumeration value="NP"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SecurityAccessCodeType")
@XmlEnum
public enum SecurityAccessCodeType {


    /**
     * 
     * 						Restricted Area Access (Datacenters, equipment
     * 						access)
     * 					
     * 
     */
    R,

    /**
     *  24-Hour Access
     * 
     */
    A,

    /**
     * 
     * 						24-Hour Access, Escort Authority
     * 					
     * 
     */
    AE,

    /**
     * 
     * 						Escort Authority
     * 					
     * 
     */
    E,

    /**
     * LAB
     * 
     */
    L,

    /**
     * COOP
     * 
     */
    C,

    /**
     * No Magnetometer Screening
     * 
     */
    NM,

    /**
     * No Parking
     * 
     */
    NP;

    public String value() {
        return name();
    }

    public static SecurityAccessCodeType fromValue(String v) {
        return valueOf(v);
    }

}
