//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionHeader" type="{http://hspd12.hhs.gov/federated/enrollment/v1}TransactionHeaderType"/&gt;
 *         &lt;element name="SearchOPDIV" type="{http://hspd12.hhs.gov/federated/enrollment/v1}OpdivCodeType"/&gt;
 *         &lt;element name="SearchPersonIdRange" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdRangeType" minOccurs="0"/&gt;
 *         &lt;element name="SearchPersonId" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdType" maxOccurs="1000" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "transactionHeader",
    "searchOPDIV",
    "searchPersonIdRange",
    "searchPersonId"
})
@XmlRootElement(name = "SyncGetApplicantDataHashRequest")
public class SyncGetApplicantDataHashRequest {

    @XmlElement(name = "TransactionHeader", required = true)
    protected TransactionHeaderType transactionHeader;
    @XmlElement(name = "SearchOPDIV", required = true)
    @XmlSchemaType(name = "string")
    protected OpdivCodeType searchOPDIV;
    @XmlElement(name = "SearchPersonIdRange")
    protected PersonIdRangeType searchPersonIdRange;
    @XmlElement(name = "SearchPersonId")
    protected List<String> searchPersonId;

    /**
     * Gets the value of the transactionHeader property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionHeaderType }
     *     
     */
    public TransactionHeaderType getTransactionHeader() {
        return transactionHeader;
    }

    /**
     * Sets the value of the transactionHeader property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionHeaderType }
     *     
     */
    public void setTransactionHeader(TransactionHeaderType value) {
        this.transactionHeader = value;
    }

    /**
     * Gets the value of the searchOPDIV property.
     * 
     * @return
     *     possible object is
     *     {@link OpdivCodeType }
     *     
     */
    public OpdivCodeType getSearchOPDIV() {
        return searchOPDIV;
    }

    /**
     * Sets the value of the searchOPDIV property.
     * 
     * @param value
     *     allowed object is
     *     {@link OpdivCodeType }
     *     
     */
    public void setSearchOPDIV(OpdivCodeType value) {
        this.searchOPDIV = value;
    }

    /**
     * Gets the value of the searchPersonIdRange property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdRangeType }
     *     
     */
    public PersonIdRangeType getSearchPersonIdRange() {
        return searchPersonIdRange;
    }

    /**
     * Sets the value of the searchPersonIdRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdRangeType }
     *     
     */
    public void setSearchPersonIdRange(PersonIdRangeType value) {
        this.searchPersonIdRange = value;
    }

    /**
     * Gets the value of the searchPersonId property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the searchPersonId property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSearchPersonId().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getSearchPersonId() {
        if (searchPersonId == null) {
            searchPersonId = new ArrayList<String>();
        }
        return this.searchPersonId;
    }

}
