//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SyncApplicantDataFieldsEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SyncApplicantDataFieldsEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Prefix"/&gt;
 *     &lt;enumeration value="FirstName"/&gt;
 *     &lt;enumeration value="MiddleName"/&gt;
 *     &lt;enumeration value="LastName"/&gt;
 *     &lt;enumeration value="GenerationQualifier"/&gt;
 *     &lt;enumeration value="NameSuffix"/&gt;
 *     &lt;enumeration value="PersonID"/&gt;
 *     &lt;enumeration value="EmployeeID"/&gt;
 *     &lt;enumeration value="SSN"/&gt;
 *     &lt;enumeration value="DOB"/&gt;
 *     &lt;enumeration value="CityOfBirth"/&gt;
 *     &lt;enumeration value="StateOfBirth"/&gt;
 *     &lt;enumeration value="CountryOfBirth"/&gt;
 *     &lt;enumeration value="CountryOfCitizenship"/&gt;
 *     &lt;enumeration value="VisaNumber"/&gt;
 *     &lt;enumeration value="ARN"/&gt;
 *     &lt;enumeration value="ForeignID"/&gt;
 *     &lt;enumeration value="PositionTitle"/&gt;
 *     &lt;enumeration value="PositionSensitivity"/&gt;
 *     &lt;enumeration value="EmergencyResponder"/&gt;
 *     &lt;enumeration value="CredentialCategory"/&gt;
 *     &lt;enumeration value="AlternateEmailAddress"/&gt;
 *     &lt;enumeration value="Organization"/&gt;
 *     &lt;enumeration value="OPDIV"/&gt;
 *     &lt;enumeration value="AffiliationCode"/&gt;
 *     &lt;enumeration value="WorkPhone"/&gt;
 *     &lt;enumeration value="WorkPhoneExtension"/&gt;
 *     &lt;enumeration value="CostCenter"/&gt;
 *     &lt;enumeration value="CAN"/&gt;
 *     &lt;enumeration value="SubAgency"/&gt;
 *     &lt;enumeration value="FundsCertification"/&gt;
 *     &lt;enumeration value="SponsorshipStatus"/&gt;
 *     &lt;enumeration value="SponsorPI"/&gt;
 *     &lt;enumeration value="SponsorDate"/&gt;
 *     &lt;enumeration value="InductorPI"/&gt;
 *     &lt;enumeration value="InductorEmail"/&gt;
 *     &lt;enumeration value="SACAdjudicationStatus"/&gt;
 *     &lt;enumeration value="SACAdjudicatorPI"/&gt;
 *     &lt;enumeration value="SACAdjudicationDate"/&gt;
 *     &lt;enumeration value="BkinvestAdjudicationStatus"/&gt;
 *     &lt;enumeration value="BkinvestType"/&gt;
 *     &lt;enumeration value="BkinvestAdjudicatorPI"/&gt;
 *     &lt;enumeration value="BkinvestAdjudicationDate"/&gt;
 *     &lt;enumeration value="PrimarySmtpEmailAddress"/&gt;
 *     &lt;enumeration value="UPN"/&gt;
 *     &lt;enumeration value="BadgeExpDate"/&gt;
 *     &lt;enumeration value="IssuingAuthority"/&gt;
 *     &lt;enumeration value="PropertyPassCodes"/&gt;
 *     &lt;enumeration value="SecAccessCodes"/&gt;
 *     &lt;enumeration value="SOI"/&gt;
 *     &lt;enumeration value="SON"/&gt;
 *     &lt;enumeration value="PivProcessFlowCode"/&gt;
 *     &lt;enumeration value="EarliestCardIssueDate"/&gt;
 *     &lt;enumeration value="AlternateUID"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "SyncApplicantDataFieldsEnumType")
@XmlEnum
public enum SyncApplicantDataFieldsEnumType {


    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("Prefix")
    PREFIX("Prefix"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("FirstName")
    FIRST_NAME("FirstName"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("MiddleName")
    MIDDLE_NAME("MiddleName"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("LastName")
    LAST_NAME("LastName"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("GenerationQualifier")
    GENERATION_QUALIFIER("GenerationQualifier"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("NameSuffix")
    NAME_SUFFIX("NameSuffix"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("PersonID")
    PERSON_ID("PersonID"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("EmployeeID")
    EMPLOYEE_ID("EmployeeID"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    SSN("SSN"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    DOB("DOB"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("CityOfBirth")
    CITY_OF_BIRTH("CityOfBirth"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("StateOfBirth")
    STATE_OF_BIRTH("StateOfBirth"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("CountryOfBirth")
    COUNTRY_OF_BIRTH("CountryOfBirth"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("CountryOfCitizenship")
    COUNTRY_OF_CITIZENSHIP("CountryOfCitizenship"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("VisaNumber")
    VISA_NUMBER("VisaNumber"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    ARN("ARN"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("ForeignID")
    FOREIGN_ID("ForeignID"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("PositionTitle")
    POSITION_TITLE("PositionTitle"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("PositionSensitivity")
    POSITION_SENSITIVITY("PositionSensitivity"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("EmergencyResponder")
    EMERGENCY_RESPONDER("EmergencyResponder"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("CredentialCategory")
    CREDENTIAL_CATEGORY("CredentialCategory"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("AlternateEmailAddress")
    ALTERNATE_EMAIL_ADDRESS("AlternateEmailAddress"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("Organization")
    ORGANIZATION("Organization"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    OPDIV("OPDIV"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("AffiliationCode")
    AFFILIATION_CODE("AffiliationCode"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("WorkPhone")
    WORK_PHONE("WorkPhone"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("WorkPhoneExtension")
    WORK_PHONE_EXTENSION("WorkPhoneExtension"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("CostCenter")
    COST_CENTER("CostCenter"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    CAN("CAN"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SubAgency")
    SUB_AGENCY("SubAgency"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("FundsCertification")
    FUNDS_CERTIFICATION("FundsCertification"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SponsorshipStatus")
    SPONSORSHIP_STATUS("SponsorshipStatus"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SponsorPI")
    SPONSOR_PI("SponsorPI"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SponsorDate")
    SPONSOR_DATE("SponsorDate"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("InductorPI")
    INDUCTOR_PI("InductorPI"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("InductorEmail")
    INDUCTOR_EMAIL("InductorEmail"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SACAdjudicationStatus")
    SAC_ADJUDICATION_STATUS("SACAdjudicationStatus"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SACAdjudicatorPI")
    SAC_ADJUDICATOR_PI("SACAdjudicatorPI"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SACAdjudicationDate")
    SAC_ADJUDICATION_DATE("SACAdjudicationDate"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("BkinvestAdjudicationStatus")
    BKINVEST_ADJUDICATION_STATUS("BkinvestAdjudicationStatus"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("BkinvestType")
    BKINVEST_TYPE("BkinvestType"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("BkinvestAdjudicatorPI")
    BKINVEST_ADJUDICATOR_PI("BkinvestAdjudicatorPI"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("BkinvestAdjudicationDate")
    BKINVEST_ADJUDICATION_DATE("BkinvestAdjudicationDate"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("PrimarySmtpEmailAddress")
    PRIMARY_SMTP_EMAIL_ADDRESS("PrimarySmtpEmailAddress"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    UPN("UPN"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("BadgeExpDate")
    BADGE_EXP_DATE("BadgeExpDate"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("IssuingAuthority")
    ISSUING_AUTHORITY("IssuingAuthority"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("PropertyPassCodes")
    PROPERTY_PASS_CODES("PropertyPassCodes"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("SecAccessCodes")
    SEC_ACCESS_CODES("SecAccessCodes"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    SOI("SOI"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    SON("SON"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("PivProcessFlowCode")
    PIV_PROCESS_FLOW_CODE("PivProcessFlowCode"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("EarliestCardIssueDate")
    EARLIEST_CARD_ISSUE_DATE("EarliestCardIssueDate"),

    /**
     * 
     * 						Matches corresponding field in InductionDataType
     * 					
     * 
     */
    @XmlEnumValue("AlternateUID")
    ALTERNATE_UID("AlternateUID");
    private final String value;

    SyncApplicantDataFieldsEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static SyncApplicantDataFieldsEnumType fromValue(String v) {
        for (SyncApplicantDataFieldsEnumType c: SyncApplicantDataFieldsEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
