//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This type defines the data returned for each slice 
 *         		processed by the SyncGetApplicantInfoHashRequest.
 *         	
 * 
 * <p>Java class for SyncApplicantInfoHashType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SyncApplicantInfoHashType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PersonIdRange" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdRangeType"/&gt;
 *         &lt;element name="NumberFound" type="{http://www.w3.org/2001/XMLSchema}integer"/&gt;
 *         &lt;element name="PersonIdHash" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="256"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="PersonDataHashHash" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="256"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SyncApplicantInfoHashType", propOrder = {
    "personIdRange",
    "numberFound",
    "personIdHash",
    "personDataHashHash"
})
public class SyncApplicantInfoHashType {

    @XmlElement(name = "PersonIdRange", required = true)
    protected PersonIdRangeType personIdRange;
    @XmlElement(name = "NumberFound", required = true)
    protected BigInteger numberFound;
    @XmlElement(name = "PersonIdHash")
    protected String personIdHash;
    @XmlElement(name = "PersonDataHashHash")
    protected String personDataHashHash;

    /**
     * Gets the value of the personIdRange property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdRangeType }
     *     
     */
    public PersonIdRangeType getPersonIdRange() {
        return personIdRange;
    }

    /**
     * Sets the value of the personIdRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdRangeType }
     *     
     */
    public void setPersonIdRange(PersonIdRangeType value) {
        this.personIdRange = value;
    }

    /**
     * Gets the value of the numberFound property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNumberFound() {
        return numberFound;
    }

    /**
     * Sets the value of the numberFound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNumberFound(BigInteger value) {
        this.numberFound = value;
    }

    /**
     * Gets the value of the personIdHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonIdHash() {
        return personIdHash;
    }

    /**
     * Sets the value of the personIdHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonIdHash(String value) {
        this.personIdHash = value;
    }

    /**
     * Gets the value of the personDataHashHash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonDataHashHash() {
        return personDataHashHash;
    }

    /**
     * Sets the value of the personDataHashHash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonDataHashHash(String value) {
        this.personDataHashHash = value;
    }

}
