//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.03 at 10:07:04 PM EDT 
//


package gov.hhs.induction.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         		This type defines the data returned for each Applicant 
 *         		processed by the SyncGetApplicantDataHashRequest.
 *         	
 * 
 * <p>Java class for SyncApplicantDataHashType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SyncApplicantDataHashType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PI" type="{http://hspd12.hhs.gov/federated/enrollment/v1}PersonIdType"/&gt;
 *         &lt;element name="PersonIdFound" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="Hash" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="256"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SyncApplicantDataHashType", propOrder = {
    "pi",
    "personIdFound",
    "hash"
})
public class SyncApplicantDataHashType {

    @XmlElement(name = "PI", required = true)
    protected String pi;
    @XmlElement(name = "PersonIdFound")
    protected boolean personIdFound;
    @XmlElement(name = "Hash")
    protected String hash;

    /**
     * Gets the value of the pi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPI() {
        return pi;
    }

    /**
     * Sets the value of the pi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPI(String value) {
        this.pi = value;
    }

    /**
     * Gets the value of the personIdFound property.
     * 
     */
    public boolean isPersonIdFound() {
        return personIdFound;
    }

    /**
     * Sets the value of the personIdFound property.
     * 
     */
    public void setPersonIdFound(boolean value) {
        this.personIdFound = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

}
