SET DEFINE OFF;

ALTER TABLE CHR_EMPLOYEE_INFO
ADD
(
  DATE_JOB_REQ_APPROVED DATE,
  CAPHR_COMMENTS  VARCHAR2(4000),
  CAN_NUMBER  VARCHAR2(30)
);

CREATE TABLE HHS_WHRSC_HR.CHR_PROCESSED_JOBS
(
JOB_ID NUMBER(15,0) NOT NULL,
EFFDT DATE,
DATE_PROCESSED_IN_CAPHR DATE NOT NULL
);


CREATE TABLE HHS_WHRSC_HR.CHR_EMPLOYEE
(
EMPID VARCHAR2(11) NOT NULL,
FIRST_NAME VARCHAR2(30),
LAST_NAME VARCHAR2(30)
);
