

--=============================================================================
-- Grant privileges on objects under WHRSC schema to roles
-------------------------------------------------------------------------------


-- privilege for HHS_WHRSC_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.ERROR_LOG TO HHS_WHRSC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.TBL_FORM_DTL TO HHS_WHRSC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.TBL_FORM_DTL_AUDIT TO HHS_WHRSC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.OCCUPATIONAL_SERIES TO HHS_WHRSC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.TYPE_VALUES TO HHS_WHRSC_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_WHRSC_HR.RDR_APPROVAL TO HHS_WHRSC_HR_RW_ROLE;



GRANT EXECUTE ON HHS_WHRSC_HR.SP_ERROR_LOG TO HHS_WHRSC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_PV_DETERMINE TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_PV_RECRUITMENT TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_PV_APPOINTMENT TO HHS_WHRSC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_DETERMINE_TABLE TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_CERTIFICATE TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_RECRUITMENT_PROCESS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_APPOINTMENT_PROCESS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_MULTI_SELECT TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_MULTI_SELECT_RATER TO HHS_WHRSC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_FORM_DATA TO HHS_WHRSC_HR_RW_ROLE;
