----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_INTG_DATA TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_APPLICANT_NOTIFICTNS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_CERTIFICATE_LOCATION TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_CERTIFICATES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_NEW_HIRE_FORMS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_NEW_HIRE_ONBRDNG_DOC TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_NEW_HIRE_TASKS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_NEW_HIRE_VACNCY_REQ TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_NEW_HIRES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_PERMISSION_PROFILES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_REQUEST_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_REQUEST_RATING_COMB TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_REQUEST_VACNCY_COMB TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_REQUESTS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_VACANCY TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_VACANCY_ELIGIBILITIS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_VACANCY_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_VAC_MISSN_CRITCL_OCC TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_UPDATE_VACANCY_RATING_COMB TO HHS_WHRSC_HR_RW_ROLE;
