 /*
DROP TABLE ANNOUNCEMENT;
DROP TABLE APP_DOCUMENTS;
DROP TABLE APPLICANT_RATING;
DROP TABLE APPOINTMENT;
DROP TABLE APPROVER_INFO;
DROP TABLE AUTO_EMAIL_LOG;
DROP TABLE BRANCHES;
DROP TABLE CALENDAR;
DROP TABLE CAREER_CHANGE;	
DROP TABLE CERTIFICATE;	
DROP TABLE CHR_EMP_RETENTION_INFO;
DROP TABLE CHR_EMPLOYEE_INFO;
DROP TABLE CHR_PCA_INFO;
DROP TABLE CHR_PERFORMANCE_INFO;
DROP TABLE CHR_PROBATION;
DROP TABLE CHR_WGI;
DROP TABLE CNTRY_SUBD_CODES_LOOKUP;
DROP TABLE COUNTRY_CODES_LOOKUP;
DROP TABLE FORMS_FIELDS;
DROP TABLE GEO_LOCATION_CODES;
DROP TABLE IC_REQUEST_INFO;
DROP TABLE IMAGES;
DROP TABLE MAIN;
DROP TABLE NED_EMP_ID;
DROP TABLE NEDTRACKING;
DROP TABLE NEW_POSITION;
DROP TABLE ORGS;
DROP TABLE ORIENTATION;
DROP TABLE PERSON_INFO;
DROP TABLE PROCESS_VALUE_LOOKUP;
DROP TABLE RECRUITMENT;
DROP TABLE RECRUITMENT_INFO;
DROP TABLE SPA_PROCESSING;
DROP TABLE STEM_LOOKUP;
DROP TABLE T42;
DROP TABLE T42_PROF_DESIGNATION_LOOKUP;
DROP TABLE T42_REQUEST;
DROP TABLE USRSESSION;	
DROP SEQUENCE DOC_NUM_SEQ;
DROP TABLE RDR_ATTACH;
DROP TABLE RECRUITMENT_ACTION_STATUS;
DROP TABLE RECRUITMENT_ACTION_HISTORY;
*/
--------------------------------------------------------
--  DDL for Table ANNOUNCEMENT
--------------------------------------------------------	
	CREATE TABLE ANNOUNCEMENT
	(REPL_ID							NUMBER(10),
	 TRANSACTION_ID				NUMBER(10),
	 ANN_NUMBER						VARCHAR2(40),
	 ANN_TYPE						VARCHAR2(50),
	 RECRUITMENT_TYPE				VARCHAR2(50),
	 DATE_SENT_TO_DEU				DATE,
	 DATE_QUAL_REVIEW_COMP		DATE,
	 DATE_ANN_POSTED				DATE,
	 DATE_ANN_OPENED				DATE,
	 DATE_ANN_CLOSED				DATE,
	 DATE_ANN_CANCELLED			DATE,
	 OPEN_CONTINUOUS_ANN			VARCHAR2(3),
	 SEQUENCE						NUMBER(10),
	 VIN								VARCHAR2(40),
	 DATE_ANN_APPROVED_BY_DEU	DATE,
	 DE_HR_SPECIALIST				VARCHAR2(100), 
	DE_HR_SPECIALIST_ID				VARCHAR2(10), 
	DE_QUALITY_REVIEWER			VARCHAR2(100), 
	DE_QUALITY_REVIEWER_ID			VARCHAR2(10), 
	QUALITY_REVIEWER				VARCHAR2(100), 
	QUALITY_REVIEWER_ID			VARCHAR2(10), 
	CASE_RETURNED_COMMENTS		CLOB, 
	SELECTIVE_PLACEMNT_FCTR_CMNTS	CLOB, 
	CASE_EXAMINING_REGISTER		VARCHAR2(3),
	DIRECT_HIRE					VARCHAR2(3)
	);


--------------------------------------------------------
--  DDL for Table APP_DOCUMENTS
--------------------------------------------------------	
	CREATE TABLE APP_DOCUMENTS
	(ROW_ID													NUMBER(10),
	 TRANSACTION_ID										NUMBER(10),
	 VACANCYID												NUMBER(10),
	 DATE_ANN_CLOSED										DATE,
	 ANN_TYPE												VARCHAR2(50),
	 ANN_NUMBER												VARCHAR2(40),
	 DT_ANN_CLOSE_TO_DT_DOC_SUBMIT	            NUMBER(10),
	 APPLICATIONID											NUMBER(10),
	 LASTNAME												VARCHAR2(50),
	 FIRSTNAME												VARCHAR2(50),
	 DOCUMENT_TYPE											VARCHAR2(100),
	 DATEVALUE												DATE,
	 XMLFILENAME											NCHAR(150),
	 LOG_DATE_APP_JOB										DATE
	);



--------------------------------------------------------
--  DDL for Table APPLICANT_RATING
--------------------------------------------------------	
	CREATE TABLE APPLICANT_RATING
	(REPL_ID								NUMBER(10),
	 TRANSACTION_ID					NUMBER(10),
	 ANN_NUMBER							VARCHAR2(40),
	 EVALUATION_METHOD				VARCHAR2(20),
	 NUM_APPS_RECD						VARCHAR2(10),
	 NUM_QUAL_APPS_RECD				VARCHAR2(10),
	 NUM_REFERRED_APPLICANTS		VARCHAR2(10),
	 DATE_MIN_QUALS_COMPLETED		DATE,
	 DATE_APPS_NOTIFIED_QUAL_ELIG	DATE,
	 DATE_APPS_NOTIFIED_REFERRAL	DATE,
	 DATE_APPS_TO_SME_QRB			DATE,
	 DATE_APPS_RECD_SME_QRB			DATE,
	 RATER								VARCHAR2(1000),
	 SEQUENCE							NUMBER(10)
	);


--------------------------------------------------------
--  DDL for Table APPOINTMENT
--------------------------------------------------------	
	CREATE TABLE APPOINTMENT
	(TRANSACTION_ID								NUMBER(10),
	 APPOINTMENT_TYPE								VARCHAR2(50),
	 JOB_OFFER_MADE								VARCHAR2(3),
	 TENTATIVE_JOB_OFFER_DATE					DATE,
	 TENTATIVE_JOB_OFFER_RSPNS_DT		      DATE,
	 JOB_OFFER_DATE								DATE,
	 JOB_OFFER_RESPONSE_DATE					DATE,
	 JOB_OFFER_RESPONSE							VARCHAR2(25),
	 JOB_OFFER_DECLINE_REASON					VARCHAR2(75),
	 DT_SECURITY_INVESTIG_INITIATED	      DATE,
	 TYPE_PREFERENCE								VARCHAR2(40),
	 PREFERENCE_ELIG								VARCHAR2(3),
	 NATURE_ACTION_CODE							VARCHAR2(75),
	 NATURE_ACTION_DESCRIPTION					VARCHAR2(75),
	 TYPE_SELECTION								VARCHAR2(30),
	 IS_REEMPLOYED_ANNUITANT					VARCHAR2(50),
	 PRIORITY_PLACEMENT							VARCHAR2(50),
	 SHARED_CERT									VARCHAR2(3),
	 ADDITIONAL_SELECTION_FROM_CERT			VARCHAR2(3),
	 HIRING_FLEX_TYPE								VARCHAR2(75),
	 HIRING_FLEX_TYPE_OTHER						VARCHAR2(50),
	 HIRING_FLEX_USED								VARCHAR2(3),
	 EOD_DATE										DATE,
	 EDUCATIONAL_DOCS_RCVD_DATE				DATE,
	 FIC_DIS_APPROVAL_DATE						DATE,
	 VISA_EAD_EFFECTIVE_DATE					DATE,
	 VISA_EAD_EXPIRATION_DATE					DATE,
	 VISA_EAD_TYPE									VARCHAR2(50),
	 IS_RELEASE_DATE_REQUESTED					VARCHAR2(3),
	 DATE_RELEASE_REQUESTED						DATE,
	 APPROVED_RELEASE_DATE						DATE,
	 LEGISLATIVE_INITIATIVE_USED				VARCHAR2(50),
	 ADDITIONAL_APPROVAL_REQ					VARCHAR2(3),
	 DATE_PKG_SENT_FOR_ADDL_APPR				DATE,
	 DATE_APPR_DEC_RECVD_HR						DATE,
	 RDR_PD_NUMBER						VARCHAR2(50),
	 RDR_PD_USED								VARCHAR2(3),
	 RELATIONSHIP_TO_RECRUIT_ACTION		   VARCHAR2(50),
	 DEU_SELECTION_APRVR							VARCHAR2(50),
	 DEU_SELECTION_APRVR_ID						VARCHAR2(10),
	 DATE_TO_DEU_FOR_DECISION					DATE,
	 DEU_SELECTION_DCSN							VARCHAR2(20),
	 DEU_SELECTION_DCSN_DATE					DATE,
	 DEU_SELECTION_DCSN_CMNTS					CLOB,
	 DEU_SELECTION_ADDL_INFO_NEEDED			CLOB,
	 IS_PATHWAY_AGREE_COMP						VARCHAR2(3),
	 EXP_DATE_OF_PROG_COMP						DATE,
	 IS_NEW_OF306_REQUIRED						VARCHAR2(3),
	 DATE_OF306_ASSIGNED							DATE,
	 CLEARANCE_LEVEL_REQUIRED					VARCHAR2(30),
	 DATE_DPSAC_NOTIFICATION_RCVD				DATE,
	 DATE_SENT_FOR_OF306_REVIEW				DATE,
	 IS_TEMP_FED_EMP_ID_ASSIGNED				VARCHAR2(3),
	 WORK_PERMIT_REQUIRED						VARCHAR2(3),
	 DATE_WORK_PERMIT_RECEIVED					DATE,
	 DATE_PREP_NEW_HIRE_EMAIL_SENT			DATE,
	 DPSAC_REVIEW_DISPOSITION					VARCHAR2(40),
	 FIRST_APPOINTMENT							VARCHAR2(3),
	 REAPPOINTMENT_TYPE							VARCHAR2(70),
	 SHARED_SELECTION							VARCHAR2(50),
	 ADDITIONAL_APPROVAL_COMMENT			CLOB,
	 DT_OFFICIAL_JOB_OFFER						DATE,
	OFFICIAL_JOB_OFFER_RESP_DT					DATE,
	OF306_ASSIGNED_ONBOARD_MGR				VARCHAR2(3),
	MEDICAL_SPECIALITY					VARCHAR2(1000),
	APPOINTEE_REFERRED_BY				VARCHAR2(1000),
	PAY_TYPE VARCHAR2(30), 
	DATE_ARP_SENT_FOR_APPROVAL DATE, 
	DATE_ARP_APPROVED DATE, 
	STEP_ASSIGNED VARCHAR2(30), 
	DT_HPR_AUTHORIZED_BY_CUSTOMER DATE, 
	MAXIMUM_PAYABLE_RATE NUMBER(10,0), 
	ARP_JUSTIFICATION VARCHAR2(1000), 
	ARP_STEP_DETERMINATION VARCHAR2(1000)
	);

--------------------------------------------------------
--  DDL for Table APPROVER_INFO
--------------------------------------------------------	
	CREATE TABLE APPROVER_INFO
	(REPL_ID								NUMBER(10),
	 TRANSACTION_ID					NUMBER(10),
	 NAME									VARCHAR2(50),
	 APPROVER_ID						VARCHAR2(10),
	 ASSIGNED_NAME						VARCHAR2(50),
	 ASSIGNED_APPROVER_ID			VARCHAR2(10),
	 TYPE									VARCHAR2(30),
	 ACTION_DISPOSITION				VARCHAR2(30),
	 RECEIVED_DATE						DATE,
	 IS_PACKAGE_COMPLETE				VARCHAR2(5),
	 MISSING_DOCS						VARCHAR2(500),
	 MISSING_DOCS_EMAIL_SENT_DATE	DATE,
	 MISSING_DOCS_RECEIPT_DATE		DATE,
	 COMMENTS							VARCHAR2(3000)
	);

--------------------------------------------------------
--  DDL for Table AUTO_EMAIL_LOG
--------------------------------------------------------	
	CREATE TABLE AUTO_EMAIL_LOG
	(RECORD_ID				NUMBER(10),
	 EMAIL_SENT_DATE		DATE,
	 FROM_EMAIL_ADDRESS	VARCHAR2(500),
	 TO_EMAIL_ADDRESS		VARCHAR2(500),
	 SUBJECT					VARCHAR2(500),
	 BODY						CLOB,
	 OFFICE					VARCHAR2(50),
	 SLA						VARCHAR2(500),
	 TRANSACTION_ID		VARCHAR2(50),
	 CERT_NUMBER			VARCHAR2(50),
	 ANN_NUMBER				VARCHAR2(500),
	 CERT_SEQ				NUMBER(10),
	 ANN_SEQ					NUMBER(10),
	 DOCUMENT_TYPE			VARCHAR2(50),
	 DATEVALUE				VARCHAR2(50)
	);

--------------------------------------------------------
--  DDL for Table BRANCHES
--------------------------------------------------------	
	CREATE TABLE BRANCHES
	(REPL_ID				NUMBER(10),
	 ID					NUMBER(10),
	 BRANCH				VARCHAR2(50),
	 IC					VARCHAR2(50),
	 EFF_START_DATE	DATE,
	 EFF_END_DATE		DATE,
	 CURRENT_BRANCH	VARCHAR2(10),
	 OLD_BRANCH			VARCHAR2(10)
	);

--------------------------------------------------------
--  DDL for Table CALENDAR
--------------------------------------------------------	
	CREATE TABLE CALENDAR
	(CALDATE		DATE,
	 WORKINGDAY	CHAR(1)
	);

--------------------------------------------------------
--  DDL for Table CAREER_CHANGE
--------------------------------------------------------	
	CREATE TABLE CAREER_CHANGE
	(TRANSACTION_ID			NUMBER(10),
	 TYPE_CAREER_CHANGE		VARCHAR2(50),
	 CAREER_CHANGE_REASON	VARCHAR2(50),
	 OTHER_REASON				VARCHAR2(1000),
	 NTE_DATE					DATE,
	 CC_EOD_DATE				DATE,
	 DETAIL_LOCATION			VARCHAR2(50),
	 UNCLASSIFIED_DUTIES		VARCHAR2(3),
	 GAINING_AGENCY			VARCHAR2(50),
	 GAINING_OPDIV				VARCHAR2(10),
	 GAINING_IC					VARCHAR2(50),
	 EXTENSION_TYPE			VARCHAR2(25),
	 REL_APPT_NO				VARCHAR2(10),
	 REL_DETAIL_NO				VARCHAR2(10)
	);

--------------------------------------------------------
--  DDL for Table CERTIFICATE
--------------------------------------------------------	
	CREATE TABLE CERTIFICATE
	(REPL_ID											NUMBER(10),
	 TRANSACTION_ID								NUMBER(10),
	 ANN_NUMBER										VARCHAR2(40),
	 CERT_ISSUED									VARCHAR2(3),
	 CERT_TYPE										VARCHAR2(20),
	 CERT_NUMBER									VARCHAR2(40),
	 DATE_CERT_ISSUED								DATE,
	 DATE_CERT_TO_SO								DATE,
	 DATE_CERT_EXPIRES							DATE,
	 CERT_EXTENDED									VARCHAR2(3),
	 DATE_NEW_CERT_EXPIRES						DATE,
	 SUPPLEMENT_ISSUED							VARCHAR2(3),
	 DATE_SUPPLEMENT_ISSUED						DATE,
	 AMENDED_CERT_ISSUED							VARCHAR2(3),
	 DATE_AMENDED_CERT_ISSUED					DATE,
	 PREF_ELIG_WITHIN_REACH						VARCHAR2(3),
	 CERT_USED										VARCHAR2(3),
	 CERT_RET_UNUSED_REASON						VARCHAR2(70),
	 SELECTION_MADE								VARCHAR2(3),
	 ACTION_TAKEN									VARCHAR2(20),
	 DATE_OF_HIRING_DECISION					DATE,
	 DATE_HIRING_DEC_RECD_IN_HR				DATE,
	 DATE_FINAL_APP_STATUS_SET					DATE,
	 SEQUENCE										NUMBER(10),
	 DATE_TO_DEU_FOR_CERT_ISSUANCE			DATE,
	 DATE_INTERNAL_REVIEW_COMPLETED			DATE,
	 DATE_10PT_FILE_CHECKED						DATE,
	 DT_CERT_RTN_TO_DEU_FNL_AUDIT	         DATE,
	 DATE_AUDIT_COMPLETED						DATE,
	 CERT_RET_UNUSED_REASON_OTHER				VARCHAR2(50)
	);

--------------------------------------------------------
--  DDL for Table CHR_EMP_RETENTION_INFO
--------------------------------------------------------	
CREATE TABLE CHR_EMP_RETENTION_INFO
(  
   ID	      VARCHAR2(10),
   NAME	   VARCHAR2(100),
   DEPT_ID  VARCHAR2(20),
   NTE_DATE	DATE
);

--------------------------------------------------------
--  DDL for Table CHR_EMPLOYEE_INFO
--------------------------------------------------------	
CREATE TABLE CHR_EMPLOYEE_INFO
(
   ID	               VARCHAR2(30),
   DEPT_ID	         VARCHAR2(10),
   NAME	            VARCHAR2(100),
   JOB_TITLE         VARCHAR2(80),
   PAY_PLAN	         VARCHAR2(10),
   OCC_SERIES	      VARCHAR2(30),
   GRADE	            VARCHAR2(30),
   STEP	            VARCHAR2(10),
   SALARY	         VARCHAR2(50),
   ANNUAL_RT	      VARCHAR2(50),
   PAY_BASIS	      VARCHAR2(30),
   PRD	            VARCHAR2(10),
   VETERANS_PREF	   VARCHAR2(30),
   SCD_TSP	         DATE,
   TSP_STATUS	      VARCHAR2(10),
   PROBATION_DATE	   DATE,
   SERVICE_DT	      DATE,
   TENURE	         VARCHAR2(10),
   START_DATE	      DATE,
   NTE_DATE	         DATE,
   INCR_DT	         DATE,
   EMPLOYMENT_NTE_DT	DATE,
   POSN_OCCUPIED	   VARCHAR2(10),
   REPORTS_TO	      VARCHAR2(30),
   JOB_SENSITIVITY	VARCHAR2(10),
   FLSA_STATUS	      VARCHAR2(10),
   COMP_LEVEL	      VARCHAR2(10),
   BARG_UNIT	      VARCHAR2(10),
   COMBO_CODE	      VARCHAR2(30),
   REG_TEMP	         VARCHAR2(10),
   FULL_PART	      VARCHAR2(10),
   JOB_CODE	         VARCHAR2(30),
   MGR_LEVEL	      VARCHAR2(10),
   STD_HRS_WK	      VARCHAR2(10),
   FIRST_NAME	      VARCHAR2(50),
   MIDDLE	         VARCHAR2(50),
   LAST_NAME	      VARCHAR2(50),
   FLSA_STATUS_2	   VARCHAR2(10),
   POSITION	         VARCHAR2(30),
   COMP_RATE	      VARCHAR2(50),
   LOC_ADJUST	      VARCHAR2(50),
   MIL_STATUS	      VARCHAR2(10),
   COMPONENT	      VARCHAR2(10),
   SEP_STATUS	      VARCHAR2(10),
   MIL_GRADE	      VARCHAR2(10),
   MIL_START_DATE	   DATE,
   MIL_END_DATE	   DATE,
   RESRVE_CAT	      VARCHAR2(10),
   CRED_MILTY	      VARCHAR2(10),
   SVC_PAY_CTR	      VARCHAR2(10),
   SVCE_VERF	      VARCHAR2(10),
   PREF_RIF	         VARCHAR2(10),
   DISAB_VET	      VARCHAR2(10),
   TYPE_APPT	      VARCHAR2(10),
   LOCATION	         VARCHAR2(30),
   DESCR	            VARCHAR2(30),
   POI	            VARCHAR2(10),
   DATE_ADDED	      DATE,
   IC	               VARCHAR2(50)
);

ALTER TABLE CHR_EMPLOYEE_INFO 
ADD (PROCESSED VARCHAR2(20) );

--------------------------------------------------------
--  DDL for Table CHR_PCA_INFO
--------------------------------------------------------	
CREATE TABLE CHR_PCA_INFO
(
   REPL_ID	NUMBER(10),
   ID	      VARCHAR2(30),
   NAME	   VARCHAR2(100),
   DEPT_ID	VARCHAR2(20),
   EFF_DATE	DATE,
   NTE_DATE	DATE
);

--------------------------------------------------------
--  DDL for Table CHR_PERFORMANCE_INFO
--------------------------------------------------------	
CREATE TABLE CHR_PERFORMANCE_INFO
(
   ID	                     VARCHAR2(10),
   DEPT_ID	               VARCHAR2(20),
   DEPT_SET_ID	            VARCHAR2(20),
   UNIT	                  VARCHAR2(20),
   BARG_UNIT	            VARCHAR2(10),
   NAME	                  VARCHAR2(100),
   EMPL_RCD_NUM	         NUMBER(10),
   EFF_DATE	               DATE,
   REVIEW_PERIOD_FROM	   DATE,
   REVIEW_PERIOD_TO	      DATE,
   REVW_TYPE	            VARCHAR2(50),
   RATING	               VARCHAR2(10),
   SCALE 	               VARCHAR2(10),
   NEXT_REVW	            VARCHAR2(30),
   POSITION	               VARCHAR2(30),
   PAY_PLAN	               VARCHAR2(10),
   POSITION_DESCRIPTION	   VARCHAR2(80),
   CURRENT_EMPLOYEE_STATUS	VARCHAR2(40),
   DATE_ADDED	            DATE
);

--------------------------------------------------------
--  DDL for Table CHR_PROBATION
--------------------------------------------------------	
CREATE TABLE CHR_PROBATION
(
   ID	            VARCHAR2(10),
   DEPT_ID	      VARCHAR2(20),
   NAME	         VARCHAR2(100),
   JOB_CODE	      VARCHAR2(30),
   PROBATION_DATE	DATE,
   SES_PRB_DT	   DATE,
   S_M_PRB_DT	   DATE,
   POSITION	      VARCHAR2(30),
   DESCR	         VARCHAR2(60),
   UNIT	         VARCHAR2(10),
   DATE_ADDED	   DATE
);


--------------------------------------------------------
--  DDL for Table CHR_WGI
--------------------------------------------------------	
CREATE TABLE CHR_WGI
(
   DEPT_ID	      VARCHAR2(20),
   NAME	         VARCHAR2(100),
   GRADE	         VARCHAR2(10),
   STEP	         VARCHAR2(10),
   WGI_DUE_DATE	DATE,
   WGI_STATUS	   VARCHAR2(10),
   PAY_PLAN	      VARCHAR2(10),
   DATE_ADDED	   DATE
);

--------------------------------------------------------
--  DDL for Table CNTRY_SUBD_CODES_LOOKUP
--------------------------------------------------------	
	CREATE TABLE CNTRY_SUBD_CODES_LOOKUP
	(REPL_ID				NUMBER(10),
	 DATE_GENERATED	DATE,
	 ID					NCHAR(255),
	 CODE					NCHAR(255),
	 VALUE				NCHAR(255),
	 LAST_MODIFIED		NCHAR(255),
	 IS_DISABLED		NCHAR(255),
	 PARENT_CODE		NCHAR(255)
	);

--------------------------------------------------------
--  DDL for Table COUNTRY_CODES_LOOKUP
--------------------------------------------------------	
	CREATE TABLE COUNTRY_CODES_LOOKUP
	(REPL_ID				NUMBER(10),
	 DATE_GENERATED	DATE,
	 ID					NCHAR(255),
	 CODE					NCHAR(255),
	 VALUE				NCHAR(255),
	 LAST_MODIFIED		NCHAR(255),
	 IS_DISABLED		NCHAR(255)
	);

--------------------------------------------------------
--  DDL for Table FORMS_FIELDS
--------------------------------------------------------	
	CREATE TABLE FORMS_FIELDS
	(REPL_ID				NUMBER(10),
	 TRANSACTION_ID	NUMBER(10),
	 FORM_NAME			VARCHAR2(50),
	 FIELD_NAME			VARCHAR2(100),
	 VALUE				VARCHAR2(100),
	 SEQUENCE			NUMBER(10),
	 ANN_NUMBER		VARCHAR2(40)
	);

--------------------------------------------------------
--  DDL for Table GEO_LOCATION_CODES
--------------------------------------------------------	
	CREATE TABLE GEO_LOCATION_CODES
	(DATE_GENERATED		DATE,
	 ID						NCHAR(255),
	 CODE						NCHAR(255),
	 CITY						NCHAR(255),
	 US_COUNTY				NCHAR(255),
	 COUNTRY_SUBDIVISION	NCHAR(255),
	 COUNTRY					NCHAR(255),
	 LAST_MODIFIED			NCHAR(255),
	 IS_DISABLED			NCHAR(255)
	);

--------------------------------------------------------
--  DDL for Table IC_REQUEST_INFO
--------------------------------------------------------	
	CREATE TABLE IC_REQUEST_INFO
	(REPL_ID										NUMBER(10),
	 TRANSACTION_ID							NUMBER(10),
	 CASE_PREPARER_FIRST_NAME				VARCHAR2(30),
	 CASE_PREPARER_LAST_NAME				VARCHAR2(30),
	 CASE_PREPARER_EMAIL						VARCHAR2(50),
	 CASE_PREPARER_PHONE_NUMBER			VARCHAR2(30),
	 CASE_PREPARER_BADGE_ID					VARCHAR2(20),
	 IC_CONTACT_FIRST_NAME					VARCHAR2(30),
	 IC_CONTACT_LAST_NAME					VARCHAR2(30),
	 IC_CONTACT_EMAIL							VARCHAR2(250),
	 IC_CONTACT_PHONE_NUMBER				VARCHAR2(30),
	 IC_EXEC_OFFICER_FIRST_NAME			VARCHAR2(30),
	 IC_EXEC_OFFICER_LAST_NAME				VARCHAR2(30),
	 IC_EXEC_OFFICER_EMAIL					VARCHAR2(50),
	 IC_EXEC_OFFICER_PHONE_NUMBER			VARCHAR2(30),
	 IC_DIR_FIRST_NAME						VARCHAR2(30),
	 IC_DIR_LAST_NAME							VARCHAR2(30),
	 IC_DIR_EMAIL								VARCHAR2(50),
	 IC_DIR_PHONE_NUMBER						VARCHAR2(30),
	 CASE_PREPARER_TITLE						VARCHAR2(50),
	 FTE_LIAISON_FIRST_NAME					VARCHAR2(30),
	 FTE_LIAISON_LAST_NAME					VARCHAR2(30),
	 FTE_LIAISON_EMAIL						VARCHAR2(50),
	 PROGRAM_MGR_FIRST_NAME					VARCHAR2(30),
	 PROGRAM_MGR_LAST_NAME					VARCHAR2(30),
	 PROGRAM_MGR_EMAIL						VARCHAR2(50),
	 SUPERVISOR_FIRST_NAME					VARCHAR2(30),
	 SUPERVISOR_LAST_NAME					VARCHAR2(30),
	 SUPERVISOR_EMAIL							VARCHAR2(50),
	 AO_NAME										VARCHAR2(60),
	 AO_ID										VARCHAR2(50),
	 IC_COMMENTS								VARCHAR2(3000),
	 DATE_SENT_TO_HR							DATE,
	 SUPERVISOR_ID								VARCHAR2(20),
	 SUPERVISOR_TITLE							VARCHAR2(100),
	 SUPERVISOR_POSITION_NUMBER			VARCHAR2(20),
	 CASE_PREPARER_ID							VARCHAR2(10),
	 IC_CONTACT_BADGE_ID						VARCHAR2(20),
	 SUPERVISOR_SUPVRY_STATUS		      VARCHAR2(10),
	 SUPERVISOR_SUPVRY_STATUS_DESC	   VARCHAR2(50),
	 IC_APPROVER_FIRST_NAME					VARCHAR2(30),
	 IC_APPROVER_LAST_NAME					VARCHAR2(30),
	 IC_APPROVER_TITLE						VARCHAR2(50),
	 IC_APPROVER_ID							VARCHAR2(20),
	 IC_APPROVAL_DATE							DATE
	);

--------------------------------------------------------
--  DDL for Table IMAGES
--------------------------------------------------------	
	CREATE TABLE IMAGES
	(RYB_ID		NUMBER(10),
	 RYB_CODE	VARCHAR2(50),
	 RYB_IMAGE	LONG RAW
	);

--------------------------------------------------------
--  DDL for Table MAIN
--------------------------------------------------------	
	CREATE TABLE MAIN
	(TRANSACTION_ID					NUMBER(10),
	 ADMIN_CODE							VARCHAR2(20),
	 PRIORITY							VARCHAR2(10),
	 ORG_INITS							VARCHAR2(30),
	 ACTION_TYPE						VARCHAR2(50),
	 DATE_SF52_RECEIVED				DATE,
	 DATE_RECEIVED						DATE,
	 EMPLOYEE_ID						VARCHAR2(20),
	 BADGE_ID							VARCHAR2(10),
	 FIRST_NAME							VARCHAR2(30),
	 MI									VARCHAR2(10),
	 LAST_NAME							VARCHAR2(30),
	 DOB									DATE,
	 EMAIL								VARCHAR2(250),
	 PHONE_NUMBER						VARCHAR2(30),
	 POSITION_NO						VARCHAR2(20),
	 JOB_CODE							VARCHAR2(30),
	 CAN_NO								VARCHAR2(30),
	 TK_NO								VARCHAR2(30),
	 INSTITUTE							VARCHAR2(30),
	 HR_ASSISTANT						VARCHAR2(100),
	 HR_ASSISTANT_ID					VARCHAR2(10),
	 HRA_DATE_INIT						DATE,
	 HRA_DATE_RETURNED				DATE,
	 HR_SPECIALIST						VARCHAR2(100),
	 HR_SPECIALIST_ID					VARCHAR2(10),
	 INTERNAL_OPS_REVIEWER			VARCHAR2(100),
	 INTERNAL_OPS_REVIEWER_ID		VARCHAR2(50),
	 PAY_SPECIALIST					VARCHAR2(100),
	 PAY_SPECIALIST_ID				VARCHAR2(50),
	 HRS_DATE_INIT						DATE,
	 HRS_DATE_RETURNED				DATE,
	 HR_SPA								VARCHAR2(100),
	 HR_SPA_ID							VARCHAR2(10),
	 BRANCH_CHIEF						VARCHAR2(100),
	 BRANCH_CHIEF_ID					VARCHAR2(10),
	 TEAM_LEADER						VARCHAR2(100),
	 TEAM_LEADER_ID					VARCHAR2(10),
	 POSITION_TITLE					VARCHAR2(100),
	 PAY_PLAN							VARCHAR2(100),
	 SERIES								VARCHAR2(30),
	 GRADE								VARCHAR2(30),
	 STEP									VARCHAR2(30),
	 PAY_BAND							VARCHAR2(30),
	 TERCILE								VARCHAR2(30),
	 PAY_CLUSTER						VARCHAR2(30),
	 HRA_CANCEL_DATE					DATE,
	 HRS_CANCEL_DATE					DATE,
	 CREATED_DATE						DATE,
	 MODIFIED_DATE						DATE,
	 PROPOSED_EFF_DATE				DATE,
	 INITIATED_BY						VARCHAR2(250),
	 BASE_SALARY						VARCHAR2(50),
	 TOTAL_SALARY						VARCHAR2(50),
	 STATUS								VARCHAR2(20),
	 STATUS_DATE						DATE,
	 STATUS_USER_ID					VARCHAR2(50),
	 COMMENTS_STATUS					CLOB,
	 INTERNAL_COMMENTS				CLOB,
	 VICE									VARCHAR2(50),
	 DATE_FIRST_ELIGIBLE				DATE,
	 CERTIFICATE_TYPE					VARCHAR2(50),
	 RYB_CODE							VARCHAR2(20),
	 RYB_STATUS							VARCHAR2(50),
	 RYB_DESCRIPTION					VARCHAR2(50),
	 RYB_CHANGE_DATE					DATE,
	 INITIATOR_MEMBERID				VARCHAR2(10),
	 INITIATOR_DEPTID					VARCHAR2(10),
	 PCKG_COMPLETE						VARCHAR2(3),
	 MISSING_DOCS_EMAIL_SENT_DATE	DATE,
	 MISSING_DOCS_RECEIPT_DATE		DATE,
	 DATE_IC_NOTIFIED_OF_OUTCOME	DATE,
	 ASSIGNED_PARTICIPANT_NAME		VARCHAR2(100),
	 ASSIGNED_PARTICPANT_ID			VARCHAR2(10),
	 ASSIGNED_PARTICPANT_TYPE		CHAR(1),
	 MISSING_DOCS						CLOB,
	 RELATED_TRANS_ID					VARCHAR2(20),
	 RELATED_SR_LVL_PAY_TRANS_ID	VARCHAR2(20),
	 JOB_OPENING_ID					VARCHAR2(30),
	 DATE_JOB_OPENING_APPROVED		DATE,
	 GLOBAL_RECRUITMENT				VARCHAR2(3),
	 LATEST_RESPONSE					VARCHAR2(100),
	 SERVICING_TEAM_LEADER			VARCHAR2(100),
	 SERVICING_TEAM_LEADER_ID		VARCHAR2(10),
	 SERVICING_BRANCH					VARCHAR2(3),
	 NFC_ADMIN_CODE					VARCHAR2(20),
	 RELATED_T42_TRANS_ID			VARCHAR2(20),
	 MODIFICATION_TO_JCPN			VARCHAR2(3),
	 RELATED_JCPN_TRANS_ID			VARCHAR2(20),
	 DSSEM								VARCHAR2(3),
	 HR_SENIOR_ADVISOR				VARCHAR2(100),
	HR_SENIOR_ADVISOR_ID				VARCHAR2(10),
	SUBMITTED_PCKG_QLTY				VARCHAR2(10), 
	SUBMITTED_PCKG_QLTY_COMMENTS		 CLOB	
	);

--------------------------------------------------------
--  DDL for Table NED_EMP_ID
--------------------------------------------------------	
	CREATE TABLE NED_EMP_ID
	(NED_ID	NCHAR(255),
	 EMP_ID	NCHAR(255),
	 REPL_ID	NUMBER(10)
	);


--------------------------------------------------------
--  DDL for Table NEDTRACKING
--------------------------------------------------------	
	CREATE TABLE NEDTRACKING
	(NED_ID					NCHAR(255),
	 ORG_CODE				NCHAR(255),
	 FULLNAME				NCHAR(255),
	 FIRST_NAME				NCHAR(255),
	 LAST_NAME				NCHAR(255),
	 EMAIL					NCHAR(255),
	 EMPLOYEE_CAT_TYPE	NCHAR(255),
	 LAST_UPDATED			DATE,
	 REPL_ID					NUMBER(10)
	);

--------------------------------------------------------
--  DDL for Table NEW_POSITION
--------------------------------------------------------	
	CREATE TABLE NEW_POSITION
	(REPL_ID							NUMBER(10),
	 TRANSACTION_ID				NUMBER(10),
	 TYPE								VARCHAR2(50),
	 POSITION_TITLE				VARCHAR2(100),
	 PAY_PLAN						VARCHAR2(100),
	 SERIES							VARCHAR2(30),
	 GRADE							VARCHAR2(30),
	 STEP								VARCHAR2(30),
	 PAY_BAND						VARCHAR2(30),
	 TERCILE							VARCHAR2(30),
	 PAY_CLUSTER					VARCHAR2(30),
	 POSITION_NO					VARCHAR2(20),
	 JOB_CODE						VARCHAR2(30),
	 CAN_NO							VARCHAR2(30),
	 TK_NO							VARCHAR2(30),
	 BASE_SALARY					VARCHAR2(50),
	 TOTAL_SALARY					VARCHAR2(50),
	 PROFESSIONAL_DESIGNATION	VARCHAR2(50),
	 CATEGORY						VARCHAR2(30),
	 ELIGIBLE_FOR_BENEFITS		VARCHAR2(3),
	 RECRUITMENT_AMOUNT			VARCHAR2(50),
	 RETENTION_AMOUNT				VARCHAR2(50),
	 PCA_AMOUNT						VARCHAR2(50),
	 PSP_AMOUNT						VARCHAR2(50),
	 ON_CALL_PAY_AMOUNT			VARCHAR2(50),
	 PERF_BONUS_AMOUNT			VARCHAR2(50),
	 CASH_AWARD_AMOUNT			VARCHAR2(50),
	 DISC_INCREASE_AMOUNT		VARCHAR2(50),
	 POSITION_CATEGORY			VARCHAR2(25),
	 POSITION_LEVEL				VARCHAR2(25),
	 TRANSITIONAL_POS				VARCHAR2(50),
	 POSITION_DESC					VARCHAR2(50),
	 NTE_DATE						DATE,
	 AUTHORITY						VARCHAR2(30),
	 TIME_LIMIT						VARCHAR2(30),
	 TOUR_OF_DUTY					VARCHAR2(30),
	 FULL_PERF_LEVEL				VARCHAR2(50),
	 NATURE_OF_POSITION			VARCHAR2(100),
	 VICE								VARCHAR2(50),
	 DUTY_LOCATION					VARCHAR2(250),
	 SEQUENCE						NUMBER(10),
	 RELATED_ID						NUMBER(10),
	 BASIC_PAY_MIN					NUMBER(11,2),
	 BASIC_PAY_MAX					NUMBER(11,2),
	 START_DATE						DATE,
	 PGY_YEAR						VARCHAR2(10),
	 HOURS_PER_WEEK				VARCHAR2(10),
	 STATEMENT_OF_DUTIES			CLOB,
	 DUTY_LOCATION_CODE			VARCHAR2(20),
	 TELEWORK						VARCHAR2(3),
	 CYBERSECURITY_CODE			VARCHAR2(3),
	 PAY_TIER					VARCHAR2(30)
	);

--------------------------------------------------------
--  DDL for Table ORGS
--------------------------------------------------------	
	CREATE TABLE ORGS
	(ID				NUMBER(10),
	 IC				VARCHAR2(10),
	 ADMIN_CODE		VARCHAR2(50),
	 ADMIN_TITLE	VARCHAR2(120),
	 ORG_INITS		VARCHAR2(50),
	 HR_ASSISTANT	VARCHAR2(50),
	 HR_SPECIALIST	VARCHAR2(50),
	 MANAGER			VARCHAR2(50),
	 HR_SPA			VARCHAR2(50),
	 REASON			VARCHAR2(500),
	 HD_TICKET_NO	NUMBER(10),
	 PROGRAM_TYPE	VARCHAR2(50),
	 STATUS			VARCHAR2(10)
	);


--------------------------------------------------------
--  DDL for Table ORIENTATION
--------------------------------------------------------	
CREATE TABLE ORIENTATION
   (	TRANSACTION_ID							NUMBER(10),
	ORIENTATION								VARCHAR2(20), 
	CSD_ORIENTATION_CONTACT				VARCHAR2(50), 
	ORIENTATION_CONTACT_PHONE_NUM		VARCHAR2(50), 
	ORIENTATION_DATE						DATE, 
	ORIENTATION_LOCATION					 VARCHAR2(100), 
	DUTY_STATION							VARCHAR2(50), 
	HIRE_TYPE								VARCHAR2(50), 
	FINGERPRINTS_REQUIRED					VARCHAR2(10), 
	ATTENDED_ORIENTATION					VARCHAR2(20), 
	REGISTERED_IN_EINDUCTION				VARCHAR2(3), 
	DATE_REG_IN_EINDUCTION					DATE, 
	ORIENTATION_EMAIL_ADDRESS				VARCHAR2(250), 
	DT_OFFICIAL_OFFER_LETTER_SENT			DATE
   );


--------------------------------------------------------
--  DDL for Table PERSON_INFO
--------------------------------------------------------	
	CREATE TABLE PERSON_INFO
	(REPL_ID									NUMBER(10),
	 TRANSACTION_ID						NUMBER(10),
	 EMPLOYEE_ID							VARCHAR2(20),
	 BADGE_ID								VARCHAR2(10),
	 FIRST_NAME								VARCHAR2(30),
	 MI										VARCHAR2(10),
	 LAST_NAME								VARCHAR2(30),
	 DOB										DATE,
	 EMAIL									VARCHAR2(50),
	 PHONE_NUMBER							VARCHAR2(30),
	 DEGREE									VARCHAR2(50),
	 BOARD_CRTFCN							VARCHAR2(50),
	 TYPE										VARCHAR2(30),
	 FILER278								VARCHAR2(3),
	 FLSA_STATUS							VARCHAR2(10),
	 LAST_PERF_RATING						VARCHAR2(3),
	 DATE_OF_LAST_PERF_RATING			DATE,
	 BARGAINING_UNIT						VARCHAR2(50),
	 SUPERVISORY_STATUS					VARCHAR2(3),
	 SUPERVISORY_PROBATION_END_DATE	DATE,
	 NEXT_WGI_ELIG_DATE					DATE,
	 PRIOR_DISCIPLINE						VARCHAR2(3),
	 PROBATION_END_DATE					DATE,
	 ADMIN_CODE								VARCHAR2(20),
	 SES_PROBATION_END_DATE				DATE,
	 CURRENT_EMPLOYEE						VARCHAR2(3),
	 IS_SUPERVISOR							VARCHAR2(3),
	 ON_WORK_VISA							VARCHAR2(3),
	 VISA_TYPE								VARCHAR2(10),
	 FILER450								VARCHAR2(3),
	 CAPHR_EFFECTIVE_DATE					 DATE, 
	CAPHR_PROCESSED_DATE				 DATE
	);


--------------------------------------------------------
--  DDL for Table PROCESS_VALUE_LOOKUP
--------------------------------------------------------	
	CREATE TABLE PROCESS_VALUE_LOOKUP
	(REPL_ID	NUMBER(10),
	 KEY1		VARCHAR2(50),
	 KEY2		VARCHAR2(50),
	 KEY3		VARCHAR2(50),
	 KEY4		VARCHAR2(50),
	 VALUE1	VARCHAR2(50)
	);

--------------------------------------------------------
--  DDL for Table RECRUITMENT
--------------------------------------------------------	
	CREATE TABLE RECRUITMENT
	(TRANSACTION_ID								NUMBER(10),
	 DATE_RECRUITMENT_STARTED					DATE,
	 RECRUITMENT_TYPE								VARCHAR2(50),
	 DATE_PRERECRUIT_MEETING					DATE,
	 DATE_PRERECRUIT_SHEET_SIGNED				DATE,
	 LEGISLATIVE_INIT_SUPPORTED		      VARCHAR2(50),
	 NUM_POSITIONS_TO_BE_ADV					NUMBER(10),
	 IS_NEW_POSITION								VARCHAR2(3),
	 IS_TRANSITIONAL_RECRUIT					VARCHAR2(3),
	 ADVERTISE_JOB									VARCHAR2(3),
	 SHARED_CERT_CONSIDERED						VARCHAR2(3),
	 OTHER_RECRUIT_CONSIDERATIONS		      VARCHAR2(25),
	 PAID_AD											VARCHAR2(3),
	 PAID_AD_APPROVED_DATE						DATE,
	 IS_RELOCATION_EXPENSES_PAID				VARCHAR2(3),
	 INCENTIVES_OFFERED							VARCHAR2(1000),
	 ADDITIONAL_RECRUIT_CHANNELS			   VARCHAR2(1000),
	 PRERECRUIT_COMMENTS							VARCHAR2(3000),
	 NUM_POSITIONS_ADV							NUMBER(10),
	 AREA_OF_CONSIDERATION						VARCHAR2(50),
	 STAFFING_SYSTEM_USED						VARCHAR2(50),
	 MULTIDISCIPLINE_POSITION					VARCHAR2(3),
	 DATE_NEED_VALIDATED							DATE,
	 IS_READVERTISEMENT							VARCHAR2(3),
	 RDR_PD_USED									VARCHAR2(3),
	 RDR_PD_KEY_NUMBER							VARCHAR2(50),
	 DE_HR_SPECIALIST								VARCHAR2(100),
	 DE_HR_SPECIALIST_ID							VARCHAR2(10),
	 DE_QUALITY_REVIEWER							VARCHAR2(100),
	 DE_QUALITY_REVIEWER_ID						VARCHAR2(10),
	 CASE_RETURNED_COMMENTS						CLOB,
	 COMMENTS_ON_QR_PROCESS						CLOB,
	 SELECTIVE_PLACEMNT_FCTR_CMNTS				CLOB,
	 AUDIT_COMMENTS								CLOB,
	 CLEARANCE_LEVEL_REQUIRED					VARCHAR2(30),
	 RELATED_CLASSIFICATION_NUMBER			VARCHAR2(50),
	 CASE_EXAMINING_REGISTER					VARCHAR2(3),
	 ADDITIONAL_COMP_INCENTIVES				VARCHAR2(1000),
	 OTHER_PUBLICATIONS							VARCHAR2(500),
	 DATE_PRT_PLCMT_PGM_CHECKED			 DATE, 
	IS_PRIORITY_PLCMT_CLEARED				 VARCHAR2(3), 
	DATE_10PT_FILE_CHECKED					DATE,
	SUBMITTED_PCKG_QUALITY					 VARCHAR2(20), 
	SUBMITTED_PCKG_QUALITY_CMNTS			CLOB
	);


--------------------------------------------------------
--  DDL for Table RECRUITMENT_INFO
--------------------------------------------------------	
	CREATE TABLE RECRUITMENT_INFO
	(REPL_ID					NUMBER(10),
	 TRANSACTION_ID		NUMBER(10),
	 SEQUENCE				NUMBER(10),
	 RECRUITMENT_NUMBER	NUMBER(10)
	);


--------------------------------------------------------
--  DDL for Table SPA_PROCESSING
--------------------------------------------------------	
	CREATE TABLE SPA_PROCESSING
	(REPL_ID							NUMBER(10),
	 TRANSACTION_ID					NUMBER(10),
	 DATE_SENT_TO_SPA				DATE 
) ;


--------------------------------------------------------
--  DDL for Table STEM_LOOKUP
--------------------------------------------------------	
	CREATE TABLE STEM_LOOKUP
	(REPL_ID			NUMBER(10),
	 SERIES			VARCHAR2(30),
	 DESCRIPTION	VARCHAR2(1000)
	);


--------------------------------------------------------
--  DDL for Table T42
--------------------------------------------------------	
	CREATE TABLE T42
	(TRANSACTION_ID	NUMBER(10),
	 T42_TYPE			VARCHAR2(20),
	 CRS_TYPE			VARCHAR2(50),
	 CRS_REASON			VARCHAR2(50),
	 CRS_CONV_TYPE		VARCHAR2(50),
	 CRS_NTE_DATE		DATE
	);


--------------------------------------------------------
--  DDL for Table T42_PROF_DESIGNATION_LOOKUP
--------------------------------------------------------	
	CREATE TABLE T42_PROF_DESIGNATION_LOOKUP
	(REPL_ID							NUMBER(10),
	 ID								NUMBER(10),
	 CATEGORY						VARCHAR2(200),
	 PROFESSIONAL_DESIGNATION	VARCHAR2(200),
	 AUTHORITY						NCHAR(200),
	 BASIC_PAY_MIN					NUMBER(11,2),
	 BASIC_PAY_MAX					NUMBER(11,2),
	 EXHAUST_REQUIRED				VARCHAR2(50),
	 OIR_OER_APPROVAL				VARCHAR2(50),
	 OGE_278							VARCHAR2(50),
	 OGE_450							VARCHAR2(50)
	);


 --------------------------------------------------------
--  DDL for Table T42_REQUEST
--------------------------------------------------------	
	CREATE TABLE T42_REQUEST
	(TRANSACTION_ID		NUMBER(10),
	 T42_ACTION_TYPE		VARCHAR2(60),
	 NCC_NCCP_REVIEW		VARCHAR2(3),
	 CLOSEOUT_REASON		VARCHAR2(70),
	 CLOSEOUT_COMMENTS	VARCHAR2(1000)
	);


--------------------------------------------------------
--  DDL for Table USRSESSION
--------------------------------------------------------	
	CREATE TABLE USRSESSION
	(REPL_ID		NUMBER(10),
	 LOGINDTIME	DATE,
	 MEMBERID	VARCHAR2(10),
	 LASTNAME	VARCHAR2(50),
	 FIRSTNAME	VARCHAR2(50),
	 USERID		VARCHAR2(50),
	 IPADDR		VARCHAR2(15),
	 LOGINCNT	NUMBER(10),
	 SESSIONKEY	VARCHAR2(100)
	);




--------------------------------------------------------
--  DDL for Sequence DOC_NUM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  DOC_NUM_SEQ  MINVALUE 1000 MAXVALUE 99999999999 INCREMENT BY 1 START WITH 1000 CACHE 20 NOORDER  NOCYCLE ;

/

--------------------------------------------------------
--  DDL for Table RDR_ATTACH
--------------------------------------------------------

  CREATE TABLE RDR_ATTACH 
   (	DOC_NUM NUMBER(10,0), 
	PROCID NUMBER(10,0), 
	RDR_NUM VARCHAR2(10 BYTE), 
	ATTACH_SEQ NUMBER(10,0), 
	ATT_NAME VARCHAR2(100 BYTE), 
	ATT_DT_PROCESSED DATE, 
	ATT_DT_APPROVED DATE, 
	DOC_TYPE VARCHAR2(50 BYTE), 
	DOC_DESC VARCHAR2(100 BYTE), 
	JOB_CODE VARCHAR2(6 BYTE), 
	TEMPLATE VARCHAR2(1 BYTE), 
	RESTRICTIONS VARCHAR2(50 BYTE), 
	GRADE VARCHAR2(100 BYTE), 
	SERIES VARCHAR2(4 BYTE), 
	PROGRAM VARCHAR2(20 BYTE), 
	POSITION_TITLE VARCHAR2(50 BYTE), 
	PAY_PLAN VARCHAR2(2 BYTE), 
	DOC_STATUS VARCHAR2(50 BYTE), 
	FPL VARCHAR2(2 BYTE)
   ); 

--------------------------------------------------------
--  DDL for Index RDR_ATTACH_INDEX1
--------------------------------------------------------

  CREATE INDEX RDR_ATTACH_INDEX1 ON RDR_ATTACH (DOC_NUM) ;

--------------------------------------------------------
--  DDL for Trigger DOC_NUM_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER DOC_NUM_TRG 
BEFORE INSERT ON RDR_ATTACH 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.DOC_NUM IS NULL THEN
      SELECT DOC_NUM_SEQ.NEXTVAL INTO :NEW.DOC_NUM FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;

/
ALTER TRIGGER DOC_NUM_TRG ENABLE;
--------------------------------------------------------
--  Constraints for Table RDR_ATTACH
--------------------------------------------------------

  ALTER TABLE RDR_ATTACH MODIFY (DOC_NUM NOT NULL ENABLE);
 
  ALTER TABLE RDR_ATTACH MODIFY (PROCID NOT NULL ENABLE);


--------------------------------------------------------
--  DDL for Table RECRUITMENT_ACTION_STATUS
--------------------------------------------------------

/*
DROP TABLE RECRUITMENT_ACTION_STATUS;
DROP SEQUENCE RECRUITMENT_ACTION_STATUS_SEQ;
*/

CREATE TABLE RECRUITMENT_ACTION_STATUS 
(ID					NUMBER(20)     NOT NULL, 
TRANSACTION_ID		NUMBER(10), 
REQUEST_NUMBER	VARCHAR2(30), 
POSITION_TITLE		VARCHAR2(100), 
PAY_PLAN			VARCHAR2(100), 
SERIES				VARCHAR2(30), 
GRADE				VARCHAR2(30),
ANN_OPENED			VARCHAR2(1) DEFAULT 'F'
) ;

ALTER TABLE RECRUITMENT_ACTION_STATUS ADD CONSTRAINT RECRUITMENT_ACTION_STATUS_PK PRIMARY KEY (ID);

--DROP INDEX RECRUITMENT_ACTION_STATUS_NK1;
CREATE INDEX RECRUITMENT_ACTION_STATUS_NK1 ON RECRUITMENT_ACTION_STATUS (TRANSACTION_ID);

CREATE SEQUENCE RECRUITMENT_ACTION_STATUS_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

/

CREATE OR REPLACE TRIGGER RECRUITMENT_ACTION_STATUS_BIR
BEFORE INSERT ON RECRUITMENT_ACTION_STATUS
FOR EACH ROW
BEGIN
	SELECT RECRUITMENT_ACTION_STATUS_SEQ.NEXTVAL
	INTO :NEW.ID
	FROM DUAL
	;
END
;

/

--------------------------------------------------------
--  DDL for Table RECRUITMENT_ACTION_HISTORY
--------------------------------------------------------


-- DROP TABLE RECRUITMENT_ACTION_HISTORY;
-- DROP SEQUENCE RECRUITMENT_ACTION_HISTORY_SEQ;


CREATE TABLE RECRUITMENT_ACTION_HISTORY
(
	HISTORYID			NUMBER(20),
	 ID					NUMBER(20),
	TRANSACTION_ID		NUMBER(10),
	ACTION_STATUS		VARCHAR2(50),
	ACTION_CODE		VARCHAR2(20) ,
	DATE_CERTIFIED		DATE,
	HR_SPECIALIST_ID		VARCHAR2(10),
	HR_SPECIALIST		VARCHAR2(100),
	COMMENTS 			VARCHAR2(100)
);

ALTER TABLE RECRUITMENT_ACTION_HISTORY ADD CONSTRAINT RECRUITMENT_ACTION_HISTORY_PK PRIMARY KEY (HISTORYID);

--DROP INDEX RECRUITMENT_ACTION_HISTORY_NK1;
CREATE INDEX RECRUITMENT_ACTION_HISTORY_NK1 ON RECRUITMENT_ACTION_HISTORY (ID);

--DROP INDEX RECRUITMENT_ACTION_HISTORY_NK2;
CREATE INDEX RECRUITMENT_ACTION_HISTORY_NK2 ON RECRUITMENT_ACTION_HISTORY (TRANSACTION_ID);


CREATE SEQUENCE RECRUITMENT_ACTION_HISTORY_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/


CREATE OR REPLACE TRIGGER RECRUITMENT_ACTION_HISTORY_BIR
BEFORE INSERT ON RECRUITMENT_ACTION_HISTORY
FOR EACH ROW
BEGIN
	SELECT RECRUITMENT_ACTION_HISTORY_SEQ.NEXTVAL
	INTO :NEW.HISTORYID
	FROM DUAL;
END;

/