/*
DROP TABLE ERROR_LOG;
DROP TABLE TBL_FORM_DTL;
DROP TABLE TBL_FORM_DTL_AUDIT;
DROP TABLE OCCUPATIONAL_SERIES;
DROP TABLE TYPE_VALUES;
DROP TABLE RDR_APPROVAL;
DROP VIEW VW_WHRSC_RECRUITMENT;
DROP VIEW VW_WHRSC_APPOINTMENT;

DROP SEQUENCE ERROR_LOG_SEQ;
DROP SEQUENCE FORM_DATA_SEQ;
DROP SEQUENCE TBL_FORM_DTL_AUDIT_SEQ;
*/

--=============================================================================
-- Create TABLE and associated objects
--=============================================================================


--------------------------------------------------------
--  DDL for Table ERROR_LOG
--------------------------------------------------------

CREATE TABLE ERROR_LOG
(
	ID                  INTEGER
	, ERROR_CD          INTEGER
	, ERROR_MSG         VARCHAR2(4000)
	, BACKTRACE         CLOB
	, CALLSTACK         CLOB
	, CRT_DT            DATE
	, CRT_USR           VARCHAR2(50)
);

ALTER TABLE ERROR_LOG ADD CONSTRAINT ERROR_LOG_PK PRIMARY KEY (ID);
/



COMMENT ON COLUMN ERROR_LOG.ID IS 'Unique primary key';
COMMENT ON COLUMN ERROR_LOG.ERROR_CD IS 'Error code';
COMMENT ON COLUMN ERROR_LOG.ERROR_MSG IS 'Error message';
COMMENT ON COLUMN ERROR_LOG.BACKTRACE IS 'Error trace';
COMMENT ON COLUMN ERROR_LOG.CALLSTACK IS 'PL/SQL call stack that leads to the error';
COMMENT ON COLUMN ERROR_LOG.CRT_DT IS 'Creation Date';
COMMENT ON COLUMN ERROR_LOG.CRT_USR IS 'Creation User';



CREATE SEQUENCE ERROR_LOG_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

/


CREATE OR REPLACE TRIGGER ERROR_LOG_BIR
BEFORE INSERT ON ERROR_LOG
FOR EACH ROW
BEGIN
	SELECT ERROR_LOG_SEQ.NEXTVAL
	INTO :NEW.ID
	FROM DUAL;
END;

/


create or replace PROCEDURE SP_ERROR_LOG
IS
	PRAGMA AUTONOMOUS_TRANSACTION;
	V_CODE      PLS_INTEGER := SQLCODE;
	V_MSG       VARCHAR2(32767) := SQLERRM;
BEGIN
	INSERT INTO ERROR_LOG
	(
		ERROR_CD
		, ERROR_MSG
		, BACKTRACE
		, CALLSTACK
		, CRT_DT
		, CRT_USR
	)
	VALUES (
		V_CODE
		, V_MSG
		, SYS.DBMS_UTILITY.FORMAT_ERROR_BACKTRACE
		, SYS.DBMS_UTILITY.FORMAT_CALL_STACK
		, SYSDATE
		, USER
	);

	COMMIT;
END;
/
--------------------------------------------------------
--  DDL for Table TBL_FORM_DTL
--------------------------------------------------------

CREATE TABLE TBL_FORM_DTL
(
	ID                      NUMBER(20) NOT NULL
	, PROCID                NUMBER(10)
	, ACTSEQ                NUMBER(10)
	, WITEMSEQ              NUMBER(10)
	, FORM_TYPE             VARCHAR2(50)
	, FIELD_DATA            XMLTYPE
	, CRT_DT                TIMESTAMP
	, CRT_USR               VARCHAR2(50)
	, MOD_DT                TIMESTAMP
	, MOD_USR               VARCHAR2(50)
	,TRANSACTIONID		 NUMBER(10)
);

ALTER TABLE TBL_FORM_DTL ADD CONSTRAINT TBL_FORM_DTL_PK PRIMARY KEY (ID);

--DROP INDEX TBL_FORM_DTL_NK1;
CREATE INDEX TBL_FORM_DTL_NK1 ON TBL_FORM_DTL (PROCID)
;


COMMENT ON COLUMN TBL_FORM_DTL.ID IS 'Unique primary key';
COMMENT ON COLUMN TBL_FORM_DTL.PROCID IS 'Foreign key. Process ID of the related BIZFLOW.PROCS table';
COMMENT ON COLUMN TBL_FORM_DTL.ACTSEQ IS 'Foreign key. Activity Sequence of the related BIZFLOW.ACT table';
COMMENT ON COLUMN TBL_FORM_DTL.WITEMSEQ IS 'Foreign key. Work Item Sequence of the related BIZFLOW.WITEM table';
COMMENT ON COLUMN TBL_FORM_DTL.FORM_TYPE IS 'Form Type.  Indicates what form data is stored in the record';
COMMENT ON COLUMN TBL_FORM_DTL.FIELD_DATA IS 'XML representation of the form data';
COMMENT ON COLUMN TBL_FORM_DTL.CRT_DT IS 'Creation Date';
COMMENT ON COLUMN TBL_FORM_DTL.CRT_USR IS 'Creation User';
COMMENT ON COLUMN TBL_FORM_DTL.MOD_DT IS 'Modification Date';
COMMENT ON COLUMN TBL_FORM_DTL.MOD_USR IS 'Modification User';


CREATE SEQUENCE FORM_DATA_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

/

CREATE OR REPLACE TRIGGER TBL_FORM_DTL_BIR
BEFORE INSERT ON TBL_FORM_DTL
FOR EACH ROW
BEGIN
	SELECT FORM_DATA_SEQ.NEXTVAL
	INTO :NEW.ID
	FROM DUAL
	;
END
;

/





---------------------------------------------------
-- Auditing utility for form data xml table
---------------------------------------------------
--------------------------------------------------------
--  DDL for Table TBL_FORM_DTL_AUDIT
--------------------------------------------------------


-- DROP TABLE TBL_FORM_DTL_AUDIT;
-- DROP SEQUENCE TBL_FORM_DTL_AUDIT_SEQ;


CREATE TABLE TBL_FORM_DTL_AUDIT
(
	AUDITID                 NUMBER(20)

	, ID                    NUMBER(20)
	, PROCID                NUMBER(10)
	, ACTSEQ                NUMBER(10)
	, WITEMSEQ              NUMBER(10)
	, FORM_TYPE             VARCHAR2(50)
	, FIELD_DATA            XMLTYPE
	, CRT_DT                TIMESTAMP
	, CRT_USR               VARCHAR2(50)
	, MOD_DT                TIMESTAMP
	, MOD_USR               VARCHAR2(50)

	, AUDIT_ACTION          VARCHAR2(50)
	, AUDIT_TS				TIMESTAMP
);

ALTER TABLE TBL_FORM_DTL_AUDIT ADD CONSTRAINT TBL_FORM_DTL_AUDIT_PK PRIMARY KEY (AUDITID);

-- optional index for search performance
--DROP INDEX TBL_FORM_DTL_AUDIT_NK1;
CREATE INDEX TBL_FORM_DTL_AUDIT_NK1 ON TBL_FORM_DTL_AUDIT (ID);

-- optional index for search performance
--DROP INDEX TBL_FORM_DTL_AUDIT_NK2;
CREATE INDEX TBL_FORM_DTL_AUDIT_NK2 ON TBL_FORM_DTL_AUDIT (PROCID);


COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.AUDITID IS 'Unique primary key.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.ID IS 'Unique primary key of TBL_FORM_DTL table record being audited.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.PROCID IS 'Foreign key of TBL_FORM_DTL table record being audited. Process ID of the related BIZFLOW.PROCS table.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.ACTSEQ IS 'Foreign key of TBL_FORM_DTL table record being audited. Activity Sequence of the related BIZFLOW.ACT table.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.WITEMSEQ IS 'Foreign key of TBL_FORM_DTL table record being audited. Work Item Sequence of the related BIZFLOW.WITEM table.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.FORM_TYPE IS 'Form Type of TBL_FORM_DTL table record being audited.  Indicates what form data is stored in the record.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.FIELD_DATA IS 'XML representation of the form data of TBL_FORM_DTL table record being audited.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.CRT_DT IS 'Creation Date of TBL_FORM_DTL table record being audited';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.CRT_USR IS 'Creation User of TBL_FORM_DTL table record being audited';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.MOD_DT IS 'Modification Date of TBL_FORM_DTL table record being audited';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.MOD_USR IS 'Modification User of TBL_FORM_DTL table record being audited';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.AUDIT_ACTION IS 'Audit action.  Expected values are INSERTING, UPDATING, or DELETING.';
COMMENT ON COLUMN TBL_FORM_DTL_AUDIT.AUDIT_TS IS 'Audit timestamp';


CREATE SEQUENCE TBL_FORM_DTL_AUDIT_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/


CREATE OR REPLACE TRIGGER TBL_FORM_DTL_AUDIT_BIR
BEFORE INSERT ON TBL_FORM_DTL_AUDIT
FOR EACH ROW
BEGIN
	SELECT TBL_FORM_DTL_AUDIT_SEQ.NEXTVAL
	INTO :NEW.AUDITID
	FROM DUAL;
END;

/



-- Trigger on source table to record onto target audit table
CREATE OR REPLACE TRIGGER TBL_FORM_DTL_AIUDR
AFTER INSERT OR UPDATE OR DELETE ON TBL_FORM_DTL
FOR EACH ROW
DECLARE
	V_TRG_ACTION VARCHAR2(50);
BEGIN
	CASE
		WHEN INSERTING THEN
			V_TRG_ACTION := 'INSERTING';
			INSERT INTO TBL_FORM_DTL_AUDIT
			(
				ID
				, PROCID
				, ACTSEQ
				, WITEMSEQ
				, FORM_TYPE
				, FIELD_DATA
				, CRT_DT
				, CRT_USR
				, MOD_DT
				, MOD_USR
				, AUDIT_ACTION
				, AUDIT_TS
			)
			VALUES
			(
				:NEW.ID
				, :NEW.PROCID
				, :NEW.ACTSEQ
				, :NEW.WITEMSEQ
				, :NEW.FORM_TYPE
				, :NEW.FIELD_DATA
				, :NEW.CRT_DT
				, :NEW.CRT_USR
				, :NEW.MOD_DT
				, :NEW.MOD_USR
				, V_TRG_ACTION
				, SYSTIMESTAMP
			);
		WHEN UPDATING THEN
			V_TRG_ACTION := 'UPDATING';
			INSERT INTO TBL_FORM_DTL_AUDIT
			(
				ID
				, PROCID
				, ACTSEQ
				, WITEMSEQ
				, FORM_TYPE
				, FIELD_DATA
				, CRT_DT
				, CRT_USR
				, MOD_DT
				, MOD_USR
				, AUDIT_ACTION
				, AUDIT_TS
			)
			VALUES
			(
				:NEW.ID
				, :NEW.PROCID
				, :NEW.ACTSEQ
				, :NEW.WITEMSEQ
				, :NEW.FORM_TYPE
				, :NEW.FIELD_DATA
				, :NEW.CRT_DT
				, :NEW.CRT_USR
				, :NEW.MOD_DT
				, :NEW.MOD_USR
				, V_TRG_ACTION
				, SYSTIMESTAMP
			);
		WHEN DELETING THEN
			V_TRG_ACTION := 'DELETING';
			INSERT INTO TBL_FORM_DTL_AUDIT
			(
				ID
				, PROCID
				, ACTSEQ
				, WITEMSEQ
				, FORM_TYPE
				, FIELD_DATA
				, CRT_DT
				, CRT_USR
				, MOD_DT
				, MOD_USR
				, AUDIT_ACTION
				, AUDIT_TS
			)
			VALUES
			(
				:OLD.ID
				, :OLD.PROCID
				, :OLD.ACTSEQ
				, :OLD.WITEMSEQ
				, :OLD.FORM_TYPE
				, :OLD.FIELD_DATA
				, :OLD.CRT_DT
				, :OLD.CRT_USR
				, :OLD.MOD_DT
				, :OLD.MOD_USR
				, V_TRG_ACTION
				, SYSTIMESTAMP
			);
		ELSE V_TRG_ACTION := NULL;
	END CASE;

EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();

END;

/

--------------------------------------------------------
--  DDL for Table OCCUPATIONAL_SERIES
--------------------------------------------------------

  CREATE TABLE OCCUPATIONAL_SERIES 
   (	PAY_PLAN VARCHAR2(2), 
	SERIES VARCHAR2(4), 
	DESCRIPTION VARCHAR2(100)
   ) ;

/

--------------------------------------------------------
--  DDL for Table TYPE_VALUES
--------------------------------------------------------	
	CREATE TABLE TYPE_VALUES
	(REPL_ID			NUMBER(10),
	 TYPE_NAME		VARCHAR2(50),
	 TYPE_VALUE		VARCHAR2(100),
	 CONDITION_1	VARCHAR2(1028),
	 CONDITION_2	VARCHAR2(1028),
	 DISP_ORDER		NUMBER(10),
	 TYPE_CODE		VARCHAR2(50)
	);

/

--------------------------------------------------------
--  DDL for Table RDR_APPROVAL
--------------------------------------------------------

  CREATE TABLE RDR_APPROVAL 
   (	PROGRAM VARCHAR2(20), 
	APP_LEVEL1 VARCHAR2(200), 
	APP_LEVEL2 VARCHAR2(200), 
	APP_LEVEL3 VARCHAR2(200), 
	APP_LEVEL4 VARCHAR2(200), 
	APP_LEVEL5 VARCHAR2(200), 
	APP_LEVEL6 VARCHAR2(200), 
	APP_LEVEL7 VARCHAR2(200), 
	APP_LEVEL8 VARCHAR2(200), 
	APP_LEVEL9 VARCHAR2(200), 
	APP_LEVEL10 VARCHAR2(200)
  ) ;

 /

  CREATE OR REPLACE  VIEW VW_WHRSC_RECRUITMENT (TRANSACTION_ID, DATE_RECEIVED, ACTION_TYPE, DATE_SF52_RECEIVED, GLOBAL_RECRUITMENT, ADMIN_CODE, INSTITUTE, ORG_INITS, PROPOSED_EFF_DATE, BRANCH_CHIEF, TEAM_LEADER, HR_SPECIALIST, HR_ASSISTANT, HR_SPA, PCKG_COMPLETE, MISSING_DOCS, MISSING_DOCS_EMAIL_SENT_DATE, MISSING_DOCS_RECEIPT_DATE, PRIORITY, RYB_CODE, RYB_STATUS, RYB_DESCRIPTION, COMMENTS_STATUS, JOB_OPENING_ID, DATE_JOB_OPENING_APPROVED, CAN_NO, TK_NO, FTE_LIAISON_FIRST_NAME, FTE_LIAISON_LAST_NAME, FTE_LIAISON_EMAIL, PROGRAM_MGR_FIRST_NAME, PROGRAM_MGR_LAST_NAME, PROGRAM_MGR_EMAIL, SUPERVISOR_FIRST_NAME, SUPERVISOR_LAST_NAME, SUPERVISOR_EMAIL, DATE_PRERECRUIT_MEETING, DATE_PRERECRUIT_SHEET_SIGNED, RECRUITMENT_TYPE, DATE_NEED_VALIDATED, LEGISLATIVE_INIT_SUPPORTED, NUM_POSITIONS_TO_BE_ADV, IS_NEW_POSITION, IS_READVERTISEMENT, RDR_PD_USED, RDR_PD_KEY_NUMBER, RELATED_CLASSIFICATION_NUMBER, IS_TRANSITIONAL_RECRUIT, OTHER_RECRUIT_CONSIDERATIONS, PAID_AD, CLEARANCE_LEVEL_REQUIRED, PAID_AD_APPROVED_DATE, IS_RELOCATION_EXPENSES_PAID, INCENTIVES_OFFERED, ADDITIONAL_RECRUIT_CHANNELS, PRERECRUIT_COMMENTS, ANN_NUMBER, DE_HR_SPECIALIST, DE_HR_SPECIALIST_ID, DE_QUALITY_REVIEWER, DE_QUALITY_REVIEWER_ID, QUALITY_REVIEWER, QUALITY_REVIEWER_ID, CASE_RETURNED_COMMENTS, SELECTIVE_PLACEMNT_FCTR_CMNTS, CASE_EXAMINING_REGISTER, DATE_SENT_TO_DEU, OPEN_CONTINUOUS_ANN, DATE_ANN_APPROVED_BY_DEU, EVALUATION_METHOD, RATER, DATE_MIN_QUALS_COMPLETED, DATE_APPS_TO_SME_QRB, DATE_APPS_RECD_SME_QRB, CERT_NUMBER, DATE_INTERNAL_REVIEW_COMPLETED, DATE_10PT_FILE_CHECKED, CERT_EXTENDED, DATE_NEW_CERT_EXPIRES, CERT_USED, CERT_RET_UNUSED_REASON, CERT_RET_UNUSED_REASON_OTHER, DT_CERT_RTN_TO_DEU_FNL_AUDIT) AS 
  SELECT 
M.TRANSACTION_ID,M.DATE_RECEIVED,M.ACTION_TYPE,M.DATE_SF52_RECEIVED,M.GLOBAL_RECRUITMENT,M.ADMIN_CODE,M.INSTITUTE,M.ORG_INITS,M.PROPOSED_EFF_DATE
,M.BRANCH_CHIEF,M.TEAM_LEADER,M.HR_SPECIALIST,M.HR_ASSISTANT,M.HR_SPA,M.PCKG_COMPLETE,M.MISSING_DOCS,M.MISSING_DOCS_EMAIL_SENT_DATE,M.MISSING_DOCS_RECEIPT_DATE
,M.PRIORITY,M.RYB_CODE,M.RYB_STATUS,M.RYB_DESCRIPTION,M.COMMENTS_STATUS,M.JOB_OPENING_ID,M.DATE_JOB_OPENING_APPROVED,M.CAN_NO,M.TK_NO
,IC.FTE_LIAISON_FIRST_NAME,IC.FTE_LIAISON_LAST_NAME,IC.FTE_LIAISON_EMAIL,IC.PROGRAM_MGR_FIRST_NAME,IC.PROGRAM_MGR_LAST_NAME,IC.PROGRAM_MGR_EMAIL
,IC.SUPERVISOR_FIRST_NAME,IC.SUPERVISOR_LAST_NAME,IC.SUPERVISOR_EMAIL
,R.DATE_PRERECRUIT_MEETING,R.DATE_PRERECRUIT_SHEET_SIGNED,R.RECRUITMENT_TYPE,R.DATE_NEED_VALIDATED,R.LEGISLATIVE_INIT_SUPPORTED,R.NUM_POSITIONS_TO_BE_ADV
,R.IS_NEW_POSITION,R.IS_READVERTISEMENT,R.RDR_PD_USED,R.RDR_PD_KEY_NUMBER,R.RELATED_CLASSIFICATION_NUMBER,R.IS_TRANSITIONAL_RECRUIT,R.OTHER_RECRUIT_CONSIDERATIONS
,R.PAID_AD,R.CLEARANCE_LEVEL_REQUIRED,R.PAID_AD_APPROVED_DATE,R.IS_RELOCATION_EXPENSES_PAID,R.INCENTIVES_OFFERED,R.ADDITIONAL_RECRUIT_CHANNELS,R.PRERECRUIT_COMMENTS
,AN.ANN_NUMBER,AN.DE_HR_SPECIALIST,AN. DE_HR_SPECIALIST_ID,AN. DE_QUALITY_REVIEWER,AN.DE_QUALITY_REVIEWER_ID,AN. QUALITY_REVIEWER,AN. QUALITY_REVIEWER_ID,AN.CASE_RETURNED_COMMENTS
,AN.SELECTIVE_PLACEMNT_FCTR_CMNTS,AN. CASE_EXAMINING_REGISTER,AN.DATE_SENT_TO_DEU,AN.OPEN_CONTINUOUS_ANN,AN.DATE_ANN_APPROVED_BY_DEU
,AR.EVALUATION_METHOD,AR.RATER,AR.DATE_MIN_QUALS_COMPLETED,AR.DATE_APPS_TO_SME_QRB,AR.DATE_APPS_RECD_SME_QRB
,C.CERT_NUMBER,C.DATE_INTERNAL_REVIEW_COMPLETED,C.DATE_10PT_FILE_CHECKED,C.CERT_EXTENDED,C.DATE_NEW_CERT_EXPIRES,C.CERT_USED,C.CERT_RET_UNUSED_REASON
,C.CERT_RET_UNUSED_REASON_OTHER,C.DT_CERT_RTN_TO_DEU_FNL_AUDIT
 FROM HHS_WHRSC_HR.MAIN M 
JOIN HHS_WHRSC_HR.IC_REQUEST_INFO IC ON IC.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.RECRUITMENT R ON R.TRANSACTION_ID = M.TRANSACTION_ID
LEFT OUTER JOIN HHS_WHRSC_HR.ANNOUNCEMENT AN ON AN.TRANSACTION_ID = M.TRANSACTION_ID
LEFT OUTER JOIN HHS_WHRSC_HR.APPLICANT_RATING AR ON AR.TRANSACTION_ID = M.TRANSACTION_ID
LEFT OUTER JOIN HHS_WHRSC_HR.CERTIFICATE C ON C.TRANSACTION_ID = M.TRANSACTION_ID
WHERE M.ACTION_TYPE='Recruitment';

/

CREATE OR REPLACE  VIEW VW_WHRSC_APPOINTMENT (TRANSACTION_ID, DATE_RECEIVED, ACTION_TYPE, DATE_SF52_RECEIVED, GLOBAL_RECRUITMENT, ADMIN_CODE, INSTITUTE, ORG_INITS, PROPOSED_EFF_DATE, BRANCH_CHIEF, TEAM_LEADER, HR_SPECIALIST, HR_ASSISTANT, HR_SPA, PCKG_COMPLETE, MISSING_DOCS, MISSING_DOCS_EMAIL_SENT_DATE, MISSING_DOCS_RECEIPT_DATE, PRIORITY, RYB_CODE, RYB_STATUS, RYB_DESCRIPTION, COMMENTS_STATUS, JOB_OPENING_ID, DATE_JOB_OPENING_APPROVED, CAN_NO, TK_NO, FTE_LIAISON_FIRST_NAME, FTE_LIAISON_LAST_NAME, FTE_LIAISON_EMAIL, SUPERVISOR_FIRST_NAME, SUPERVISOR_LAST_NAME, SUPERVISOR_EMAIL, ANN_NUMBER, VIN, CERT_NUMBER, CERT_TYPE, DATE_CERT_TO_SO, DATE_OF_HIRING_DECISION, DATE_HIRING_DEC_RECD_IN_HR, CURRENT_EMPLOYEE, FIRST_NAME, LAST_NAME, EMPLOYEE_ID, EMAIL, SUPERVISORY_STATUS, FILER278, FILER450, BOARD_CRTFCN, POSITION_TITLE, PAY_PLAN, SERIES, GRADE, FULL_PERF_LEVEL, STEP, PAY_TIER, PAY_BAND, JOB_CODE, POSITION_NO, DUTY_LOCATION, DUTY_LOCATION_CODE, BASIC_PAY_MIN, BASIC_PAY_MAX, PROFESSIONAL_DESIGNATION, ELIGIBLE_FOR_BENEFITS, NTE_DATE, ATTENDED_ORIENTATION, ORIENTATION_DATE, ORIENTATION_LOCATION, ORIENTATION_EMAIL_ADDRESS, HIRE_TYPE, DT_OFFICIAL_OFFER_LETTER_SENT, RELATIONSHIP_TO_RECRUIT_ACTION, SHARED_SELECTION, RDR_PD_USED, RDR_PD_NUMBER, LEGISLATIVE_INITIATIVE_USED, TENTATIVE_JOB_OFFER_DATE, TENTATIVE_JOB_OFFER_RSPNS_DT, JOB_OFFER_RESPONSE, ADDITIONAL_APPROVAL_REQ, ADDITIONAL_APPROVAL_COMMENT, DT_OFFICIAL_JOB_OFFER, OFFICIAL_JOB_OFFER_RESP_DT, DT_SECURITY_INVESTIG_INITIATED, OF306_ASSIGNED_ONBOARD_MGR, CLEARANCE_LEVEL_REQUIRED, DATE_SENT_FOR_OF306_REVIEW, DATE_DPSAC_NOTIFICATION_RCVD, DPSAC_REVIEW_DISPOSITION, DATE_PREP_NEW_HIRE_EMAIL_SENT, TYPE_SELECTION, APPOINTMENT_TYPE, NATURE_ACTION_CODE, HIRING_FLEX_USED, PRIORITY_PLACEMENT, HIRING_FLEX_TYPE, HIRING_FLEX_TYPE_OTHER, IS_PATHWAY_AGREE_COMP, WORK_PERMIT_REQUIRED, DATE_WORK_PERMIT_RECEIVED, MEDICAL_SPECIALITY, TYPE_PREFERENCE, IS_REEMPLOYED_ANNUITANT, EDUCATIONAL_DOCS_RCVD_DATE, APPOINTEE_REFERRED_BY, IS_TEMP_FED_EMP_ID_ASSIGNED, IS_RELEASE_DATE_REQUESTED, DATE_RELEASE_REQUESTED, APPROVED_RELEASE_DATE, DATE_PKG_SENT_FOR_ADDL_APPR, DATE_APPR_DEC_RECVD_HR, FIC_DIS_APPROVAL_DATE, VISA_EAD_TYPE, VISA_EAD_EFFECTIVE_DATE, VISA_EAD_EXPIRATION_DATE, DEU_SELECTION_APRVR, DEU_SELECTION_ADDL_INFO_NEEDED, DEU_SELECTION_DCSN, DATE_TO_DEU_FOR_DECISION, DEU_SELECTION_DCSN_DATE, DEU_SELECTION_DCSN_CMNTS, PAY_TYPE,DATE_ARP_SENT_FOR_APPROVAL,DATE_ARP_APPROVED) AS 
  SELECT 
M.TRANSACTION_ID,M.DATE_RECEIVED,M.ACTION_TYPE,M.DATE_SF52_RECEIVED,M.GLOBAL_RECRUITMENT,M.ADMIN_CODE,M.INSTITUTE,M.ORG_INITS,M.PROPOSED_EFF_DATE
,M.BRANCH_CHIEF,M.TEAM_LEADER,M.HR_SPECIALIST,M.HR_ASSISTANT,M.HR_SPA,M.PCKG_COMPLETE,M.MISSING_DOCS,M.MISSING_DOCS_EMAIL_SENT_DATE,M.MISSING_DOCS_RECEIPT_DATE
,M.PRIORITY,M.RYB_CODE,M.RYB_STATUS,M.RYB_DESCRIPTION,M.COMMENTS_STATUS,M.JOB_OPENING_ID,M.DATE_JOB_OPENING_APPROVED,M.CAN_NO,M.TK_NO

,IC.FTE_LIAISON_FIRST_NAME,IC.FTE_LIAISON_LAST_NAME,IC.FTE_LIAISON_EMAIL,IC.SUPERVISOR_FIRST_NAME,IC.SUPERVISOR_LAST_NAME,IC.SUPERVISOR_EMAIL

,AN.ANN_NUMBER,AN.VIN

,C.CERT_NUMBER,C.CERT_TYPE,C.DATE_CERT_TO_SO,C.DATE_OF_HIRING_DECISION,C.DATE_HIRING_DEC_RECD_IN_HR

,PI.CURRENT_EMPLOYEE,PI.FIRST_NAME,PI.LAST_NAME,PI.EMPLOYEE_ID,PI.EMAIL,PI.SUPERVISORY_STATUS,PI.FILER278,PI.FILER450,PI.BOARD_CRTFCN

,NP.POSITION_TITLE,NP.PAY_PLAN,NP.SERIES,NP.GRADE,NP.FULL_PERF_LEVEL,NP.STEP,NP.PAY_TIER,NP.PAY_BAND,NP.JOB_CODE,NP.POSITION_NO,NP.DUTY_LOCATION
,NP.DUTY_LOCATION_CODE,NP.BASIC_PAY_MIN,NP.BASIC_PAY_MAX,NP.PROFESSIONAL_DESIGNATION,NP.ELIGIBLE_FOR_BENEFITS,NP.NTE_DATE


,ORI.ATTENDED_ORIENTATION,ORI.ORIENTATION_DATE ,ORI.ORIENTATION_LOCATION ,ORI.ORIENTATION_EMAIL_ADDRESS ,ORI.HIRE_TYPE ,ORI.DT_OFFICIAL_OFFER_LETTER_SENT

,AP.RELATIONSHIP_TO_RECRUIT_ACTION ,AP.SHARED_SELECTION ,AP.RDR_PD_USED ,AP.RDR_PD_NUMBER ,AP.LEGISLATIVE_INITIATIVE_USED
,AP.TENTATIVE_JOB_OFFER_DATE ,AP.TENTATIVE_JOB_OFFER_RSPNS_DT ,AP.JOB_OFFER_RESPONSE ,AP.ADDITIONAL_APPROVAL_REQ
,AP.ADDITIONAL_APPROVAL_COMMENT ,AP.DT_OFFICIAL_JOB_OFFER ,AP.OFFICIAL_JOB_OFFER_RESP_DT ,AP.DT_SECURITY_INVESTIG_INITIATED
,AP.OF306_ASSIGNED_ONBOARD_MGR ,AP.CLEARANCE_LEVEL_REQUIRED ,AP.DATE_SENT_FOR_OF306_REVIEW ,AP.DATE_DPSAC_NOTIFICATION_RCVD
,AP.DPSAC_REVIEW_DISPOSITION ,AP.DATE_PREP_NEW_HIRE_EMAIL_SENT ,AP.TYPE_SELECTION ,AP.APPOINTMENT_TYPE ,AP.NATURE_ACTION_CODE
,AP.HIRING_FLEX_USED ,AP.PRIORITY_PLACEMENT ,AP.HIRING_FLEX_TYPE ,AP.HIRING_FLEX_TYPE_OTHER ,AP.IS_PATHWAY_AGREE_COMP
,AP.WORK_PERMIT_REQUIRED ,AP.DATE_WORK_PERMIT_RECEIVED ,AP.MEDICAL_SPECIALITY ,AP.TYPE_PREFERENCE ,AP.IS_REEMPLOYED_ANNUITANT
,AP.EDUCATIONAL_DOCS_RCVD_DATE ,AP.APPOINTEE_REFERRED_BY ,AP.IS_TEMP_FED_EMP_ID_ASSIGNED ,AP.IS_RELEASE_DATE_REQUESTED
,AP.DATE_RELEASE_REQUESTED ,AP.APPROVED_RELEASE_DATE ,AP.DATE_PKG_SENT_FOR_ADDL_APPR ,AP.DATE_APPR_DEC_RECVD_HR 
,AP.FIC_DIS_APPROVAL_DATE ,AP.VISA_EAD_TYPE ,AP.VISA_EAD_EFFECTIVE_DATE ,AP.VISA_EAD_EXPIRATION_DATE ,AP.DEU_SELECTION_APRVR
,AP.DEU_SELECTION_ADDL_INFO_NEEDED ,AP.DEU_SELECTION_DCSN ,AP.DATE_TO_DEU_FOR_DECISION ,AP.DEU_SELECTION_DCSN_DATE ,AP.DEU_SELECTION_DCSN_CMNTS,AP.PAY_TYPE,AP.DATE_ARP_SENT_FOR_APPROVAL,AP.DATE_ARP_APPROVED

FROM HHS_WHRSC_HR.MAIN M JOIN HHS_WHRSC_HR.IC_REQUEST_INFO IC ON IC.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.ANNOUNCEMENT AN ON AN.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.CERTIFICATE C ON C.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.PERSON_INFO PI ON PI.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.NEW_POSITION NP ON NP.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.ORIENTATION ORI ON ORI.TRANSACTION_ID = M.TRANSACTION_ID
JOIN HHS_WHRSC_HR.APPOINTMENT AP ON AP.TRANSACTION_ID = M.TRANSACTION_ID
WHERE M.ACTION_TYPE='Appointment';

/