CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_ACTIVE_RECRUITMENTS AS
--===========================================================
SELECT 
	main_combined.*,
	HHS_WHRSC_HR."RECRUITMENT"."DATE_REC_PCKG_SENT_APPROVED",
	null as "Investigation Complete"
FROM  HHS_WHRSC_HR."RECRUITMENT" 
	left join 
		(SELECT  
			 HHS_WHRSC_HR."MAIN"."TRANSACTION_ID",
			  HHS_WHRSC_HR."MAIN"."HR_SPECIALIST",
			  HHS_WHRSC_HR."MAIN"."ADMIN_CODE",
			  HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID",
			   vac_cert_combined."POSITION_TITLE",
			   vac_cert_combined."Series",
			   vac_cert_combined."Grade",
			   vac_cert_combined."Locations",
			   vac_cert_combined."Special Tracking",
			   vac_cert_combined."ANNOUNCEMENT_TYPE",
			   NVL(vac_cert_combined."VACANCY_ANNOUNCEMENT_NUMBER", vac_cert_combined."VACANCY_IDENTIFICATION_NUMBER") as "Announcement Number/VIN",
			   vac_cert_combined."Number of Certs",
			   HHS_WHRSC_HR."MAIN"."DATE_RECEIVED",
			   HHS_WHRSC_HR."MAIN"."MISSING_DOCS_RECEIPT_DATE",
			   vac_cert_combined."DATE_ANN_APPROVED_BY_DEU",
			   vac_cert_combined."DATE_ANNOUNCEMENT_OPENED",
			   vac_cert_combined."DATE_ANNOUNCEMENT_CLOSED",
			   vac_cert_combined."First Cert Issue Date",
			   vac_cert_combined."First Cert Return Date",
			   vac_cert_combined."First Cert Return Date"+120 as "Cert Expire Date",
			   nh_combined."NH_CREATION_DATE",
			   nh_combined."SEND_TENTATV_OFFER_COMPLT_DATE",
			   nh_combined."BCKGRND_INVSTGTN_COMPLT_DATE",
			   nh_combined."SEND_OFFICL_OFFER_COMPLT_DATE",
			   nh_combined."NH_ACTUAL_START_DATE",
			   vac_cert_combined."DATE_ANNOUNCEMENT_POSTED",
			   vac_cert_combined."TOTAL_REFERRED_APPLICANTS",
			   HHS_WHRSC_HR."MAIN"."COMMENTS_STATUS",
			   HHS_WHRSC_HR."MAIN"."STATUS" 
		FROM HHS_WHRSC_HR."MAIN" 
			left join
				(SELECT *
			FROM  HHS_WHRSC_HR."DSS_VACANCY" 
			 left join 
				(select  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG( HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."LOCATION_CITY" , '; ')
						within group (order by HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" ) "Locations"
						from  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS" 
						group by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
						order by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
					) loc
					 on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = loc."VACANCY_IDENTIFICATION_NUMBER"  
				left join 
					(select  a."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(a."SERIES" , '; ')
						within group (order by a."VACANCY_IDENTIFICATION_NUMBER" ) "Series"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 
						HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."SERIES" from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") a
						group by   a."VACANCY_IDENTIFICATION_NUMBER" 
						order by   a."VACANCY_IDENTIFICATION_NUMBER" 			
					) ser
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = ser."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  b."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(b."GRADE" , ';')
						within group (order by b."VACANCY_IDENTIFICATION_NUMBER" ) "Grade"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 			
						to_char(HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."GRADE", '99') as "GRADE"
							from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") b
						group by   b."VACANCY_IDENTIFICATION_NUMBER" 
						order by   b."VACANCY_IDENTIFICATION_NUMBER"			
					) gra
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = gra."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  c."VACANCY_NUMBER", 
						LISTAGG(c."VCNCY_MISSION_CRITICAL_OCCUPTN" , '; ')
						within group (order by c."VACANCY_NUMBER" ) "Special Tracking"
						from  
						(select distinct  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VACANCY_NUMBER", 
							HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VCNCY_MISSION_CRITICAL_OCCUPTN"
							from  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN" ) c
						group by   c."VACANCY_NUMBER" 
						order by   c."VACANCY_NUMBER"			
					) mco
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = mco."VACANCY_NUMBER"
				left join  HHS_WHRSC_HR."ANNOUNCEMENT" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" =  HHS_WHRSC_HR."ANNOUNCEMENT"."VIN" 
				left join  HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION"."VACANCY_NUMBER" 
				left join
					(SELECT  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER", 
							count( HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER") as "Number of Certs", 
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_CERTIFICATE_ISSUED") as "First Cert Issue Date",
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_HIRING_DECISN_RECD_IN_HR") as "First Cert Return Date" 
						FROM  HHS_WHRSC_HR."DSS_CERTIFICATES" 
							left join  HHS_WHRSC_HR."CERTIFICATE" 
								on  HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER" =  HHS_WHRSC_HR."CERTIFICATE"."CERT_NUMBER" 
						group by  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 
						order by HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 			
					) cert_combined
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = cert_combined."VACANCY_IDENTIFICATION_NUMBER"		
				) vac_cert_combined
				on  HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" = vac_cert_combined."REQUEST_NUMBER" 
			left join (SELECT *
				FROM HHS_WHRSC_HR."DSS_NEW_HIRES"
				left join HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS" 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS"."NEW_HIRE_NUMBER"
				left join 
					(select distinct HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NEW_HIRE_NUMBER", HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NH_REQUEST_NUMBER"
						from  HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST" 
					) nhvr 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = nhvr."NEW_HIRE_NUMBER"		
				) nh_combined
				on HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" =nh_combined."NH_REQUEST_NUMBER"
		) main_combined
		on  HHS_WHRSC_HR."RECRUITMENT"."TRANSACTION_ID" = main_combined."TRANSACTION_ID"
		where STATUS = 'ACTIVE';
--===========================================================
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_ALL_RECRUITMENTS AS
--===========================================================
SELECT 
	main_combined.*,
	HHS_WHRSC_HR."RECRUITMENT"."DATE_REC_PCKG_SENT_APPROVED",
	null as "Investigation Complete"
FROM  HHS_WHRSC_HR."RECRUITMENT" 
	left join 
		(SELECT  
			 HHS_WHRSC_HR."MAIN"."TRANSACTION_ID",
			  HHS_WHRSC_HR."MAIN"."HR_SPECIALIST",
			  HHS_WHRSC_HR."MAIN"."ADMIN_CODE",
			  HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID",
			   vac_cert_combined."POSITION_TITLE",
			   vac_cert_combined."Series",
			   vac_cert_combined."Grade",
			   vac_cert_combined."Locations",
			   vac_cert_combined."Special Tracking",
			   vac_cert_combined."ANNOUNCEMENT_TYPE",
			   NVL(vac_cert_combined."VACANCY_ANNOUNCEMENT_NUMBER", vac_cert_combined."VACANCY_IDENTIFICATION_NUMBER") as "Announcement Number/VIN",
			   vac_cert_combined."Number of Certs",
			   HHS_WHRSC_HR."MAIN"."DATE_RECEIVED",
			   HHS_WHRSC_HR."MAIN"."MISSING_DOCS_RECEIPT_DATE",
			   vac_cert_combined."DATE_ANN_APPROVED_BY_DEU",
			   vac_cert_combined."DATE_ANNOUNCEMENT_OPENED",
			   vac_cert_combined."DATE_ANNOUNCEMENT_CLOSED",
			   vac_cert_combined."First Cert Issue Date",
			   vac_cert_combined."First Cert Return Date",
			   vac_cert_combined."First Cert Return Date"+120 as "Cert Expire Date",
			   nh_combined."NH_CREATION_DATE",
			   nh_combined."SEND_TENTATV_OFFER_COMPLT_DATE",
			   nh_combined."BCKGRND_INVSTGTN_COMPLT_DATE",
			   nh_combined."SEND_OFFICL_OFFER_COMPLT_DATE",
			   nh_combined."NH_ACTUAL_START_DATE",
			   vac_cert_combined."DATE_ANNOUNCEMENT_POSTED",
			   vac_cert_combined."TOTAL_REFERRED_APPLICANTS",
			   HHS_WHRSC_HR."MAIN"."COMMENTS_STATUS",
			   HHS_WHRSC_HR."MAIN"."STATUS" 
		FROM HHS_WHRSC_HR."MAIN" 
			left join
				(SELECT *
			FROM  HHS_WHRSC_HR."DSS_VACANCY" 
			 left join 
				(select  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG( HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."LOCATION_CITY" , '; ')
						within group (order by HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" ) "Locations"
						from  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS" 
						group by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
						order by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
					) loc
					 on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = loc."VACANCY_IDENTIFICATION_NUMBER"  
				left join 
					(select  a."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(a."SERIES" , '; ')
						within group (order by a."VACANCY_IDENTIFICATION_NUMBER" ) "Series"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 
						HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."SERIES" from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") a
						group by   a."VACANCY_IDENTIFICATION_NUMBER" 
						order by   a."VACANCY_IDENTIFICATION_NUMBER" 			
					) ser
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = ser."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  b."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(b."GRADE" , ';')
						within group (order by b."VACANCY_IDENTIFICATION_NUMBER" ) "Grade"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 			
						to_char(HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."GRADE", '99') as "GRADE"
							from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") b
						group by   b."VACANCY_IDENTIFICATION_NUMBER" 
						order by   b."VACANCY_IDENTIFICATION_NUMBER"			
					) gra
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = gra."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  c."VACANCY_NUMBER", 
						LISTAGG(c."VCNCY_MISSION_CRITICAL_OCCUPTN" , '; ')
						within group (order by c."VACANCY_NUMBER" ) "Special Tracking"
						from  
						(select distinct  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VACANCY_NUMBER", 
							HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VCNCY_MISSION_CRITICAL_OCCUPTN"
							from  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN" ) c
						group by   c."VACANCY_NUMBER" 
						order by   c."VACANCY_NUMBER"			
					) mco
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = mco."VACANCY_NUMBER"
				left join  HHS_WHRSC_HR."ANNOUNCEMENT" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" =  HHS_WHRSC_HR."ANNOUNCEMENT"."VIN" 
				left join  HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION"."VACANCY_NUMBER" 
				left join
					(SELECT  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER", 
							count( HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER") as "Number of Certs", 
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_CERTIFICATE_ISSUED") as "First Cert Issue Date",
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_HIRING_DECISN_RECD_IN_HR") as "First Cert Return Date" 
						FROM  HHS_WHRSC_HR."DSS_CERTIFICATES" 
							left join  HHS_WHRSC_HR."CERTIFICATE" 
								on  HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER" =  HHS_WHRSC_HR."CERTIFICATE"."CERT_NUMBER" 
						group by  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 
						order by HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 			
					) cert_combined
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = cert_combined."VACANCY_IDENTIFICATION_NUMBER"		
				) vac_cert_combined
				on  HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" = vac_cert_combined."REQUEST_NUMBER" 
			left join (SELECT *
				FROM HHS_WHRSC_HR."DSS_NEW_HIRES"
				left join HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS" 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS"."NEW_HIRE_NUMBER"
				left join 
					(select distinct HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NEW_HIRE_NUMBER", HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NH_REQUEST_NUMBER"
						from  HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST" 
					) nhvr 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = nhvr."NEW_HIRE_NUMBER"		
				) nh_combined
				on HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" =nh_combined."NH_REQUEST_NUMBER"
		) main_combined
		on  HHS_WHRSC_HR."RECRUITMENT"."TRANSACTION_ID" = main_combined."TRANSACTION_ID";
--===================================================================
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_ACTIVE_RECRUITMENTS_EXPAND AS
--===================================================================
SELECT 
	main_combined.*,
	 HHS_WHRSC_HR."RECRUITMENT"."RECRUITMENT_TYPE",
	 HHS_WHRSC_HR."RECRUITMENT"."LEGISLATIVE_INIT_SUPPORTED", 
	HHS_WHRSC_HR."RECRUITMENT"."DATE_REC_PCKG_SENT_APPROVED",
	null as "Investigation Complete"
FROM  HHS_WHRSC_HR."RECRUITMENT" 
	left join 
		(SELECT  
			HHS_WHRSC_HR."MAIN"."TRANSACTION_ID",
			HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID",
			Branch."BRANCH", 
			HHS_WHRSC_HR."MAIN"."INSTITUTE",
			HHS_WHRSC_HR."MAIN"."ADMIN_CODE",
			HHS_WHRSC_HR."MAIN"."ORG_INITS",
			HHS_WHRSC_HR."MAIN"."HR_SPECIALIST",
			HHS_WHRSC_HR."MAIN"."GLOBAL_RECRUITMENT", 
			 vac_cert_combined."ANNOUNCEMENT_TYPE",
			 vac_cert_combined."OPEN_CONTINUOUS_ANN", 
			 vac_cert_combined."Special Tracking",
			 vac_cert_combined."Locations",
			 vac_cert_combined."POSITION_TITLE",
			 vac_cert_combined."Pay Plan",
			 vac_cert_combined."Series",
			 vac_cert_combined."Grade",
			 vac_cert_combined."FULL_PERFORMANCE_LEVEL", 
			 HHS_WHRSC_HR."MAIN"."DATE_RECEIVED",
			 HHS_WHRSC_HR."MAIN"."MISSING_DOCS_RECEIPT_DATE",
			 HHS_WHRSC_HR."MAIN"."COMMENTS_STATUS",
			 HHS_WHRSC_HR."MAIN"."RYB_STATUS",
			  HHS_WHRSC_HR."MAIN"."STATUS" 
		FROM HHS_WHRSC_HR."MAIN" 
			left join
				(SELECT *
			FROM  HHS_WHRSC_HR."DSS_VACANCY" 
			 left join 
				(select  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG( HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."LOCATION_CITY" , '; ')
						within group (order by HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" ) "Locations"
						from  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS" 
						group by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
						order by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
					) loc
					 on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = loc."VACANCY_IDENTIFICATION_NUMBER"  
				left join 
					(select  a."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(a."SERIES" , ',')
						within group (order by a."VACANCY_IDENTIFICATION_NUMBER" ) "Series"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 
						HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."SERIES" from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") a
						group by   a."VACANCY_IDENTIFICATION_NUMBER" 
						order by   a."VACANCY_IDENTIFICATION_NUMBER" 			
					) ser
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = ser."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  b."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(b."GRADE" , ',')
						within group (order by b."VACANCY_IDENTIFICATION_NUMBER" ) "Grade"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 			
						to_char(HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."GRADE", '99') as "GRADE"
							from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") b
						group by   b."VACANCY_IDENTIFICATION_NUMBER" 
						order by   b."VACANCY_IDENTIFICATION_NUMBER"			
					) gra
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = gra."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  d."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(d."PAY_PLAN" , ',')
						within group (order by d."VACANCY_IDENTIFICATION_NUMBER" ) "Pay Plan"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 			
						(HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."PAY_PLAN") as "PAY_PLAN"
							from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") d
						group by   d."VACANCY_IDENTIFICATION_NUMBER" 
						order by   d."VACANCY_IDENTIFICATION_NUMBER"			
					) pp
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = pp."VACANCY_IDENTIFICATION_NUMBER"
				
				left join
					(select  c."VACANCY_NUMBER", 
						LISTAGG(c."VCNCY_MISSION_CRITICAL_OCCUPTN" , ';')
						within group (order by c."VACANCY_NUMBER" ) "Special Tracking"
						from  
						(select distinct  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VACANCY_NUMBER", 
							HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VCNCY_MISSION_CRITICAL_OCCUPTN"
							from  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN" ) c
						group by   c."VACANCY_NUMBER" 
						order by   c."VACANCY_NUMBER"			
					) mco
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = mco."VACANCY_NUMBER"
				left join  HHS_WHRSC_HR."ANNOUNCEMENT" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" =  HHS_WHRSC_HR."ANNOUNCEMENT"."VIN" 
				left join  HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION"."VACANCY_NUMBER" 
				left join
					(SELECT  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER", 
							count( HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER") as "Number of Certs", 
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_CERTIFICATE_ISSUED") as "First Cert Issue Date",
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_HIRING_DECISN_RECD_IN_HR") as "First Cert Return Date" 
						FROM  HHS_WHRSC_HR."DSS_CERTIFICATES" 
							left join  HHS_WHRSC_HR."CERTIFICATE" 
								on  HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER" =  HHS_WHRSC_HR."CERTIFICATE"."CERT_NUMBER" 
						group by  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 
						order by HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 			
					) cert_combined
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = cert_combined."VACANCY_IDENTIFICATION_NUMBER"		
				) vac_cert_combined
				on  HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" = vac_cert_combined."REQUEST_NUMBER" 
			left join (SELECT *
				FROM HHS_WHRSC_HR."DSS_NEW_HIRES"
				left join HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS" 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS"."NEW_HIRE_NUMBER"
				left join 
					(select distinct HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NEW_HIRE_NUMBER", HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NH_REQUEST_NUMBER"
						from  HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST" 
					) nhvr 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = nhvr."NEW_HIRE_NUMBER"		
				) nh_combined
				on HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" =nh_combined."NH_REQUEST_NUMBER"
			left join 		
				(select distinct HHS_WHRSC_HR."BRANCHES"."IC" , HHS_WHRSC_HR."BRANCHES"."BRANCH"
				from  HHS_WHRSC_HR."BRANCHES" )Branch
				on   HHS_WHRSC_HR."MAIN"."INSTITUTE" = Branch."IC" 
		) main_combined
		on  HHS_WHRSC_HR."RECRUITMENT"."TRANSACTION_ID" = main_combined."TRANSACTION_ID"
	
		where STATUS = 'ACTIVE';
--===================================================================
CREATE OR REPLACE VIEW HHS_WHRSC_HR.VW_ALL_RECRUITMENTS_EXPAND AS
--===================================================================
SELECT 
	main_combined.*,
	 HHS_WHRSC_HR."RECRUITMENT"."RECRUITMENT_TYPE",
	 HHS_WHRSC_HR."RECRUITMENT"."LEGISLATIVE_INIT_SUPPORTED", 
	HHS_WHRSC_HR."RECRUITMENT"."DATE_REC_PCKG_SENT_APPROVED",
	null as "Investigation Complete"
FROM  HHS_WHRSC_HR."RECRUITMENT" 
	left join 
		(SELECT  
			HHS_WHRSC_HR."MAIN"."TRANSACTION_ID",
			HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID",
			Branch."BRANCH", 
			HHS_WHRSC_HR."MAIN"."INSTITUTE",
			HHS_WHRSC_HR."MAIN"."ADMIN_CODE",
			HHS_WHRSC_HR."MAIN"."ORG_INITS",
			HHS_WHRSC_HR."MAIN"."HR_SPECIALIST",
			HHS_WHRSC_HR."MAIN"."GLOBAL_RECRUITMENT", 
			 vac_cert_combined."ANNOUNCEMENT_TYPE",
			 vac_cert_combined."OPEN_CONTINUOUS_ANN", 
			 vac_cert_combined."Special Tracking",
			 vac_cert_combined."Locations",
			 vac_cert_combined."POSITION_TITLE",
			 vac_cert_combined."Pay Plan",
			 vac_cert_combined."Series",
			 vac_cert_combined."Grade",
			 vac_cert_combined."FULL_PERFORMANCE_LEVEL", 
			 HHS_WHRSC_HR."MAIN"."DATE_RECEIVED",
			 HHS_WHRSC_HR."MAIN"."MISSING_DOCS_RECEIPT_DATE",
			 HHS_WHRSC_HR."MAIN"."COMMENTS_STATUS",
			 HHS_WHRSC_HR."MAIN"."RYB_STATUS",
			  HHS_WHRSC_HR."MAIN"."STATUS" 
		FROM HHS_WHRSC_HR."MAIN" 
			left join
				(SELECT *
			FROM  HHS_WHRSC_HR."DSS_VACANCY" 
			 left join 
				(select  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG( HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."LOCATION_CITY" , '; ')
						within group (order by HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" ) "Locations"
						from  HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS" 
						group by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
						order by   HHS_WHRSC_HR."DSS_VACANCY_LOCATIONS"."VACANCY_IDENTIFICATION_NUMBER" 
					) loc
					 on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = loc."VACANCY_IDENTIFICATION_NUMBER"  
				left join 
					(select  a."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(a."SERIES" , ',')
						within group (order by a."VACANCY_IDENTIFICATION_NUMBER" ) "Series"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 
						HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."SERIES" from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") a
						group by   a."VACANCY_IDENTIFICATION_NUMBER" 
						order by   a."VACANCY_IDENTIFICATION_NUMBER" 			
					) ser
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = ser."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  b."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(b."GRADE" , ',')
						within group (order by b."VACANCY_IDENTIFICATION_NUMBER" ) "Grade"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 			
						to_char(HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."GRADE", '99') as "GRADE"
							from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") b
						group by   b."VACANCY_IDENTIFICATION_NUMBER" 
						order by   b."VACANCY_IDENTIFICATION_NUMBER"			
					) gra
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = gra."VACANCY_IDENTIFICATION_NUMBER"
				left join
					(select  d."VACANCY_IDENTIFICATION_NUMBER", 
						LISTAGG(d."PAY_PLAN" , ',')
						within group (order by d."VACANCY_IDENTIFICATION_NUMBER" ) "Pay Plan"
						from  
						(select distinct HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."VACANCY_IDENTIFICATION_NUMBER", 			
						(HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION"."PAY_PLAN") as "PAY_PLAN"
							from HHS_WHRSC_HR."DSS_VACANCY_RATING_COMBINATION") d
						group by   d."VACANCY_IDENTIFICATION_NUMBER" 
						order by   d."VACANCY_IDENTIFICATION_NUMBER"			
					) pp
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = pp."VACANCY_IDENTIFICATION_NUMBER"
				
				left join
					(select  c."VACANCY_NUMBER", 
						LISTAGG(c."VCNCY_MISSION_CRITICAL_OCCUPTN" , ';')
						within group (order by c."VACANCY_NUMBER" ) "Special Tracking"
						from  
						(select distinct  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VACANCY_NUMBER", 
							HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN"."VCNCY_MISSION_CRITICAL_OCCUPTN"
							from  HHS_WHRSC_HR."DSS_VAC_MISSION_CRITCL_OCCUPTN" ) c
						group by   c."VACANCY_NUMBER" 
						order by   c."VACANCY_NUMBER"			
					) mco
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = mco."VACANCY_NUMBER"
				left join  HHS_WHRSC_HR."ANNOUNCEMENT" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" =  HHS_WHRSC_HR."ANNOUNCEMENT"."VIN" 
				left join  HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION" 
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = HHS_WHRSC_HR."DSS_REQUEST_VACNCY_COMBINATION"."VACANCY_NUMBER" 
				left join
					(SELECT  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER", 
							count( HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER") as "Number of Certs", 
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_CERTIFICATE_ISSUED") as "First Cert Issue Date",
							min(HHS_WHRSC_HR."DSS_CERTIFICATES"."DATE_HIRING_DECISN_RECD_IN_HR") as "First Cert Return Date" 
						FROM  HHS_WHRSC_HR."DSS_CERTIFICATES" 
							left join  HHS_WHRSC_HR."CERTIFICATE" 
								on  HHS_WHRSC_HR."DSS_CERTIFICATES"."CERTIFICATE_NUMBER" =  HHS_WHRSC_HR."CERTIFICATE"."CERT_NUMBER" 
						group by  HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 
						order by HHS_WHRSC_HR."DSS_CERTIFICATES"."VACANCY_IDENTIFICATION_NUMBER" 			
					) cert_combined
					on HHS_WHRSC_HR."DSS_VACANCY"."VACANCY_IDENTIFICATION_NUMBER" = cert_combined."VACANCY_IDENTIFICATION_NUMBER"		
				) vac_cert_combined
				on  HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" = vac_cert_combined."REQUEST_NUMBER" 
			left join (SELECT *
				FROM HHS_WHRSC_HR."DSS_NEW_HIRES"
				left join HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS" 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = HHS_WHRSC_HR."DSS_NEW_HIRE_TASKS"."NEW_HIRE_NUMBER"
				left join 
					(select distinct HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NEW_HIRE_NUMBER", HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST"."NH_REQUEST_NUMBER"
						from  HHS_WHRSC_HR."DSS_NEW_HIRE_VACANCY_REQUEST" 
					) nhvr 
					on HHS_WHRSC_HR."DSS_NEW_HIRES"."NEW_HIRE_NUMBER" = nhvr."NEW_HIRE_NUMBER"		
				) nh_combined
				on HHS_WHRSC_HR."MAIN"."JOB_OPENING_ID" =nh_combined."NH_REQUEST_NUMBER"
			left join 		
				(select distinct HHS_WHRSC_HR."BRANCHES"."IC" , HHS_WHRSC_HR."BRANCHES"."BRANCH"
				from  HHS_WHRSC_HR."BRANCHES" )Branch
				on   HHS_WHRSC_HR."MAIN"."INSTITUTE" = Branch."IC" 
		) main_combined
		on  HHS_WHRSC_HR."RECRUITMENT"."TRANSACTION_ID" = main_combined."TRANSACTION_ID";
--====================================================