----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_APPLICANT_NOTIFICATNSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_CERTIFICATE_LOCATIONSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_CERTIFICATESTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_FORMSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_ONBRDNG_DOCSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_TASKSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_VACNCY_REQTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRESTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_PERMISSION_PROFILESTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUEST_LOCATIONSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUEST_RATING_COMBTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUEST_VACNCY_COMBTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUESTSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCYTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY_ELIGIBILITIESTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY_LOCATIONSTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VAC_MISSN_CRITCL_OCCTO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY_RATING_COMBTO HHS_WHRSC_HR_RW_ROLE;
