

----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_APPLICANT_NOTIFICATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_CERTIFICATE_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_CERTIFICATES TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_NEW_HIRE_FORMS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_NEW_HIRE_ONBOARDING_DOCS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_NEW_HIRE_TASKS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_NEW_HIRE_VACANCY_REQUEST TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_NEW_HIRES TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_PERMISSION_PROFILES TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_REQUEST_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_REQUEST_RATING_COMBINATION TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_REQUEST_VACNCY_COMBINATION TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_REQUESTS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_VACANCY TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_VACANCY_ELIGIBILITIES TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_VACANCY_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_VAC_MISSION_CRITCL_OCCUPTN TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.DSS_VACANCY_RATING_COMBINATION TO HHS_WHRSC_HR_RW_ROLE;
