--=============================================================================
-- Grant privileges on objects under WHRSC schema to roles
-------------------------------------------------------------------------------


-- privilege for HHS_WHRSC_HR_RW_ROLE;


GRANT EXECUTE ON HHS_WHRSC_HR.FN_GET_BRANCH_FOR_AN_IC TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.FN_GET_DEPUTY_FOR_AN_IC TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.FN_GET_RECRUITMENT_PRE_VAL TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.FN_GET_RECRUITMENT_EMAIL_TBL TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.FN_GET_RECRUITMENT_SLA_VACAN TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.FN_GET_RECRUITMENT_EMAIL_TB_AP TO HHS_WHRSC_HR_RW_ROLE;

GRANT EXECUTE ON HHS_WHRSC_HR.SP_SEND_MAIL TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_JOB_RECRUITMENT_PRE_VALID TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_JOB_RECRUITMENT_SLA_POST TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_JOB_RECRUITMENT_SLA_CERT_EX TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_JOB_RECRUITMENT_JOB_TENT TO HHS_WHRSC_HR_RW_ROLE;