----------------------------------
-- grant for HHS_WHRSC_HR_RW_ROLE
----------------------------------

GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_APPLICANT_NOTIFICATNS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_CERTIFICATE_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_CERTIFICATES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_FORMS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_ONBRDNG_DOCS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_TASKS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRE_VACNCY_REQ TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_NEW_HIRES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_PERMISSION_PROFILES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUEST_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUEST_RATING_COMB TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUEST_VACNCY_COMB TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_REQUESTS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY_ELIGIBILITIES TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY_LOCATIONS TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VAC_MISSN_CRITCL_OCC TO HHS_WHRSC_HR_RW_ROLE;
GRANT EXECUTE ON HHS_WHRSC_HR.SP_TRUNC_VACANCY_RATING_COMB TO HHS_WHRSC_HR_RW_ROLE;
