SET DEFINE OFF;

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.RECRUITMENT_ACTION_STATUS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.RECRUITMENT_ACTION_HISTORY TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.RDR_ATTACH TO BIZFLOW;

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.CHR_PROCESSED_JOBS TO HHS_WHRSC_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_WHRSC_HR.CHR_EMPLOYEE TO HHS_WHRSC_HR_RW_ROLE;

